### ISSUE TITLE
non-ascii characters

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1005]
The following files have non-ascii characters at the beginning. Renaming any model with the BuildingsPy rename function will cause changes in these models.
```
Media/Refrigerants/R410A/isentropicExponentVap_Tv.mo
Media/Refrigerants/R410A/package.mo
Media/Refrigerants/R410A/specificIsobaricHeatCapacityVap_Tv.mo
Media/Refrigerants/R410A/specificIsochoricHeatCapacityVap_Tv.mo
```

**Comment by thorade** [comment]
These four files also have a wide dash here:
`Martin–Hou equation of state — part`
