### ISSUE TITLE
Replace if statement with if expression in smoothTransition

### ISSUE THREAD

**Issue by dhblum** [ibpsa/modelica-ibpsa#1019]
I was wondering if the following if statement in the function `IBPSA.Utilities.Math.Functions.BaseClasses.smoothTransition` could be replaced by the suggested if expression?  This would allow its use in JModelica optimization for MPC.  Namely, the model `IBPSA.Fluid.MixingVolumes.BaseClasses.PartialMixingVolume` if the parameter `prescribedHeatFlowRate = true`.

from:

``` 
algorithm 
 aX:= abs(x);
 y := a + aX*(b + aX*(c + aX*(d + aX*(e + aX*f))));
 if x < 0 then
    y := -y;
 end if;
```
to:

```
algorithm 
 aX:= abs(x);
 y := if x >= 0 then a + aX*(b + aX*(c + aX*(d + aX*(e + aX*f)))) else 
 -(a + aX*(b + aX*(c + aX*(d + aX*(e + aX*f)))));
```

I could submit a pull request.

**Comment by Mathadon** [comment]
fine by me, although this would require fewer operations in CasADi:

```
algorithm 
 aX:= abs(x);
 y := (if x >= 0 then 1 else -1) * a + aX*(b + aX*(c + aX*(d + aX*(e + aX*f))));
```

**Comment by dhblum** [comment]
Sounds good, that works too.
