### ISSUE TITLE
Fluid.Movers with Modelica.Media.IdealGases.MixtureGases on OpenModelica

### ISSUE THREAD

**Issue by kiddjmadd** [ibpsa/modelica-ibpsa#1037]
I duplicated the "PowerExact" example and deleted the dP and mass flow controlled pumps to see how different Media worked with the RPM-controlled pump. I was able to run the model with IBPSA.Media.Air, Modelica.Media.Water.StandardWater and Modelica.Media.Air.SimpleAir but it failed on all the Modelica.Media.IdealGases.MixtureGases that I tried. Error message is below. Not sure whether this applies to other implementations, but wanted to report for evaluation. 

I'm using stable version, "OMEdit v1.12.0 (64-bit) Connected to v1.12.0 (64-bit)"

Compilation completes but error below appears when application tries to simulate:

"This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information. 

a->dim_size[0] != b->dim_size[0], 8 != 6

Simulation process failed. Exited with code 3."

**Comment by thorade** [comment]
The applications support team would be the OpenModelica development team.
The best thing you could do is run the same model again and send in a stacktrace. If you leave your email, they might even contact you back. Are you on Windows or on Linux? Is using the latest OMC nightly an option?

Maybe a similar issue is already filed?
https://trac.openmodelica.org/OpenModelica/wiki/CoverageIssues#Buildings
https://libraries.openmodelica.org/branches/master/IBPSA_latest/IBPSA_latest.html
https://libraries.openmodelica.org/branches/newInst/IBPSA_latest/IBPSA_latest.html

**Comment by kiddjmadd** [comment]
Hi Mattis,
I'm on Windows but can try with nightly builds on Linux and Windows also. I'll need to switch to nightly on Windows anyways due to an issue I'm having with pump from Modelica.Fluids.Machines. 
Go ahead and close out if this isn't something with the library itself. Thanks for your response.

Jesse

**Comment by thorade** [comment]
I believe sending in a minimal model that crashes OpenModelica should help them to fix that. After that fix, the model will probably still not run, and that might be partly due to how it is modeled here in the library. I would still close this ticket for now, but you can reopen it any time once you have new feedback.
If you plan to keep using the nightlies, then my experience is that it is worth setting up a virtual Linux/Ubuntu machine, because you can install upates more easily.
