### ISSUE TITLE
cyclic weather data reader

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1038]
The weather data reader outputs currently automatically repeat themselves after one year, even if the table contains more data because of the use of `IBPSA.BoundaryConditions.WeatherData.BaseClasses.ConvertTime`.

This means that weather data files containing more than 1 year of data will discard the data that comes after 3.15e7 seconds and jump back to the start of the file. Furthermore, weather data files that use an epoch time stamp as the time index simply do not work. 

This puts constraints on how the data reader can be used. The reason for this is not clear to me. I propose to remove this block and to use `CombiTimeTable` instead of `CombiTimeTable1Ds`. This also has more options for events, interpolation and extrapolation. The impact on events, accuracy and simulation time should however be checked.

**Comment by mlauster** [comment]
@Mathadon, can this be solved in one step together with #842? Both topics might intefer.

**Comment by Mathadon** [comment]
@mlauster indeed, this looks related. How do you propose to proceed?

**Comment by mlauster** [comment]
@Mathadon, could you have a look if https://github.com/ibpsa/modelica-ibpsa/tree/issue842_multiyear solves your problem? I don't know if it still uses `CombiTimeTable1Ds` or `CombiTimeTable` instead or if there were any reasons to take whatever is in there.
If you see further need for modifications, feel free to work on that branch. I will clean up the examples for testing.
I suggest to close this issue and take the discussions to #842.

**Comment by mwetter** [comment]
Closed as it is on the master branch.
