### ISSUE TITLE
CSV writer precision

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1041]
The CSV writer prints only 6 significant digits by default, which is a problem when using unix time stamps since this results in entries such as `1.51476e+09`, consequently rounding time to about 10000s. This should be fixed.

**Comment by Mathadon** [comment]
Matrixop.c contains the following code that corresponds to the Modelica code `String( _someReal_ )`:

```
DYMOLA_STATIC String Real2String3(Real x,Integer leftJustified,Integer minwidth,Integer precision) {
        char buf[100];
        char*ret;
        Assert(precision<40 && minwidth<40,"");
        sprintf(buf,leftJustified?"%-*.*g":"%*.*g",(int)minwidth,(int)precision,(double)x);
        ret=StringAllocate(strlen(buf));
        strcpy(ret,buf);
        return ret;
}
DYMOLA_STATIC String Real2String2(Real x,Integer leftJustified,Integer minwidth) {
        return Real2String3(x,leftJustified,minwidth,6);
}
```

this implies that the precision of 6 digits is hardcoded. However it can be changed in matrixop by the user. Do we want to create a custom but C implementation for converting a `Real` into a `String` when higher precisions are required?

**Comment by Mathadon** [comment]
It would! =) I'll test that implementation and revise the pull request accordingly :)

**Comment by thorade** [comment]
Just learned that the real to string conversion also accepts a format option, like this:
```
str :=String(time, format="10.2f")
```
https://stackoverflow.com/a/17989/874701
