### ISSUE TITLE
In StaticTwoPortConservationEquation, trigger a warning rather than an error in energy balance check

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1048]
In `StaticTwoPortConservationEquation`, the check for the energy balance
```modelica
  if prescribedHeatFlowRate then
    assert(noEvent( abs(Q_flow) < dTMax*cp_default*max(m_flow_small/1E3, abs(m_flow))),
   "In " + getInstanceName() + ":
   The heat flow rate equals " + String(Q_flow) +
   " W and the mass flow rate equals " + String(m_flow) + " kg/s,
   which results in a temperature difference " +
   String(abs(Q_flow)/ (dTMax*cp_default*max(m_flow_small/1E3, abs(m_flow)))) +
   " K > dTMax=" +String(dTMax) + " K.
   This may indicate that energy is not conserved for small mass flow rates.
   The implementation may require prescribedHeatFlowRate = false.");
  end if;
```
is heuristic and hence should trigger a warning rather than an error that stops the simulation.

**Comment by Mathadon** [comment]
@mwetter this assert is evaluated on each time step so this may generate a huge number of warnings?

**Comment by mwetter** [comment]
@Mathadon : I revised the implementation.

The new implementation can be tested with
```
simulateModel("IBPSA.Fluid.MassExchangers.Examples.ConstantEffectiveness", stopTime=360, method="dassl", tolerance=1e-06, resultFile="ConstantEffectiveness");
```
This writes a warning if in `StaticTwoPortConservationEquation`, the line
```modelica
    QMaxVio_flow = dTMax*cp_default*max(m_flow_small/1E3, abs(m_flow));
```
is replaced with (to trigger a warning during simulation)
```modelica
    QMaxVio_flow = 0.05^time*dTMax*cp_default*max(m_flow_small/1E3, abs(m_flow));
```
or with (to trigger a warning during initialization)
```modelica
    QMaxVio_flow = dTMax*cp_default*max(m_flow_small/1E3, abs(m_flow));
```

The warning is of the form
```
Warning: The following was detected at time: 0
  In ConstantEffectiveness.hex.bal2.vol:
   Heat flow rate Q_flow =13548.3 W and mass flow rate m_flow = 1.11803 kg/s.
   This yields a temperature difference of 238.885 K > dTMax = 200 K.
   This indicates that energy is not conserved for small mass flow rates.
   The implementation may require prescribedHeatFlowRate = false.
   No further warnings will be written for this energy balance.
  Failed condition: noEvent(abs(hex.Q1_flow) < hex.bal2.vol.QMaxVio_flow)
```

**Comment by mwetter** [comment]
After https://github.com/ibpsa/modelica-ibpsa/commit/17890bcea6e91bd5518f8040462b75762cb13fe0 there is a 6x6 nonlinear equation in Simplified4, which used to be 5x5.
This is caused by the use of `Q_flow` in the `when` construct, e.g., adding
```modelica
when Q_flow >= 0 then
 checkHeatFlowRate = false;
end when;
```
also causes a 6x6 nonlinear equation.

I don't see how to print this statement only once (other than implementing the print in a C function with a static variable) while not increasing the dimension of this nonlinear system of equation. I will therefore close this issue.  We can reopen if there is a test case in which the heuristics fails (our test problem is now fine after fixing other issues in the model).

**Comment by Mathadon** [comment]
@mwetter the implementation that you proposed would also not properly catch an error at time t >> 0.

**Comment by Mathadon** [comment]
Should be possible to do something like:

```
discrete Boolean errorThrown;

initial equation
errorThrown=false;

equation
when Q_flow>thresHold and not pre(errorThrown) then
  errorThrown=true;
  assert(false, "error message")
end when;
```
Or something similar if asserts cannot be within a when statement.

**Comment by mwetter** [comment]
@Mathadon : I tried such a setup with a `when` construct but this increased the size of the nonlinear equation. For now I suggest to leave this closed.
