### ISSUE TITLE
Provide easier to understand choice when selecting a media

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1050]
I observed that (new) users often have problems selecting a media. This is not surprising, as the default Medium list looks like this:
![screenshot at 2018-11-09 14-16-31](https://user-images.githubusercontent.com/1329080/48291123-1d87d280-e42a-11e8-86d9-a7893df77f93.png)

I suggest we constrain the media that show up in the dialog box to these:
![screenshot at 2018-11-09 14-16-00](https://user-images.githubusercontent.com/1329080/48291143-31333900-e42a-11e8-8778-8ced58edebb6.png)

This can be done with the declaration
```modelica
  replaceable package Medium =
    Modelica.Media.Interfaces.PartialMedium "Medium in the component"
      annotation (choices(
        choice(redeclare package Medium = IBPSA.Media.Air "Moist air"),
        choice(redeclare package Medium = IBPSA.Media.Water "Water"),
        choice(redeclare package Medium = IBPSA.Media.Antifreeze.PropyleneGlycolWater(
          property_T=293.15,
          X_a=0.40)
          "Propylene glycol water")));
```
This ticket is to make such an implementation. I suggest we don't include the media in `IBPSA.Media.Specialized` as these are in my view of little use to almost all users. Advanced users who really have a need for such media can still enter them manually rather than through the pull down menu.

**Comment by JayHuLBL** [comment]
@mwetter 
- [x] restricted media selection, except the models in package `Fluid.Sensors`.
- [ ] in some models like `Fluid.Sources.FixedBoundary`, it extends `Modelica.Fluid.Sources.BaseClasses.PartialSource`. When instantiating the model, it still has many media options. Should it extends `IBPSA.Fluid.Sources.BaseClasses.PartialSource` so to have restricted media options?

**Comment by mwetter** [comment]
@JayHuLBL Please extend from `IBPSA.Fluid.Sources.BaseClasses.PartialSource` if this simplifies the medium choice for the user.

**Comment by mwetter** [comment]
@JayHuLBL : 
- [ ] The two sources used in `Examples.MassFlowSource_WeatherData` also need to be updated.
- [ ] `Sources.FixedBoundary` need to be updated, using a different base class.
