### ISSUE TITLE
Refactor Fluid.Sources

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1072]
This issue is to refactor the `Fluid.Sources` package to avoid repeated use of the same base class. Currently, JModelica issues the warning:
```
In component bou:
  The component nPorts is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 11, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component verifyInputs is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 15, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component ports is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 24, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component flowDirection is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 26, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component p_in_internal is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 29, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component Xi_in_internal is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 32, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component X_in_internal is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 35, column 3, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
In component bou:
  The component C_in_internal is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.
Warning at line 43, column 12, in file '/mnt/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo',
```
I suggest that these models are refactored after https://github.com/ibpsa/modelica-ibpsa/pull/1052 is merged.

As part of this refactoring, I think `FixedBoundary` could be removed as `Boundary_pT` or `Boundary_ph` can as well be used.

**Comment by mwetter** [comment]
Remove `FixedBoundary`, and check how to avoid warnings either by code changes or changes in JModelica.

**Comment by mwetter** [comment]
- [ ] check if `verifyInputs` is used/needed.

**Comment by JayHuLBL** [comment]
@mwetter Following changes have been implemented:
- [x] updated models that use `IBPSA.Sources.FixedBounday`, by replacing `IBPSA.Sources.FixedBounday` with `IBPSA.Sources.Boundary_pT`.
- [x] created package `IBPSA.Obsolete`.
- [x] moved `IBPSA.Sources.FixedBounday` to `IBPSA.Obsolete`.
- [x] added obsolete annotation in `IBPSA.Obsolete.FixedBoundary`, so when any class instantiates the class, run the class will trigger a warning.
```
Component type specifier FixedBoundary specified an obsolete type: Obsolete model - use IBPSA.Fluid.Sources.Boundary_pT or IBPSA.Fluid.Sources.Boundary_ph instead.
```
- [x] added `convertObsolete.mos` file to folder `IBPSA/Resources/Scripts/Dymola/` and made change in `package.mo` file as below:
```
annotation (
version="3.0.0",
versionDate="2018-09-28",
dateModified = "2018-09-28",
uses(Modelica(version="3.2.2")),
conversion(from(version="3.0.0",
                script="modelica://IBPSA/Resources/Scripts/Dymola/ConvertObsolete.mos")),
```

Would you please let me know if any other change should be implemented before I do pull request?

**Comment by mwetter** [comment]
@JayHuLBL : Can you please make the following changes:
- [ ] `IBPSA/Resources/Scripts/Dymola/ConvertObsolete.mos` should be called `IBPSA/Resources/Scripts/Dymola/ConvertIBPSA_from_3.0_to_4.0.mos`
- [ ] Correct the package structure `IBPSA.ObsoleteModels` so that it is `IBPSA.Obsolete.Fluid.Sources` [and then reproduce the moved models in this package, using one file for each model (rather than putting `FixedBoundary` into the `package.mo` file).
- [ ] Correct the conversion script to rename `IBPSA.Fluid.Sources.FixedBoundary` to `IBPSA.Obsolete.Fluid.Sources.FixedBoundary`. You cannot rename it to `Boundary_pT` because a user may have set parameters that are only declared in `FixedBoundary` and then a converted model becomes invalid.
