### ISSUE TITLE
analyse convergence of algebraic loops with from_dp=true for valves

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1073]
We should check the convergence influence when defaulting `from_dp=true` for valves.

**Comment by Mathadon** [comment]
to verify statistics in https://travis-ci.org/ibpsa/modelica-ibpsa/builds/476808709?utm_source=github_status&utm_medium=notification

**Comment by mwetter** [comment]
@Mathadon There is no clear trend in the statistics, for example,
```
*** Warning: Simplified1.mat: Translation statistics for initialization changed for nonlinear, but results are unchanged.
 Old = 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1
 New = 0, 0, 17, 0, 0, 0, 0, 1, 0, 1, 1, 1
*** Warning: Simplified1.mat: Translation statistics for simulation changed for nonlinear, but results are unchanged.
 Old = 0, 0, 7, 0, 1, 0, 1, 1, 1
 New = 0, 0, 18, 0, 1, 0, 1, 1, 1
```
If you have better experience with the new formulation, I would say we go ahead with it. Otherwise let's leave it as is.

**Comment by Mathadon** [comment]
Were there convergence issues in the unit tests of JModelica? Perhaps those are solved by this change? Otherwise I would check this issue again once we run into convergence issues again somewhere.
