### ISSUE TITLE
FMI with DynamicFreeInitial + media.density as a function of state variables

### ISSUE THREAD

**Issue by veeshy** [ibpsa/modelica-ibpsa#1089]
From the user's guide on FMI, the Fluid.FMI.ExportContrainers.ReplaceableTwoPort interface suggests a media's density should not depend on pressure, or else the dynamics must be set to steady-state because a translation error needing derivatives of input.p will result.

I'd like to be able to use a media that has density(state variables) as well as solve with DynamicFreeInitial. Any thoughts on how to accomplish this?

**Comment by mwetter** [comment]
If the tool reports that it needs the derivative of `input.p`, then you will need to add an input, say `der_p` and set `der(input.p) = der_p` in your model. (Of course, this requires that you know the value of `der_p` and hence can set it as an input to the FMU.)

**Comment by veeshy** [comment]
Nice idea, my external solver does have that inlet der to supply. I tried but found dymola says `Differentiation of an input, der(inlet.p), is not supported.`. I'm just modeling a pipe for demonstration purposes and looked a little harder at what is wanting the inlet.p der and it's a der(pipe.mediums[1].p) = der(inlet.p). Trying to set this der directly leads to an over determined system.
