### ISSUE TITLE
ConstantEffectiveness sets prescribedHeatFlowRate = true

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1101]
This model should have `prescribedHeatFlowRate = false` because the rate of heat transfer is driven by the temperature difference.

This applies for the `MassExchangers.ConstantEffectiveness` and `HeatExchangers.ConstantEffectiveness`.

**Comment by Mathadon** [comment]
I'm not sure what the point is of removing this parameter? Having it avoids problems in case we would change the default to `prescribedHeatFlowRate=false` in the base class?

**Comment by mwetter** [comment]
I meant to change the base class to use `false`, but now saw
https://github.com/ibpsa/modelica-ibpsa/issues/907
with the justification for setting `prescribedHeatFlowRate=true`.

Hence, this issue can be closed and the branch deleted.
