### ISSUE TITLE
outputting start date of simulation

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1104]
The weather data reader is not always used correctly. E.g. someone may use a weather file that starts in August instead of in January for t=0. One way of avoiding this would be to generate a print statement for each model (e.g. using `ModelicaFormatMessage()` in `C`) that essentially prints the data and time when the simulation starts. That should catch attention.. Quite some implementation work in C though. Good idea?

This is linked to https://github.com/open-ideas/IDEAS/issues/929

**Comment by mwetter** [comment]
@Mathadon I don't think this is still needed when #842 is closed through #1096

**Comment by Mathadon** [comment]
ok!
