### ISSUE TITLE
Long-term temperature changes of geothermal bore fields

### ISSUE THREAD

**Issue by MassimoCimmino** [ibpsa/modelica-ibpsa#1107]
There is an issue with the integration of the finite line source solution in `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.finiteLineSource`. The upper bound of integration (in theory infinite) is set to 100.0. This is a correct upper limit for typical boreholes with diameters of the order of 6 inches.

However, in the implementation of the thermal response we decided to evaluate the finite line source analytical solution at a radius `radius = 0.0005*length`. For shorter boreholes (approx. 25 m or less), the radius becomes small and the integrand function is still non-negligible at a value of 100.0. The figure below shows the logarithm (log10) of the integrand.

![FiniteLineSource_Integrand_BoreholeLength](https://user-images.githubusercontent.com/23085996/54496680-a1fecc00-48c8-11e9-8f20-3d81e55f7840.png)

This causes issues with the calculation of the thermal response, and becomes progressively worse with decreasing borehole length, as shown below for a 5 meter borehole (the thermal response should be strictly positive).

![GFunction_1borehole_5meters](https://user-images.githubusercontent.com/23085996/54496730-31a47a80-48c9-11e9-93d4-fbf2bcf27747.png)

A conservative estimate for the upper bound of integration is `10/radius`, or `20000/length` in our case. This corrects the thermal response, see below.

![GFunction_1borehole_5meters_fixed](https://user-images.githubusercontent.com/23085996/54496798-b2fc0d00-48c9-11e9-8041-f76baca201f9.png)

**Comment by MassimoCimmino** [comment]
A validation case was added in `IBPSA.Fluid.Geothermal.Borefields.Validation.ConstantHeatInjection_100Boreholes` to verify that the soil temperature change follows the g-function (calculated in `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Examples.GFunction_100boreholes`). This validates that the total heat transfer rate is correctly divided between the boreholes in the borefield.

**Comment by MassimoCimmino** [comment]
Added an output that returns the average temperature along the wall of the boreholes in the borefield. This output was previously not available, as borehole segments may have different temperatures due to the ground temperature gradient.
![Capture](https://user-images.githubusercontent.com/23085996/58889698-597cd080-86b7-11e9-8d17-9ad8a1e4180a.PNG)

**Comment by mwetter** [comment]
The command
```
jm_ipython.sh jmodelica.py IBPSA.Fluid.Geothermal.Borefields.Validation.ConstantHeatInjection_100Boreholes
```
fails with a compilation error. The problematic assignment is
```
cooBor={{7.5*mod(i-1,10), 7.5*floor((i-1)/10)} for i in 1:100}
```
in `IBPSA.Fluid.Geothermal.Borefields.Validation.BaseClasses.ConstantHeatInjection_100Boreholes_Configuration`
If I replace this assignment with the actual matrix, the model simulates. I made this change in https://github.com/ibpsa/modelica-ibpsa/commit/e17b45d0419e9cf6a4f5ad56d37a225405608e8d and filed a support request to Modelon to correct this issue. Once fixed, we can revert this change.

**Comment by mwetter** [comment]
I reopen this issue for testing of `cooBor={{7.5*mod(i-1,10), 7.5*floor((i-1)/10)} for i in 1:100}` for JModelica, revision 12903.
