### ISSUE TITLE
getTimeSpan (used by weather data reader) fails on some Windows installations

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1108]
On some Windows installations (namely the JModelica Jenkins CI), the weather data reader fails to simulate. The simulation log is
```
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning]   <ModelicaError category="warning"><value name="msg">"Syntax error at character 1 of&#10;ICAL/EXTREME PERIODS,6,Summer - Week Nearest Max Temperature ...&#10;Syntax error at character 1 of&#10;ICAL/EX"</value></ModelicaError>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]   <DependentParametersEvaluationFailed category="error">Error evaluating dependent parameters and start values</DependentParametersEvaluationFailed>
FMIL: module = Model, log level = 2: [INFO][FMU status:Error]   Error evaluating dependent parameters. Initialization failed.
Enter Initialize returned with an error. Enable logging for more information, (FMUModel(..., enable_logging=True)).
```
The error is caused by `IBPSA.BoundaryConditions.WeatherData.BaseClasses.getTimeSpanTMY3`.

It appears that correcting the line endings from Unix to Windows fixes this problem, but this would not be robust as users may provide weather files with Unix file endings.

We should consider rewriting `getTimeSpan` to simply use C with `fscanf` to do this file parsing.

@AnaConstantin : For this we should also add regression test which are missing for `getTimeSpanTMY3`.

**Comment by AnaConstantin** [comment]
@mwetter sure, I can add a regression test (we are able to do this now. Yey!). Could you please create a branch for the issue?

**Comment by AnaConstantin** [comment]
If you decide on rewriting the function in C, I think it's good to think about a check for the average increment of the weather file. At this moment it is (lastTimeStamp - firstTimeStamp) / (nrRows -1), but this works only for weather files with equidistant time stamps. If data is missing or if time stamps repeat (as is the case with raw data) the weather data will not be repeated if the simulation goes beyond a year, but the error message will not be clear. Let me know what you think. 
For now I can add the information in the documentation of ReaderTMY3.mo and additional outputs in the assert in ConvertTime.mo (weaDatStaTim and weaDatEndTim).

**Comment by mwetter** [comment]
@AnaConstantin : Please use the branch `issue1108_getTimeSpanTMY3` which I created now.

**Comment by mwetter** [comment]
@JayHuLBL : Can you please reimplement `getTimeSpanTMY3.mo` by calling a C function, using the branch `issue1108_getTimeSpanTMY3`

**Comment by JayHuLBL** [comment]
@mwetter I have reimplemented the `getTimeSpanTMY3.mo` by calling a C function `getTimeSpan.c` in `Resources/C-Sources/`, in branch `issue1108_getTimeSpanTMY3`.

**Comment by mwetter** [comment]
@JayHuLBL : I corrected the implementation of branch `issue1108_getTimeSpanTMY3`, added a check for successful use of `malloc` and corrected the comments so that the file compiles with JModelica too.

Can you please address the following
- [ ] Add an example where the initial time is not zero. You can read the file `IBPSA/Resources/Data/BoundaryConditions/WeatherData/Validation/DecemberToJanuary.mos` for this validation.
- [ ] You use fixed array size of 500. Why not simply using https://linux.die.net/man/3/getline which will make sure that the buffer is sufficiently long?
- [ ] JModelica has various "warning: ignoring return value ...". Please address these and use the return value to make sure the function call is successful. 
- [ ] Remove the debug output

**Comment by JayHuLBL** [comment]
@mwetter Implementation has been improved:
- [x] used `getline()` to avoid fixed array size
- [x] changed the function type from `void` to `int` and added return value
- [x] removed debug output
- [x] added `Example/GetTimeSpanTMY3_NonzeroStart.mo`, with the non-zero start time

**Comment by JayHuLBL** [comment]
@mwetter CI test was failed since the change causes slightly results difference, for classes in package`IBPSA.ThermalZones.ReducedOrder.Examples` and class `IBPSA.Fluid.Examples.SimpleHouse.mo`. 

I updated the reference results at commit 8d410d93903f447cbc1c3ac52d3178f4880ce7de.
