### ISSUE TITLE
change solver in Simplified2.mo

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1130]
For the JModelica verification, we simulate
```
simulateModel("IBPSA.Fluid.Examples.FlowSystem.Simplified2", tolerance=1e-6, stopTime=1000, numberOfIntervals=5000, method="CVode", resultFile="Simplified2");
```
While the model simulates with 500 intervals, it fails with 5000 intervals. This is to change to solver to `Dassl`. (`Radau` would also work).

**Comment by Mathadon** [comment]
@mwetter For the record, what type of error does JModelica generate?

**Comment by mwetter** [comment]
@Mathadon : The failed simulation is in Dymola. We simulate this model in Dymola but with more result points so that we can use these dense results for the JModelica verification.
