### ISSUE TITLE
Thermal Zone model test case 11 fails with error

### ISSUE THREAD

**Issue by marcusfuchs** [ibpsa/modelica-ibpsa#1132]
When I simulate `IBPSA.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase11`, I get the following error:

```
Error: The following error was detected at time: 5184000
  Inputs differ by more than threShold.
  Check output 'satisfied' for when violation(s) happened.
  Failed condition: assEqu.nFai == 0
```

The error seems a bit strange because `assEqu.satisfied` is shown as `true` in the results. Is anybody else experiencing this error? (I am using Dymola 2019 FD01 on a Windows 10 machine)

**Comment by mwetter** [comment]
@marcusfuchs : Does this stop the simulation, or is it only the solver probing for a solution?
Note that the mixing volume has been changed a few days ago which slightly affects the numerics in Dymola, see https://github.com/ibpsa/modelica-ibpsa/pull/1123. Would increasing the tolerance work for this model on Windows?

**Comment by marcusfuchs** [comment]
@mwetter If I understand the role of the assertion block (`IBPSA.ThermalZones.ReducedOrder.Validation.VDI6007.BaseClasses.VerifyDifferenceThreePeriods`) correctly, it never stops the simulation but only reports at the end of the simulation whether the threshold was crossed. Regarding the `assEqu.satisfied` output, I think I made an error earlier. When I run the model again, it actually shows me when the problem occurs by turning `false`:

![image](https://user-images.githubusercontent.com/5516900/56740899-1a7f6500-6772-11e9-9e7c-4d438625428c.png)

Changing the model tolerance seems to have no effect on this outcome.

**Comment by mwetter** [comment]
@marcusfuchs : On Linux this test works fine, see zoomed in area from running the .mos script.
![image](https://user-images.githubusercontent.com/1329080/56775887-11949080-677e-11e9-8509-4911e0c7f0e5.png)
The value `assEqu.threshold` was set by @mlauster if I remember correctly based on what VDI 6007 requires. He should know if this can be relaxed, or the model be improved so it better meets the test criteria.

**Comment by marcusfuchs** [comment]
@mwetter Thanks for verifying the results on Linux. It's already helpful to know that there is no fundamental problem with the test. And while it would be great if we could fix this for Windows, it's also a good reminder for us to think about switching our Workstations to Linux.

**Comment by mlauster** [comment]
Test case 11 is really a tough cookie. It seems that you violate the conditions at the first hour of the second test day. Since this test case actually requires non-physical conditions (same set temperature for cooling and heating with two different systems with differing thermal mass, what forces two controllers with differing parameters, but no space for counteracting), we skip the first minute or so of the first hour of each test day for the validation. I currently don't have any PC or Dymola installation, so I can't check, but you could extend this time period to two minutes, although I can't say what has to be done for this.

**Comment by marcusfuchs** [comment]
@mlauster Thanks! Impressive diagnosis without access to Dymola! This is indeed the problem. The test includes a timer to skip the first minute of the test day, defined as

```modelica
Modelica.Blocks.Logical.LessEqualThreshold thr(threshold=60)
    "Threshold to measure 60 seconds"
```

When I increase this limit to 


```modelica
Modelica.Blocks.Logical.LessEqualThreshold thr(threshold=120)
    "Threshold to measure 60 seconds"
```

the test works again. If we agree that this an acceptable fix to the problem, I can create a PR. 

Also thanks a lot for the details in your comment, the part 

> with differing thermal mass

helped me a lot towards finding the original problem I had been looking at when I simulated the test in the first place.

**Comment by mwetter** [comment]
@marcusfuchs : Can you please make a PR if the problem persists, or else close the issue.

**Comment by marcusfuchs** [comment]
@mwetter thanks for the reminder - I just realized my previous wording was not clear enough: When I wrote 

> If we agree that this an acceptable fix to the problem, I can create a PR.

I meant to say that I don't know the VDI guideline well enough to judge whether this is an acceptable change concerning the validity of the model or not. Therefore, I was waiting for feedback before creating the PR. Maybe @mlauster could help to decide whether we can proceed with this change. If so, I'll implement the change and create the PR.

**Comment by mlauster** [comment]
The VDI guideline specifies hourly values and a non-physical test case. As we already skip the first 60 seconds of the first hour of each test day, skipping 60 seconds more does not change our approach to do the best we can to fulfill these undoable requirements. So in my opinion, we could go for 120 seconds.

**Comment by mwetter** [comment]
Thanks @mlauster : @marcusfuchs , can you please make the PR if the problem persists.
