### ISSUE TITLE
remove models to ensure MSL 3.2.3 compatibility

### ISSUE THREAD

**Issue by JayHuLBL** [ibpsa/modelica-ibpsa#1135]
Learned from Dassault that MSL 3.2.3 will be shipped with next Dymola release (2020 Beta3). The upgrade from MSL 3.2.2 to 3.2.3 will cause following issue.

In MSL 3.2.3, class `Modelica.Media.Examples.Tests.Components.PartialTestModel` extends `Modelica.Icons.ObsoleteModel` (which is commented in MSL 3.2.2). When any model extends `Modelica.Media.Examples.Tests.Components.PartialTestModel`, running the model under pedantic mode will raise error like:
```
Component type specifier PortVolume specified an obsolete type: Obsolete model - use Modelica.Media.Examples.Utilities.PortVolume instead.
File: /opt/dymola-2020-x86_64/Modelica/Library/Modelica 3.2.3/Media/package.mo, line 4382
Component context: volume
Component declared as PortVolume volume in Modelica.Media.Examples.Tests.Components
```
The error will be avoided if the model extends `Modelica.Media.Examples.Utilities.PartialTestModel`. However, MSL 3.2.2 does not have package `Modelica.Media.Examples.Utilities`.

In IBPSA library, following models extends `Modelica.Media.Examples.Tests.Components.PartialTestModel` so they will not work properly with MSL 3.2.3:
```
IBPSA.Media.Specialized.Air.Examples.PerfectGasTestImplementation
IBPSA.Media.Specialized.Water.Examples.TemperatureDependentDensityTestImplementation
IBPSA.Media.Examples.AirTestImplementation
IBPSA.Media.Examples.PropyleneGlycolWaterTestImplementation
IBPSA.Media.Examples.WaterTestImplementation
```

I suggest to remove these models so to make sure the compatibility with both MSL 3.2.2 and 3.2.3.  Also, some of them are quite old (implemented in 2008).

**Comment by mwetter** [comment]
I am fine with removing them. What about the other library developers?

**Comment by Mathadon** [comment]
Ok to remove.
