### ISSUE TITLE
guard against low pressures

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1148]
I just had an issue where someone set an air pressure of 10 Pa, which caused negative absolute humidities to be computed, leading to funny computations elsewhere. The simulation however did not crash, stop or error. Should we somehow check/guard against these kind of errors to avoid wrong results to be generated? We could integrate an assert in some partials, perhaps in a mixing volume and/or medium implementation. However, this will generate overhead.. Any thoughts on this?

**Comment by mwetter** [comment]
How was such a low pressure achieved? Through a signal input, or through a parameter? I would think catching this at the source would be more efficient than in the volume, e.g., in the solution to an ODE.

**Comment by Mathadon** [comment]
Good point, through a parameter in this case. The `PartialSimpleMedium` does not define `p_min` or `p_max`. I guess we cannot add it since this would prohibit the use of media other than those from IBPSA? The better option then seems to add `p_min` and `p_max` for both water and air in the `Boundary` e.g. check based on the chemical formula of the Medium?

**Comment by mwetter** [comment]
What do you mean by the chemical formula? Is there anything in `PartialMedium` (other than a string comparison which would be expensive).

**Comment by Mathadon** [comment]
`Modelica.Media.Water.ConstantPropertyLiquidWater` contains
```Modelica
constant Modelica.Media.Interfaces.Types.Basic.FluidConstants[1]
    simpleWaterConstants(
    each chemicalFormula="H2O",
    each structureFormula="H2O",
    each casRegistryNumber="7732-18-5",
    each iupacName="oxidane",
    each molarMass=0.018015268);
```

However I did not realize that we cannot use this since it does not exist in `PartialMedium`. Can we use `mediumName` instead? I don't see why a string comparison would be problematic since the comparison should be performed only once?

**Comment by mwetter** [comment]
If the string is compared only once, then this would be fine. But I thought we call `checkBoundary` also from an `equation` section in some models.
