### ISSUE TITLE
avoid integer overflow in StopTime for borehole model

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1163]
This issue is to change:
```
IBPSA/Fluid/Geothermal/Borefields/Validation/ConstantHeatInjection_100Boreholes.mo
...
-  annotation (experiment(Tolerance=1e-6, StopTime=31536000000),
+  annotation (experiment(Tolerance=1e-6, StopTime=31536.0E+06),
```
as the first notation causes an integer overflow in the CI testing for JModelica. (The maximum value for an integer is 2147483647.)

**Comment by MassimoCimmino** [comment]
@mwetter I was not aware of this. Should the unit test page on the wiki be updated to specify that `StartTime` and `StopTime` be given as float regardless of their values (or if non-zero) to avoid errors in the future?

**Comment by mwetter** [comment]
@MassimoCimmino : I will update BuildingsPy to catch overflow if specified as an integer. This is more robust than trusting that users follow the coding guideline.
