### ISSUE TITLE
Refactor heat transfer coefficient alpha in aixlib models

### ISSUE THREAD

**Issue by katharinabr** [ibpsa/modelica-ibpsa#1168]
In some AixLib models the heat transfer coefficient `alpha` becomes `hConv` or `hRad` according to [https://github.com/RWTH-EBC/AixLib/wiki/Variable-Naming](url). This should also be done in `IBPSA.ThermalZones.ReducedOrder` to avoid problems at the next IBPSA/ AixLib merge.

**Comment by mwetter** [comment]
@katharinabr : Could you use `hCon` to stick with the 3 letter camel-case convention that we try to use (but admittedly don't use consistently)?

**Comment by katharinabr** [comment]
Ok, I'll use `hCon`. We just thought there might be some confusion because we already use `Con`, e.g. for condenser. But I think the context shows what is meant.

**Comment by mwetter** [comment]
The development branch is `issue1168_RefactorAlpha`
