### ISSUE TITLE
Refactor damper models

### ISSUE THREAD

**Issue by AntoineGautier** [ibpsa/modelica-ibpsa#1188]
This issue is to integrate into `modelica-ibpsa` the developments related to issue [#1298](https://github.com/lbl-srg/modelica-buildings/issues/1298) in `modelica-buildings`.
See the presentation at [Aachen](https://github.com/ibpsa/project1/blob/master/meetings/2019-04-03-expert-meeting-aachen/wp_1_1/ibpsa-project-1-lbl-actuators.html) and the [updated version](https://antoinegautier.github.io/plots/Actuators.html) describing the latest implementation.

**Comment by AntoineGautier** [comment]
(I include here some comments made in the PR.)

To clarify the motivation for renaming the parameters for nominal pressure drop:

**In the master branch:**

- `Exponential`: `dp_nominal` is the pressure drop between the 2 fluid ports. This is consistent with the super class `PartialTwoPort` which defines `dp = port_a.p - port_b.p`. This super class is inherited from by all damper models.

- `VAVBoxExponential`: `dp_nominal` is either the pressure drop of the fixed resistance only (if `not dp_nominalIncludesDamper`) or the total pressure drop between the 2 fluid ports (if `dp_nominalIncludesDamper`).
This class extends `PartialDamperExponential` which uses `dp_nominal` as the total pressure drop between the 2 fluid ports in the call to `homotopy(..., simplified=m_flow_nominal_pos*dp/dp_nominal_pos)`.

- `PressureIndependent`: `dp_nominal` is the pressure drop of the damper only (which is the exact opposite of `VAVBoxExponential` with `dp_nominalIncludesDamper=false`), `dpFixed_nominal` is the pressure drop of the fixed resistance.

**The modifications we discussed lead to:**
- `PartialDamperExponential`
  - New parameter `dpDamper_nominal` with default value 10 Pa.
  - New parameter `dpFixed_nominal` with default value 0 Pa.
  - `v_nominal` with default value 1 m/s changed into `final v_nominal = (2 / rho_default / k1 * dpDamper_nominal)^0.5`.
  - `dp_nominal` changed into `final dp_nominal = dpDamper_nominal + dpFixed_nominal`.
  - `kFixed` changed into `final kFixed = if dpFixed_nominal > Modelica.Constants.eps then
    m_flow_nominal / sqrt(dpFixed_nominal) else Modelica.Constants.inf `.

  Note that this will make `PartialDamperExponential` similar to `PartialTwoWayValve` which contains the declaration of `dpValve_nominal` and `dpFixed_nominal`.

  Remaining point: with those changes the model is not "partial" any more: `Exponential` will be identical.

- `Exponential`
  - No changes in the exposed parameters. The model in master uses protected parameters as intermediary steps to compute `dp_nominal`: those are no longer needed with the modifications made in `PartialDamperExponential`.

- `VAVBoxExponential` changed into `Exponential`

  - `dp_nominalIncludesDamper` is removed.

- `PressureIndependent`
  - Now extends directly `Exponential`.

  Remaining point: we could include the leakage coefficient declaration in `Exponential`.

- `MixingBox` 
  - To be modified in consistency with the refactoring of `PartialDamperExponential`.

@mwetter @Mathadon please review the proposed changes. Do you need additional elements before our next iteration on Thursday?

**Comment by mwetter** [comment]
@AntoineGautier : These changes look good to me.

**Comment by Mathadon** [comment]
@AntoineGautier thanks for the summary, looks good. I agree with no nominal for `dpDamper_nominal`.

**Comment by AntoineGautier** [comment]
- [ ] `PartialDamperExponential` can be retired if strictly identical to `Exponential`.
- [ ]  Adopt the leakage coefficient parameter for all damper models.
- [ ] Check the parameters description of `k0` and `k1`: those are loss coefficients, not flow coefficients.

**Comment by AntoineGautier** [comment]
Closed by #1267. 
The feature enhancement related to implementing an interpolation between a fully closed and a fully open characteristic shall be addressed in a separate issue.
