### ISSUE TITLE
Enhance ROM (ThermalZone.RC) for moisture balance

### ISSUE THREAD

**Issue by KremerMartin** [ibpsa/modelica-ibpsa#1209]
**What do I want to do?**
I want to implement the possibility to take into account moisture production and moisture balance in thermal zones. 
For this reason I would like to modify the air volume model in the `ThermalZones.ReduceOrder.RC.OneElement.mo`.

**How I want to solve it**

- I will implement a boolean parameter `use_moisture_balance` that will be _false_ per default.

- The `volAir` will be conditioned with this parameter. If it is _false_ the existing `volAir` will be used.

- A second air volume `volMoistAir` will be implemented (type: `Fluid.MixingVolumes.MixingVolumeMoistAir`) and conditioned by the same parameter (if _true_ use `volMoistAir`)

- An additional input connector `mWat_flow` and output connector `X_w` both conditioned with `use_moisture_balance` will be implemented and conditionally connected to the `volMoistAir`

In the Aixlib this implementation has been performed. To avoid Merge-Conflicts with the IBPSA, I would like to implement the same changes into the IBPSA. Changes can be seen in issue [695](https://github.com/RWTH-EBC/AixLib/issues/695) of the Aixlib.

Are there any concerns about this changes?

**Comment by KremerMartin** [comment]
@mwetter Could you assign me to this issue and give me rights to push a new branch where I can solve this issue, if you approve the change?

**Comment by mwetter** [comment]
@KremerMartin : I made the branch `issue1209_thermalZoneMoistAir` for this development.

**Comment by KremerMartin** [comment]
@mwetter Thanks a lot. Can you give me permission to push to this branch? Until now I have no access.

**Comment by mwetter** [comment]
@KremerMartin : you should still be able to make a pull request against the branch.

**Comment by KremerMartin** [comment]
This issue has been solved by PR #1213. The branch is now ready to be merged into the master.

**Comment by mwetter** [comment]
@KremerMartin : Thanks for the PR. I am working on reviewing and revising it.

**Comment by mwetter** [comment]
@KremerMartin : I revised the code and added the following:

- Corrected the implementation of the latent gain. The earlier version only added moisture to the volume, but this would have only changed the mass fraction in the volume and not the internal energy. Hence, it would have adiabatically cooled the air. 
- As part of the above point, I changed the input connector from `mWat_flow` to `QLat_flow`. This way, it uses the same units as other internal gains. See `IBPSA.ThermalZones.ReducedOrder.Validation.RoomWithLatentGain` for how to connect it to internal heat gains (in this case, I assumed the latent gains have the same value as the sensible convective gain).
 - Two validation tests, one with adding latent gains and one with adding zero latent gain. See `IBPSA.ThermalZones.ReducedOrder.Validation`
- I removed the output connector `X_w` as this can be obtained from the fluid connector, see the `IBPSA.ThermalZones.ReducedOrder.Validation.RoomWithLatentGain`.

There is one more change that need to be done: 
- [ ] `VDI6007.TestCase12` from which the new validations extend from, declares `VAir=0.1`. Can you please change `VAir` in the new validation cases `IBPSA.ThermalZones.ReducedOrder.Validation.RoomWithLatentGain` and `IBPSA.ThermalZones.ReducedOrder.Validation.RoomWithOutLatentGain` to the air volume specified in the VDI document, of which I don't have a copy.

Can you please address the point above, and make a new pull request so I can finalize.

**Comment by KremerMartin** [comment]
@mwetter I have a question regarding the latent heat of water vapour, you have implemented. You used 37 degree Celsius for the specificEnthalpy. Wouldn't this lead to mistakes for other moisture sources than human beeings? For example plants?
If someone provides the latent heat at a certain temperature (e.g. 20 degree Celsius), there will be a mistake in the amount of water added to the medium, since the latent heat will be divided through the specific enthalpy at 37 degree Celsius.
Maybe a hint in the model description will be useful, to ensure there will be no mistakes made by an user when implementing moisture gain sources.

**Comment by mwetter** [comment]
@KremerMartin : The error of adding the moisture at 20 degC vs 37 degC is around 2%, which we can assume to be smaller than the uncertainty of how large the latent gains are. I will however add a note so it is clearer to users. See commit #bd6dc774

**Comment by KremerMartin** [comment]
@mwetter Thanks a lot. I like the solution.
