### ISSUE TITLE
Movers do not properly read in pump curve from performance data

### ISSUE THREAD

**Issue by nnelsonwood** [ibpsa/modelica-ibpsa#1214]
Attempting to check or simulate the `PowerSimplified.mo` and `PowerExact.mo` models within Fluid.Movers.Validation leads to the following error messages respectively:

>[1] 15:23:03 Translation Error
>[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 2129:20-2129:78]: Internal >error NFCeval.evalBuiltinMax got invalid arguments (pump_Nrpm.per.pressure.V_flow)`

>[5] 15:26:40 Translation Error
>[IBPSA.Fluid.Movers.BaseClasses.Characteristics.flowParameters: 5:3-6:57]: Failed to deduce >dimension 1 of V_flow due to missing binding equation.

In both cases the problem seems to be that setting `per = per` within the pump models doesn't properly load the pump curve data into the models.

If I instead replace each variable individually (e.g. `per.pressure = per.pressure, per.power = per.power, per.use_powerCharcteristic = per.use_powerCharacteristic` ) then the model will succesfully and check and it will simulate. This, however, leads to a second problem. The claim is that in `PowerExact.mo` all three pump models will be identical after importing the pump curves, but I continue to get the same answer for the `FlowControlled_*` movers as is arrived at by the `PowerSimplified.mo` model (which are different than the `SpeedControlled_Nrpm` pump). The flow rate and dp are the same across all three pumps in both models as is expected.

I am experiencing these issues while running OpenModelica Nightly Build version 1.14.0
I looked for similar issues in the past and it seems like this is related to Issues #417 and #396.

**Comment by Mathadon** [comment]
I presume that this is a bug in OpenModelica?

**Comment by nnelsonwood** [comment]
You are probably right. I am rather new to modeling with Modelica and so didn't realize that most of the libraries are actually built for programs other than OpenModelica. I would not be surprised to hear that this is a bug with OpenModelica rather than your library.

**Comment by mwetter** [comment]
This looks like a bug in OpenModelica. We have similar models that exhibit a problem when propagating records. I will delete this issue as the OpenModelica development team is working on getting coverage for the IBPSA library.
