### ISSUE TITLE
Unbounded limiter in MSL 3.2.3 causes negative phi

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1221]
Since MSL 3.2.3 the model `Modelica.Blocks.Nonlinear.Limiter` has the parameter `homotopyType`, which sets a homotopy option. By default `linear` is used, which neglects the min/max bounds. When updating IDEAS to Dymola 2020 this caused the PI controller output bounds to be ignored at initialization, leading to a PI outlet control signal of -10, which then fed into a valve and caused the resulting algebraic loop not to converge due to the negative control signal. I propose to disable homotopy by default in `IBPSA.Controls.Continuous.LimPID` to avoid this.

**Comment by Mathadon** [comment]
@damienpicard this can explain convergence problems in your model too

**Comment by mwetter** [comment]
Disabling homotopy makes sense in this situation.

**Comment by Mathadon** [comment]
many models seem to be bugging out though.. I'll look into it.

**Comment by Mathadon** [comment]
@mwetter does IBPSA already use Dymola2020 for the regression tests? It seems to have a newer version of MSL 3.2.3. The old version does not yet have this parameter and may be causing the models to fail for that reason.

**Comment by mwetter** [comment]
@Mathadon : IBPSA is using Dymola 2020 for the regression tests.
