### ISSUE TITLE
bound inputs of valves

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1223]
linked to #1221 : shouldn't we bound the inputs of valves to avoid non-physical situations? We have an assert now but it's set at `-0.2`, which is still quite large. I think it would be a better solution to guard the inputs using a `phi=max(l, ...)` expression?

**Comment by mwetter** [comment]
The rational of the previous implementation was to avoid a non-differentiability at the boundary of the feasible domain. Not sure what the `max(1, ...)` would cause if the solution to the upstream PI controller would be such that the input is 1.

**Comment by Mathadon** [comment]
Ok, that's an argument, but a few thoughts:
- Differentiability only matters when solving an algebraic loop, right? I.e. we need differentiability for  avoiding that the Newton solver does not converge. The control signal should however not end up in an algebraic loop if the filter is used (default) since then the input is prescribed by a state value, meaning that the differentiability does not matter. Perhaps similar arguments can be made for the time integrator though, where we would need the differentiability.. 
- I prefer a non-differentiability over a non-physical model where the valve acts as a pump.
- We could use a `smoothMax` instead of `max`?

**Comment by mwetter** [comment]
Try using a limiter at the valve input, and run benchmarks to see how computing time changes.
Don't use `smoothMax` because of overshoots of this function.

**Comment by Mathadon** [comment]
The model `IBPSA.Fluid.Examples.FlowSystem.Basic` has the same computation time after the change. This is the most complex fluid system using valves that we have in the library.
