### ISSUE TITLE
ThreeWayTable Valve

### ISSUE THREAD

**Issue by alexanderAKU** [ibpsa/modelica-ibpsa#1227]
The library contains a two way valve that has a table based flow characteristic (TwoWayTable). However, a three way valve with table-based characteristics does not exist. I tried to model a three way table-based valve in the same way as the model ThreeWayLinear or ThreeWayEqualPercentageLinear: I tried to redeclare the partial two way valve (res1 and res3) and use the TwoWayTable. However, this approach does not work because the parameter l in the partial valve (res1 and res3) is final as well as the parameter l in the model TwoWayTable.

I think it would be a good approach to release the "final" modifier in the PartialThreeWayValve because this model is a base class. The final modifier could be added in the child classes if needed.
Are there any suggestions how to solve this issue?

Best regards

**Comment by Mathadon** [comment]
It's not clear to me why you have to modify the parameter `l`, can you elaborate on that?

**Comment by alexanderAKU** [comment]
The replaceable valves `res1` and `res3` in the model `PartialThreeWayValve` include the final parameter `l`. The parameter `l` of in the model `TwoWayTable` is final too. Thus, `res1` and `res3` can not be replaced by the model `TwoWayTable` because the parameter `l` would have two different final values.

**Comment by mwetter** [comment]
@alexanderAKU : Would the commit 0e647cf address what you need?
@Mathadon : This would be backward compatible, and not impact the dialog window of Dymola.

**Comment by Mathadon** [comment]
Ok I get it, the problem is that the `PartialThreeWayValve` wants to assign a value of `l` that conflicts with the definition of `TwoWayTable`.

**Comment by alexanderAKU** [comment]
@mwetter the commit solves my problem. Thanks.
