### ISSUE TITLE
enable IBPSA.Airflow.Multizone.Examples.OneOpenDoor for JModelica with CVODE

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1234]
The model `IBPSA.Airflow.Multizone.Examples.OneOpenDoor` works with JModelica with CVode with these settings:
```
                           compiler_options = {"generate_html_diagnostics" : False,
                                               "nle_solver_tol_factor": 1e-2})
```
which are now the default in BuildingsPy. It can therefore be removed from `conf.json`.

**Comment by Mathadon** [comment]
@mwetter that looked like quite a high tolerance but if I understand correctly from the code in `RuntimeLibrary/src/fmi2/fmi2_me.c` and `RuntimeLibrary/src/jmi/jmi_me.c` then this factor is used as a multiplication factor on top of the tolerance that is provided by the user. However, depending on the variable scaling (nominal values) it may still cause algebraic loops to converge until too inaccurate results. Did you try to add a `nominal` attribute for algebraic loop iteration variables such that the models converge even with high precision tolerance?

**Comment by mwetter** [comment]
@Mathadon : yes, we tried various things and worked with Modelon who recommended this setting for our models.
