### ISSUE TITLE
Parameter keyword missing in `AixLib.Media.Antifreeze.BaseClasses.PropertyCoefficients`

### ISSUE THREAD

**Issue by PMehrfeld** [ibpsa/modelica-ibpsa#1239]
Is there any reasons that `nX_a` ([here](https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Media/Antifreeze/BaseClasses/PropertyCoefficients.mo#L8)) and two lines later `nTot` does not have the `parameter` keyword in the beginning of the line?

I receive the following error when checking the model `IBPSA.Media.Antifreeze.BaseClasses.PropertyCoefficients` with Dymola 2020:
> Subscript nX_a in declaration of variable nT is neither a parameter nor constant expression.

Otherwise I would recommend to insert the `parameter` keyword in both lines.

**Comment by mwetter** [comment]
I believe all these declarations should be parameters with `annotation(Evaluate=true)`, including `X_a_ref` etc.

**Comment by PMehrfeld** [comment]
Normally, records are used as `constant` or `parameter` and, thus, all variables inside become a `constant` or a `parameter`. But when checking the pure class `IBPSA.Media.Antifreeze.BaseClasses.PropertyCoefficients` the check fails with the error message above.
I think correct Modelica would be to explicitly define these two Integers as parameters, although it is a record.

**Comment by mwetter** [comment]
Yes, please declare the two as parameters. If this does not suffice, we can add the others such as `X_a_ref` also as parameters.
