### ISSUE TITLE
division by zero in IBPSA.Fluid.Actuators.Dampers.MixingBox

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1243]
The model `IBPSA.Fluid.Actuators.Dampers.MixingBox` generates a division by zero when `dpOut_nominal = dpRec_nominal = dpExh_nominal = 0`, which makes sense since the model can't redirect the flows as intended if it can't generate pressure drops. The error message is however quite obscure. Should we add an assert that checks for `dp*_nominal > 0`?

**Comment by mwetter** [comment]
@Mathadon : If there is a combination of parameters for which the model is not well defined, we should trigger an assertion to guide a non-experienced user in a better direction that a division by zero would.
