### ISSUE TITLE
IncludeThreeWayTable Valve

### ISSUE THREAD

**Issue by alexanderAKU** [ibpsa/modelica-ibpsa#1254]
This issue is the extension of issue #1227:

Currently, the library contains a table based two way valve. However, a table based three way valve is not included yet.

The model new model `ThreeWayTable` will extend from the `PartialThreeWayValve` and replace the partial models `res1` and `res3` by the model `TwoWayTable`

**Comment by alexanderAKU** [comment]
@mwetter could you create a branch with the name `issue1254_includeThreeWayTableValve` so that I can push my changes to the repository?

**Comment by mwetter** [comment]
@alexanderAKU : I created the branch https://github.com/ibpsa/modelica-ibpsa/tree/issue1254_includeThreeWayTableValve
