### ISSUE TITLE
_dp_start in AixLib.Fluid.Interfaces.PartialTwoPortInterface leads to FMI error

### ISSUE THREAD

**Issue by PMehrfeld** [ibpsa/modelica-ibpsa#1265]
## Problem
I edited the example `IBPSA.Fluid.FixedResistances.Examples.PressureDrop` in the following way:
1. Duplicate `res` and place the new component in series with the other pressure drop model
1. Change both `dp_nominal`s to 5 Pa

![image](https://user-images.githubusercontent.com/11769433/71242331-047c7100-230e-11ea-8c23-763096c72800.png)

Then I export it as an FMU and import it again with the following script:
```
wd = Modelica.Utilities.System.getWorkDirectory();

solverFmiType = "me"  // fmiType  := "all" "FMI type, me (model exchange), cs (co-simulation), all or csSolver (using Dymola solver). all probably means cvode.

fmuName = translateModelFMU("IBPSA.Fluid.FixedResistances.Examples.PressureDrop", false, "", "2", solverFmiType, false, 0);

importFMU(Modelica.Utilities.Files.loadResource(wd + "/" + fmuName + ".fmu"), 
  true, 
  true, 
  false, 
  "IBPSA.Fluid.FixedResistances.Examples");
```

In a last step I simulate this FMU in a new blank model and I receive the following error:
```
Local "_dp_start" conflict with inherited. Should be identical
But attempting to increase variability of component _dp_start.
For element _dp_start found at
Modelica Text: line 106
Conflict with element from
Modelica Text: line 103
Component context: iBPSA_Fluid_FixedResistances_Examples_PressureDrop_fmu.res
Component declared as res_rec res in IBPSA.Fluid.FixedResistances.Examples.IBPSA_Fluid_FixedResistances_Examples_PressureDrop_fmu
Modelica Text: line 130
```

## Solution

In the model `AixLib.Fluid.Interfaces.PartialTwoPortInterface`,I rename the parameter `_dp_start` to `dp_start` and also change this parameter name in the modifiere-brakets of the variable `dp`, the error goes away.

## Questions

1. Is there any reason for this behavior?
1. Can we solve it be refactoring the parameter name (to stay consistent we should do this for `_m_flow_start` as well)?

**Comment by mwetter** [comment]
@PMehrfeld :

This behavior is not expected: The variable _dp_start is, in the original model, only declared and used once:
```
  parameter Modelica.SIunits.PressureDifference res._dp_start(displayUnit = "Pa")
     = 0 "Start value for dp, used to avoid a warning if not set in dp, and to avoid dp.start in parameter window";
  Modelica.SIunits.PressureDifference res.dp(start = res._dp_start, nominal = 
    10.0, displayUnit = "Pa") = res.port_a.p-res.port_b.p "Pressure difference between port_a and port_b";
```
I see no problem with this code. When I make two instances and set `dp_nominal=5` (to reproduce your model), I can simulate it in Dymola and JModelica. Note that JModelica is first generating an FMU and then simulates it, somewhat similar to your import into Dymola.

Renaming the parameter should not change the model behavior, so this is unexpected. The reason I called the parameter `_dp_start` with leading underscore is to indicate that this is of no interest to the user. In hindsight, it could have been declared as a `constant`.

This behavior looks like a bug in Dymola.

**Comment by PMehrfeld** [comment]
@mwetter: Thanks for your effort and helpful answer.  
We looked a bit deeper into the issue and recognized that the error occurs only with the non-default setting `Advanced.FMI.xmlIgnoreProtected = false`. If it is set to `true` and compile the model to a FMU, the FMU simulates as expected after reimport.
