### ISSUE TITLE
Resistance in PartialThreeWayValve uses PartialTwoPortInterface instead of PartialTwoPortTransport

### ISSUE THREAD

**Issue by damienpicard** [ibpsa/modelica-ibpsa#1266]
Resistances in `PartialThreeWayValve` uses `PartialTwoPortInterface` instead of `PartialTwoPortTransport ` for resistances. This prevent us to redeclare the resistance as an IdealSource as this extends from  `PartialTwoPortTransport `.

In IDEAS we have a simplified model for a 3-way valve (`IDEAS.Fluid.Actuators.Valves.Simplified.ThreeWayValveMotor`) and we would like to upgrade it to use the base class `PartialThreeWayValve`. It is however not possible with the current implementation.

**Comment by mwetter** [comment]
@damienpicard : Does it really make sense to reuse `PartialThreeWayValve` for `IDEAS.Fluid.Actuators.Valves.Simplified.ThreeWayValveMotor`? They have very different parameters as the valves in IBPSA are based on `PartialResistance` but `ThreeWayValveMotor` has no resistances.

**Comment by mwetter** [comment]
I will close this due to inactivity.
