### ISSUE TITLE
Fluid.FixedResistances.Examples.PlugFlowPipe error

### ISSUE THREAD

**Issue by paulps2** [ibpsa/modelica-ibpsa#1272]
I'm quite new to Modelica and I'm trying to understand some basic examples. I'm looking at the example IBPSA.Fluid.FixedResistances.Examples.PlugFlowPipe and checking this model gives me the following error

```[1] 11:48:12 Scripting Notification
Number of classes to check: 2 
Checking: model IBPSA.Fluid.FixedResistances.Examples.PlugFlowPipe... 0.2350000000001273 seconds -> FAILED! 
         
Error String: 
 
Error Buffer: 
Warning: Requested package Modelica of version 3.2.2, but this package was already loaded with version 3.2.3. You might experience problems if these versions are incompatible. 
[C:/Program Files/OpenModelica1.14.0-64bit/lib/omlibrary/IBPSA 3.0.0/Fluid/FixedResistances/BaseClasses/PlugFlowTransportDelay.mo:49:3-55:44:writable] Error: Function argument initialValues={time + pip.cor.timDel.t_in_start, time + pip.cor.timDel.t_out_start} in call to spatialDistribution has variability continuous which is not a parameter expression. 
 
#[-], 0.2350000000001273, IBPSA.Fluid.FixedResistances.Examples.PlugFlowPipe 
------------------------------------------------------------------------- 
Checking skipped: package IBPSA.Fluid.FixedResistances.Examples.PlugFlowPipe.Medium...  


[2] 11:48:12 Scripting Notification
Number of classes checked / failed: 2/1
```

It seems that the module pip.cor.timDel uses the function `spatialDistribution`. My guess is that there is something wrong with `pip.cor.timDel.t_in_start` or `pip.cor.timDel.t_out_start`? It would be greatly appreciated if someone could help me with this.

P.S. I'm using OMEdit v1.14.0 on windows 10 with Modelica library v3.2.3

**Comment by mwetter** [comment]
I checked the code and `t_in_start` and `t_out_start` are parameters. With the nightly build of OpenModelica, I get the error
```
IBPSA.Fluid.FixedResistances.Examples.PlugFlowPipe.o: In function `IBPSA_Fluid_FixedResistances_Examples_PlugFlowPipe_eqFunction_430':
IBPSA.Fluid.FixedResistances.Examples.PlugFlowPipe.c:(.text+0x22cb): undefined reference to `spatialDistribution'
```
which looks like OpenModelica does not yet support the `spatialDistribution` operator. As the OpenModelica team is working on getting full coverage of the IBPSA library, I will close this issue.

**Comment by thorade** [comment]
https://trac.openmodelica.org/OpenModelica/ticket/5765
