### ISSUE TITLE
convertTime does not check start time

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1281]
The block `ConverTime` (https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/BoundaryConditions/WeatherData/BaseClasses/ConvertTime.mo) does not check the start time, which means the start time can be before the input file starts. This should be caught by an assert too?

**Comment by mwetter** [comment]
@Mathadon 
can you please provide a case where the model does not compute correctly. The simulation
```
simulateModel("IBPSA.BoundaryConditions.WeatherData.BaseClasses.Examples.ConvertTime", startTime=-12960000, stopTime=77760000, method="Cvode", tolerance=1e-06, resultFile="ConvertTime");
```
looks good to me
![image](https://user-images.githubusercontent.com/1329080/73230553-85f7c800-4132-11ea-9969-6c3d6cce4190.png)

**Comment by Mathadon** [comment]
@mwetter It's not about whether or not the time is correctly computed. The assert

```
  assert(canRepeatWeatherFile or (time - weaDatEndTim) < shiftSolarRad,
    "In " + getInstanceName() + ": Insufficient weather data provided for the desired simulation period.
    Based on the provided weather file the following start time " + String(weaDatStaTim) +
    " and end time " + String(weaDatEndTim) + " (last time stamp + average increment) for the weather data were determined",
    AssertionLevel.error);
```
does not allow extrapolating beyond the range of the weather data file. For consistency reasons it would not make sense to allow extrapolating _before_ the start of the weather data file?

**Comment by mwetter** [comment]
So you want to catch the situation where `canRepeatWeatherFile = false` (e.g., the weather file is not for a full year) and the simulation starts before the start of the weather data file?
I think such an assertion would be fine to guard against this eventuality. Can you please make a PR?

**Comment by Mathadon** [comment]
yes
