### ISSUE TITLE
revise valves and pump icons to indicate how they are controlled

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1294]
This issue is to implement different graphics to indicate if valves are open/closed and what speed the pumps are operating at. This addresses https://github.com/ibpsa/project1/wiki/2020-01-20-library-development#new-action-items

**Comment by mwetter** [comment]
The development branch is `issue1294_dynamicIcons`.

I also tried to place another triangle over the input connector, but this won't be visible because the input connector is always on the top of the graphical elements.

**Comment by mwetter** [comment]
Updates have been made to various icons (mixing volumes, sensors, delays, valves, pumps, pressure drop, etc.), see below.

![image](https://user-images.githubusercontent.com/1329080/75598624-f6577900-5a51-11ea-82be-4d6c45475a3c.png)

I tried to display the most important quantities without overloading the graphics. The changes are only visible during/after the simulation, but not when building a model. In Dymola, move the slider under "Animation control" or slide the "Measurement cursor" in a plot to see the current values.

- Valves show which port is open (white) or closed (black)
- Pressure drops show with a black bar how big the flow is relative to `m_flow_nominal`. If the flow is negative, the bar is red.
- Junctions also show how big the inflowing mass flow rate is (black) and how big the outflowing mass flow rate is (red). 
-  Volumes and pressure sources show the temperature and change the color based on their temperature, although scaling was not that straightforward because of the large range in temperatures that we typically have.
- Sensors show the measured quantity, and different number formatting is used depending on the expected range of the number.
- The weather data reader displays the outside drybulb temperature.

More can be added in a next phase by copying the current annotations (so that uniform font sizes are used).

**Comment by Mathadon** [comment]
looks fancy!

**Comment by mwetter** [comment]
Michael to verify that `y` and not `y_actual` is consistently used, then make a pull request.
