### ISSUE TITLE
implement BESTEST verification for weather data

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1314]
This issue is to implement a fully scripted verification of the weather data processing for BESTEST.

**Comment by mwetter** [comment]
@EttoreZ : Can you please address these items after updating your local branch.

Todo:
- [ ] The directory Resources/Data/BoundaryConditions/Validation/BESTEST has various weather files that seem not be used. Delete if not needed.
- [ ] If we can make the json output more compact, we could store them on git. I tried to already write them more compact, but the number format could be changed using `'f'{value:.4g}'` to see if this keeps the json files under about 10 MB. In this case we could integrate them into the CI testing to make sure results are current.

**Comment by EttoreZ** [comment]
I erased the duplicate weather files.
I changed the number formatting to 4  significant digits and now the .json files are around 1.8MB each.

**Comment by mwetter** [comment]
@EttoreZ : I don't quite understand why some weather files are still here. For example, this file is still present:
```
$ find . -name '421810.epw'
./Resources/Data/BoundaryConditions/Validation/BESTEST/421810.epw
```
But it is nowhere used other than mentioned in a comment:
```
$ find . -name '*.mo' | xargs grep 421810
./BoundaryConditions/BESTEST/Validation/WD500.mo:<p>Weather data file : 421810.epw</p>
./BoundaryConditions/BESTEST/Validation/WD500.mo:<p><i>Table 1: Site Data for Weather file 421810epw</i></p>
./BoundaryConditions/BESTEST/Validation/WD500.mo:<table summary=\"Site Data for Weather file 421810epw\" cellspacing=\"2\" cellpadding=\"0\" border=\"1\"><tr>
```
Can such files be removed or is this a bug?

**Comment by EttoreZ** [comment]
@mwetter I intentionally left those there because those .epw files are the ones given by Tim, than converted into the .mos format using the java converter. I thought to leave them there to have the whole processing chain available. Do you think it's better to remove them? If it's to make the library lighter, it might be better to keep the .epw and convert them into .mos just for the tests and then erase those.

All the best,
Ettore

**Comment by mwetter** [comment]
@EttoreZ I don't see where for example `421810.mos` or `421810.epw` are used. Neither of which appears in the `.mo` files or the `.py` script, although `WD500.mo` mentions it in its documentation.
If they are used then it is fine to leave them (because they seldom change and are needed to run the examples) but if they are nowhere used, then please delete them and update the `info` section as the example `WD500.mo` is not using `421810.epw`.

**Comment by mwetter** [comment]
I will delete the `results` folder from git and update the `.py` script. The reason is that these files are 7 MB large, and likely often change when Dymola is updated or the weather data reader is revised. In comparison, all 500 reference results of the IBPSA library take 5 MB.

**Comment by EttoreZ** [comment]
@mwetter  I see the problem now, it's a bug as reported in the documentation each WDxxx test should run with a different weather file. In a local copy of my library there were these two additional lines in the model definition of each WDxxx:
weaDatHHorIR(filNam=Modelica.Utilities.Files.loadResource("modelica://IBPSA/Resources/Data/BoundaryConditions/Validation/BESTEST/XXXXX.mos")),
weaDatTDryBulTDewPoinOpa(filNam=Modelica.Utilities.Files.loadResource("modelica://IBPSA/Resources/Data/BoundaryConditions/Validation/BESTEST/XXXXX.mos")));
That for some reason I did not push to my branch.
loading the correct weather file for each model case. I can add them and make a new pull request?
For the json files, another way could be to compress the .json files? ( I found the package compress_json) it makes the files around 200kb each, the process converts them into binary files though.

**Comment by mwetter** [comment]
@EttoreZ The .mos scripts that plot the results plot around 8 to 10 quantities on the same plot, and these quantities have ranges from 0 to 1 and from 8E4 to 9E4. This makes them unreadable on the plot. Can you please group them based on their quantities in separate sub plots, or remove them if you don't want all being tested as part of the CI testing?

For now, let's not commit the json files as they can always be regenerated, and the CI testing will catch changes in results. If we later want to add them, we can use https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.write as this does not create an additional dependency.

**Comment by mwetter** [comment]
@EttoreZ : Please make the changes with the correct weather files, and then make a PR. Also note that the BESTEST results likely changed now slightly because I already merged https://github.com/ibpsa/modelica-ibpsa/pull/1344 into `issue1314_BESTEST_weather`.
