### ISSUE TITLE
Boundary Conditions images for azimuth angle calculation

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/modelica-ibpsa#1322]
The images reported in the User's guide of the boundary conditions show a discrepancy with the acutal calculation of the Azimuth Angle. In IBPSA.BoundaryConditions.UserGuide is shown that the Azimuth angle is positive going from South to East , while in the types for N,E,S,W the angle is positive in the opposite direction towards West, which is consistent with the rest of the calculations in the library. 
Below I attach the updated images in .ods and .png formats

All the best,
Ettore Zanetti
![zen_sun](https://user-images.githubusercontent.com/46685675/76787795-02fe0000-67ba-11ea-8fbe-d9336cf9e888.png)
![zen_pla](https://user-images.githubusercontent.com/46685675/76787802-03969680-67ba-11ea-969e-ca4dfdb732e2.png)

[BoundaryImagesODS.zip](https://github.com/ibpsa/modelica-ibpsa/files/4339710/BoundaryImagesODS.zip)

**Comment by Mathadon** [comment]
@EttoreZ I'm not entirely sure whether I agree. `IBPSA.Types.Azimuth` has 

```modelica
   constant Modelica.SIunits.Angle E = -Modelica.Constants.pi/2
  "Azimuth for an exterior wall whose outer surface faces east";
   constant Modelica.SIunits.Angle N = Modelica.Constants.pi
  "Azimuth for an exterior wall whose outer surface faces north";
   constant Modelica.SIunits.Angle S = 0
  "Azimuth for an exterior wall whose outer surface faces south";
   constant Modelica.SIunits.Angle W = +Modelica.Constants.pi/2
  "Azimuth for an exterior wall whose outer surface faces west";
```

where, as you say, the azimuth angle increases from S to W, N, E.

The first figure that you included, has an arrow for Φ_s starting from S (which is consistent with 0 azimuth for south), and increases towards the west direction, which is also consistent with the code above. Can you further explain where the inconsistency is at?

**Comment by EttoreZ** [comment]
Yes sorry for the misunderstanding, just to be clear these are the old images:

![zen_pla](https://user-images.githubusercontent.com/46685675/76790052-60944b80-67be-11ea-9d2f-c6cf6ab2b0fe.png)
![zen_sun](https://user-images.githubusercontent.com/46685675/76790057-6427d280-67be-11ea-9488-39721ca3f0a4.png)

**Comment by mwetter** [comment]
@EttoreZ Thanks for updating the figures. Can you please correct the grey rectangle. In the original drawing, this was to indicate the horizontal plane so that theta_p can be visualized.

This is not clear in the original figure.

**Comment by EttoreZ** [comment]
My bad, I think the conversion from .ppt to .ods changed the position of the image a bit, attached are the new .ods and png, they should be fine now.

![zen_sun](https://user-images.githubusercontent.com/46685675/76805863-44a1a180-67e0-11ea-864d-74432d7e5b5f.png)
![zen_pla](https://user-images.githubusercontent.com/46685675/76805865-453a3800-67e0-11ea-83d6-7fbcea08a2b1.png)
[BouCondImaODS.zip](https://github.com/ibpsa/modelica-ibpsa/files/4340701/BouCondImaODS.zip)

**Comment by mwetter** [comment]
@EttoreZ : Thanks for the update image. Can you please make a pull request against the branch `issue1322_boundaryConditions_image`.
