### ISSUE TITLE
Including NW, SW, etc... types into the available direction types

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/modelica-ibpsa#1323]
For convenience besides the cardinal coordinates N,E,S,W also the directions of 45° NE,SE,SW,NW will be added to the available coordinates. This will allows to have more robust models in case the convention for the azimuth angle will change according https://github.com/ibpsa/modelica-ibpsa/issues/785

**Comment by mwetter** [comment]
@EttoreZ : Can you please make a pull request to the branch `issue1323_type_coordination`.
