### ISSUE TITLE
add simplified door model

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1353]
The current door models `Airflow.DoorDiscretized*` are based on an orifice equation model in which the pressure difference drives the flow rate. If used with an HVAC system that models flow friction in the return duct, then each pressure (or mass) in the room is a state that varies very quickly due to very small difference in pressure of the rooms that are connected. This causes very fast transient of the pressure (or mass), driven by small differential pressures, and the equations are coupled to slow dynamics of temperature, and hence stiff. This causes problems for example in
https://github.com/lbl-srg/modelica-buildings/issues/1911#issuecomment-620193181.
It may also be the reason for https://github.com/lbl-srg/modelica-buildings/issues/1895.

This issue is to implement a simplified door model that still allows for bi-directional, temperature difference-driven flow between zone, but it will set the pressure of each zone to be equal. Then, a translator will do index reduction and only use one state for all room pressures (or mass).

**Comment by mwetter** [comment]
The model has been tested with the Buildings library, commit 10049c0fcc169f4f9141bb191c9fb5b4ba4331cb

The computing time is for three models in `Buildings.ThermalZones.EnergyPlus.Examples.SmallOffice`:

Model | new | old | speed up %
---------|-------|------|-----------------
`Guideline36Spring` | 13.1 | 15.8 | 17
`ASHRAE2006Spring` | 3.3 | 3.7 | 11
`NoHVAC` | 0.42 | 0.36 | 14

The first two models differ by their control, with Guideline 36 having a more detailed control sequence. The last model uses the same building model but no HVAC system.

**Comment by Mathadon** [comment]
Sounds like a substantial difference considering that the rest of the model takes a lot of time to compute. You compared statistics by any chance?

**Comment by mwetter** [comment]
I didn't drill in further but the number of equations seems similar:
https://github.com/ibpsa/modelica-ibpsa/pull/1442/files#diff-599036ec03873c72f9ed50d7d64909834c32ff074aed01bbd3b5b6beedad419cL5

There are two states removed because I did not add the error control on the mass that is exchanged. I expect these states not to be needed once https://github.com/ibpsa/modelica-ibpsa/issues/1412 is fixed (which I am working on).

**Comment by Mathadon** [comment]
Above:

> This issue is to implement a simplified door model that still allows for bi-directional, temperature difference-driven flow between zone, but it will set the pressure of each zone to be equal.

This does not seem to be the case from the code so I guess that post is simply outdated?

**Comment by mwetter** [comment]
The pressure is assumed to be identical for computing the buoyancy-driven part, which is implemented in
https://github.com/ibpsa/modelica-ibpsa/pull/1442/files#diff-8dfe7b312e3f9c5f3fd5594623b192be9913bcdee7da6c35dee76c7701d156a4R53

This is then superposed to the static-pressure-difference driven part. This superposition is the main modeling simplification.
