### ISSUE TITLE
order of elements in .mo versus package.order

### ISSUE THREAD

**Issue by thorade** [ibpsa/modelica-ibpsa#1364]
Types added in #1323 need to be in same order in package.order file as in .mo file, for OpenModelica

![image](https://user-images.githubusercontent.com/314571/82867881-ebff2b00-9f2b-11ea-8b48-87a159ba1a3f.png)

**Comment by thorade** [comment]
BuildingsPy will sort it alphabetically in the package.order file, so I suggest to manally change the order in the .mo file once. If that is OK, I will submit a PR.

**Comment by Mathadon** [comment]
Same issue here https://github.com/open-ideas/IDEAS/issues/1138 
I thought that I messed up the merge but apparently not.

**Comment by mwetter** [comment]
@thorade Try updating the IBPSA library and BuildingsPy (if you regenerate the `package.order`). This should have been addressed in https://github.com/lbl-srg/BuildingsPy/issues/341

**Comment by thorade** [comment]
I used an old BuildingsPy, because when installing the latest master I got another error (str/bytes). 
But then it seems the sorting part is a solved issue, so this issue can be closed.
