### ISSUE TITLE
non-unity nominal valve openings 

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1379]
Building management systems often express the valve opening as a percentage [0, 100], rather than a fraction [0, 1]. Mapping a BMS into control logic therefore requires scaling the output of the PI and other control logic. This process is prone to error and it could be easier to simply allow the Modelica models to use a % control signal as an input. To be more generic, it would make sense to allow the user to define `y_nominal`, which equals 1 by default, and which indicates for what valve opening `m_flow_nominal` and `dp_nominal` are valid. Internally, we could simply scale the computation of `phi` by this new variable to obtain the same result as before.

I can propose an implementation if we agree that this would be a useful feature.

**Comment by mwetter** [comment]
I feel strongly about sticking to `[0, 1]`. If we allow for percentage, then we may soon be asked to allow Celsius (or Fahrenheit!) for temperatures, and psi for pressure etc, opening up to a mess of different units. My position is that the model or the FMI has a consistent set of units, which is declared in its API (in terms of FMI, the `modelDescription.xml` file), which keeps it clear and avoids mistakes. Tool that integrate it provide unit conversion using the units declared in the API when coupling to these models, asking for user input or plotting results.

**Comment by Mathadon** [comment]
fair enough :)
