### ISSUE TITLE
Refactored Steam Medium 

### ISSUE THREAD

**Issue by khinkelman** [ibpsa/modelica-ibpsa#1389]
Hi @mwetter, I have refactored the `Steam` medium and it is ready for review. The changes are on my forked branch [issue1206_media_steam](https://github.com/khinkelman/modelica-ibpsa/tree/issue1206_media_steam). If you could please create a branch for this update, I (or you) can create a PR. Please let me know what you need from me.

As a high-level summary, here are the new models developed on this branch:
- `IBPSA.Media.Steam` -- New refactored steam medium model for water in the vapor-phase (IF97 region 2) only
- Example models for `IBPSA.Media.Steam`
- `IBPSA.Media.WaterHighTemperature` -- Extends `Media.Water` with a higher T_max and a function to calculate saturation temperature with respect to pressure. This water model can be used directly in high-pressure situations. 
- `IBPSA.Media.Interfaces.PartialPureSubstanceWithSat` -- Partial medium model to allow non-instantiated models to implement saturation state functions. 

Thanks!

**Comment by mwetter** [comment]
@khinkelman : I just created the branch https://github.com/ibpsa/modelica-ibpsa/tree/issue1389_mediaSteam
Can you please make a PR against that branch.
Thanks.
