### ISSUE TITLE
sign change in CpLowRise

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1392]
See in `IBPSA.Airflow.Multizone.BaseClasses.windPressureLowRise`:

```Modelica
algorithm 
  // Restrict incAng to [0...pi]

  // Change sign to positive
  aR := if incAng < 0 then -incAng else incAng;
```

this does not make sense to me since the angle direction changes. This should be modified?

**Comment by mwetter** [comment]
Yes, this looks like a bug.

**Comment by Mathadon** [comment]
Ok, will propose a fix.

**Comment by mwetter** [comment]
@Mathadon : Looking at this a bit more in detail, I think the model is fine due to symmetry, see also the graphic in the info section. Do you have a counter example and maybe a bugfix? If not, can this be closed?

**Comment by Mathadon** [comment]
@mwetter you mean that the wind profile itself is symmetric around 0? If that is indeed the case, there seems to be no problem in practice and we can close this issue. But it's a bit bad practice to put such illogical equations in the code. E.g. @kldjonge copied the code and used it for a non-symmetric profile where it would have caused problems.

**Comment by mwetter** [comment]
This can be closed as the model is for rectangular buildings for which the formulation is correct.
