### ISSUE TITLE
inconsistent use of parameter in functions in IBPSA/Media/Refrigerants/R410A

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1414]
The functions in `IBPSA/Media/Refrigerants/R410A` use constructs such as
```modelica
  Real A[:] = {-1.721781e2, 2.381558e-1, -4.329207e-4, -6.241072e-7}
    "Coefficients A for Martin-Hou equation of state";
...
  parameter Integer n = size(A, 1);
```
This leads to a compilation error in OpenModelica. Here, the `parameter` keyword can be removed, or `size(A, 1)` can be directly used in the function body.

Also, some functions don't use `n`, in which case it can be removed.

**Comment by thorade** [comment]
Probably the A,B,C could be marked as constant, and then n can be a constant as well.

**Comment by mwetter** [comment]
@thorade I don't think there is a difference for the compiler between the current implementation and using the constant keyword, as these are protected members of a function. Or is there?

**Comment by thorade** [comment]
@mwetter According to OCT team, both compilation and simulation speed will slightly benefit from marking these protected variables as constant.

**Comment by mwetter** [comment]
@thorade : That for this insight. I will make them constant and move some up to the scope of the class if they are used in many functions.
