### ISSUE TITLE
Java weather converter 

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/modelica-ibpsa#1416]
This issue is to update the Java weather converter so that it will handle sub hourly data as intended in the .epw format. In particular 
if the field "minutes" is 00 or 60, then the data is considered hourly and the value reported is the value at the end of the hour. Instead if the "minutes" value is between 00 and 60 the field "hour" and "minutes (1,10) should be interpreted as  10 minutes in the first hour or just 10 minutes, while currently the code currently interprets it as 1 hour and 10 minutes or 70 minutes.
I already corrected the code and as soon as an issue branch is open I will make the pull request.

**Comment by mwetter** [comment]
Please make the pull request against the branch `issue1416_javaWeatherConverter`.
