### ISSUE TITLE
Html check issue

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1419]
I just merge IBPSA into IDEAS and my unit tests flag an html error that the IBPSA unit tests seem to ignore.

https://travis-ci.com/github/open-ideas/IDEAS/jobs/440814325
```
(cd ../../../../IDEAS; python3.6 ../bin/runUnitTests.py --validate-html-only)
274The following malformed html syntax has been found:
275[-- ./Fluid/Sensors/BaseClasses/PartialAbsoluteSensor.mo ]
276line 38 column 108 - Warning: <br> element not empty or not closed
277
278[-- ./Fluid/Interfaces/Examples/ReverseFlowMassExchanger.mo ]
279line 62 column 81 - Warning: <br> element not empty or not closed
280
281[-- ./Fluid/Interfaces/Examples/ReverseFlowHumidifier.mo ]
282line 28 column 81 - Warning: <br> element not empty or not closed
```

https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Fluid/Sensors/BaseClasses/PartialAbsoluteSensor.mo 
indeed contains
```
September 20, 2020, by Michael Wetter:<br/>
Introduced parameter <code>warnAboutOnePortConnection</code> and added assertion with level set to warning.</br>
```
The <br> tags are formulated differently. I think the first one is correct. The IBPSA travis log (https://travis-ci.com/github/ibpsa/modelica-ibpsa/jobs/388378832) does contain a html entry:
`(cd /home/travis/build/ibpsa/modelica-ibpsa/IBPSA; ../bin/runUnitTests.py --validate-html-only)`

Both the IBPSA and IDEAS repo use the Buildingspy master branch and install `pytidylib-0.3.2`. So I'm not sure what's going on.. Any ideas?

**Comment by mwetter** [comment]
@Mathadon : I don't know why these errors are not detected. I can reproduce it on my local installation and opened the issue https://github.com/lbl-srg/BuildingsPy/issues/391
