### ISSUE TITLE
Possible Bug in getTimeSpanTMY3 function

### ISSUE THREAD

**Issue by MichaMans** [ibpsa/modelica-ibpsa#1432]
There might be a bug in the getTimeSpanTMY3 function, used by the ReaderTMY3 of the library. Under windows, with Dymola Version 2021 (64-bit), 2020-04-17 with Visusal Studio 2017/Visual C++ 2017 Express Edition (15) set as compiler, the function cannot read properly long lines.

It might be an issue with the c - code behind that function as this is an external c function call. Unfortunately I have no idea about c and how to fix the problem. 

Reproducing the error is not that straight forward as I am getting the error, but not all the time.

At least in my last tries I managed to reproduce the error under windows with the Testgettimespan model attached and the reading of the example_weather.mos. I hope this is as simple as possible to hopefully reproduce the error.
[dymola.zip](https://github.com/ibpsa/modelica-ibpsa/files/5660508/dymola.zip)

**Comment by mwetter** [comment]
I can reproduce it with the new example `IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/GetTimeSpanTMY3LongHeader.mo` on Windows:

![image](https://user-images.githubusercontent.com/1329080/106011565-71b11880-606f-11eb-85ac-1e15cdb305f3.png)

Above, I translated the model and then repeatedly called dymosim.exe without doing any changes.

**Comment by MichaMans** [comment]
@mwetter thanks for having a look at it! So as you could reproduce the bug it also seems that it not occurs every time, right? Do you have any thoughts on what causes the error? Do you also bet on the external c function call? (as this does not get compiled right? and so is called on every simulation and not only on the translation step?)

**Comment by mwetter** [comment]
It probably is a memory violation related to the string allocation in the C code, but I need more time to correct it. It is compiled during translation but memory allocation can change from one simulation to another.
