### ISSUE TITLE
Branch for extended multi-zone airflow package

### ISSUE THREAD

**Issue by kldjonge** [ibpsa/modelica-ibpsa#1436]
I was asked during the IBPSA project 1.1 meeting to make a pull request to a branch in stead of the master (https://github.com/ibpsa/modelica-ibpsa/pull/1434)  so that travis checks weren't initiated with each commit. Can a branch be made for this purpose?

**Comment by mwetter** [comment]
@kldjonge : Please use `issue1436_AirflowNewClasses` which I just created.
