### ISSUE TITLE
Nomenclature issue psychrometric utilities function

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/modelica-ibpsa#1446]
I open this issue to change the description comment of the function **IBPSA.Utilities.Psychrometrics.Functions.X_pW**. Now is _"Humidity ratio for given water vapor pressure"_. However from the output of the function:
_algorithm 
  x_w := 0.62198*p_w/(p - p_w);
  X_w := x_w/(1 + x_w);_

X_w is the mass fraction of water vapour in the air. Therefore the comment should be changed to "Mass fraction for given water vapor pressure" to avoid confusion.

**Comment by EttoreZ** [comment]
I created the branch **Issue1446 psychrometrics utility comment**, as soon as @mwetter creates the branch I will make the pull request.

**Comment by Mathadon** [comment]
see https://github.com/ibpsa/modelica-ibpsa/tree/issue1446_PsychrometricsUtilityComment
