### ISSUE TITLE
Fan power modeling

### ISSUE THREAD

**Issue by dhblum** [ibpsa/modelica-ibpsa#1450]
Englander and Norford (1992a) noticed for fans controlled to a constant static pressure setpoint with VSD retrofits, measurements of power as a function of measured flow P(V) did not trend towards the origin as the classic fan law of P ~ V^3 suggests.  They developed a taxonomy of fan power modeling in Englander and Norford (1992b) that differentiated between:

1. fans that are controlled to a static pressure setpoint (e.g. VAV supply fans) that do not pass through the P(V) origin
2. fans that are not controlled to a static pressure setpoint (e.g. VAV return fans) that do pass through the P(V) origin.

They then introduced a model for 1. that could estimate P(V) from flow and static pressure setpoint, also noting that perfect static pressure reset would indeed cause P(V) to pass through the origin.  Though they differentiate this effect from that of low fan efficiency at low flow, it is not clear where the extra energy theoretically goes in the extreme case of a running fan against with fully closed dampers.  It could be that this energy could indeed by explained by very low efficiency if a first-principal model of flow work were actually used.  

The model for fans and pumps in this library uses such a first principals model of flow work with P = (dp*V)/(eta_shaft * eta_motor).  However, by default, efficiencies are set to be constant as a function of flow, which tend the P(V) to trend towards the origin even in static-pressure controlled cases.  Without a user knowing the importance of Englander and Norford's observations, and actively characterizing the efficiency as a function of flow using the available parameter, the model will under-predict fan energy at low flows.  

I've discussed a bit with @mwetter and @AntoineGautier and am opening this issue to further discuss and work out a potential fix.  One solution could be to implement a default shaft work efficiency curve as developed for EnergyPlus [here on page 1065](https://energyplus.net/sites/all/modules/custom/nrel_custom/pdfs/pdfs_v9.4.0/EngineeringReference.pdf).  @mwetter and @AntoineGautier feel free to fill in gaps I may have missed or corrections in our discussion.

References
-----------
- S.L. Englander and L.K. Norford (1992a). "Saving fan energy in VAV systems - part 1: Analysis of a variable speed drive retrofit." ASHRAE Transactions (98).
- S.L. Englander and L.K. Norford (1992b). "Variable speed drives: Improving energy consumption modeling and savings analysis techniques." ACEEE Summer Study Proceedings.

**Comment by Mathadon** [comment]
I've done some thinking about this too. It might help to add a power term that depends on `dp`, e.g. linearly or quadratically, without multiplying with`m_flow`. Ideally this is supported by data and by some physical rationale but I didn't get that far yet.

**Comment by mwetter** [comment]
To avoid too high fluid outlet temperature near zero flow rate, we could add a thermal loss from the fluid to some ambient (default) temperature.
