### ISSUE TITLE
asssert in ...ConservationEquation

### ISSUE THREAD

**Issue by carlesRT** [ibpsa/modelica-ibpsa#1505]
Hi,

I do use a Medium with two substances. I wanted to use `IBPSA.Fluid.HeatExchangers.BaseClasses.PartialEffectivenessNTU` but the following assert within `IBPSA.Fluid.Interfaces.PartialTwoPortInterface` is triggered,

```
  // Assert that the substance with name 'water' has been found.
  assert(Medium.nXi == 0 or abs(sum(s)-1) < 1e-5,
      "If Medium.nXi > 1, then substance 'water' must be present for one component.'"
         + Medium.mediumName + "'.\n"
         + "Check medium model.");
```

Notice that,

```
  final parameter Real s[Medium.nXi] = {if Modelica.Utilities.Strings.isEqual(string1=Medium.substanceNames[i],
                                            string2="Water",
                                            caseSensitive=false)
                                            then 1 else 0 for i in 1:Medium.nXi}
    "Vector with zero everywhere except where species is";
```

I do have water as substance, this is but located in second place within `substanceNames`. Since `reducedX=true` `nXi `is equal to 1 and the second substanceNames, "Water", is not checked. 

- At first glance I do not see any issue if I outcomment this assert, but...  Is it a problem if "water" is placed second/last in the substanceName? i.e. is there any convention I am not aware of? Or can I outcomment this assert if I do have "Water"?
- Should `nS` instead of `nXi` be used?

A Similar issue might appear in other components, e.g. `IBPSA.Fluid.Interfaces.ConservationEquation`

**Comment by mwetter** [comment]
I don't think you can just remove the assertion. It checks whether water was found when constructing `s`, and this is used for example in the conservation equation
```modelica
  if substanceDynamics == Modelica.Fluid.Types.Dynamics.SteadyState then
    zeros(Medium.nXi) =mbXi_flow + mWat_flow_internal*s;
  else
    der(mXi) =mbXi_flow + mWat_flow_internal*s;
  end if;
```
I don't know what medium you use, but maybe you can rearrange its components?

**Comment by Mathadon** [comment]
The current implementation indeed does not seem to support Media where the property order is reversed. We thus implicitly assume that water is the independent property. I'd also try to revise the Medium property order as a simple workaround..

**Comment by carlesRT** [comment]
Thanks for your feedback.

I use LiBrH2O Media of the DCOL Library. Yes, I can rearrange the components, I guess will do so, though I will not be enough, I might need to revise the use of the media in some components as well. 

I guess we can close it?

**Comment by Mathadon** [comment]
Sure!
