### ISSUE TITLE
impure functions

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1506]
@casella reports here https://github.com/open-ideas/IDEAS/issues/1225#issuecomment-884753516 

that `getHeaderElementTMY3()` is an impure function and should be flagged as such. I guess that we do not do this yet since we're not yet compliant with the Modelica spec v3.5? See https://specification.modelica.org/maint/3.5/MLS.html section 12.3, which seems to be new.

**Comment by mwetter** [comment]
Yes, `impure function` won't work with our version (OCT issues an error and I double JModelica would work). I suggest this to be added when we switch to MSL 4.0.0

**Comment by Mathadon** [comment]
Alright!

**Comment by mwetter** [comment]
This is now on the master as
```modelica
within IBPSA.BoundaryConditions.WeatherData.BaseClasses;
impure function getHeaderElementTMY3
...
```
