### ISSUE TITLE
remove include for ModelicaUtilities.h in getTimeSpan.h

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1507]
Based on https://github.com/open-ideas/IDEAS/issues/1225#issuecomment-885434297 and the response of @casella (https://github.com/open-ideas/IDEAS/issues/1225#issuecomment-885588542) the include of `ModelicaUtilities.h` in `getTimeSpan.h` can/should be removed in order for OMC to work with the file. 

@mwetter do you know whether this would conflict with OCT or Dymola? I guess that the include was added with a reason.. Can it be removed?

**Comment by Mathadon** [comment]
Dymola 2020 works fine without the include and so does the final release of JModelica.

**Comment by mwetter** [comment]
The include statement can be removed. I will make a PR.
