### ISSUE TITLE
Implementation of PlugFlowPipeDiscretized

### ISSUE THREAD

**Issue by bravache** [ibpsa/modelica-ibpsa#1538]
This issue is for implementing the `PlugFlowPipeDiscretized` which is a wrapper around N instances of `IBPSA.Fluid.FixedResistances.PlugFlowPipe` connected in series, with a single pipe resistance calculation.

The main purpose of this class is to allow for varying boundary conditions over the length of a pipe. The `PlugFlowPipe` heat transfer calculation is based on a fixed temperature boundary conditions (and constant along the length of the pipe), and this assumption can be dubious for buried pipes that are long, uninsulated and/or with a high temperature gradient with the soil.

Test and performances of the discretized pipe were evaluated in https://github.com/lbl-srg/modelica-buildings/pull/2409. The following text is copied from there.

---

I have added the model `PlugFlowDiscretize` to address some of the concerns from the previous model, namely: how can we justify a constant temperature boundary condition (constant along the length of the pipe), especially in cases with uninsulated pipes and for long stretch of pipes.

The main change is that this model allows to discretize `PlugFlowCore` axially. In some ways, this goes against the main benefit of the plug flow model, which is to avoid discretization of the problem, but on the other hand, it allows to more easily justify a semi-fixed temperature boundary for each segment.

I also toyed with the idea of formalizing a "virtual insulation layer" parameter in the model, but it is actually tricky since this layer would take on the soil thermal property, and the pipe is currently not coupled with the soil. This means that if I were to formalize this virtual insulation layer, I would have to also add the soil as a parameter to the `PlugFlowDiscretize`. In the end, I opted for not adding that option, but showcased how to use virtual insulation in the example `DiscretizedBuriedPipes` (by simply making the insulation take on the soil conductivity and making the insulation thickness as the virtual layer thickness).

Playing with this `PlugFlowDiscretize` model in the example confirmed what we suspected: for uninsulated pipes, the number of segment has a significant impact on heat transfer. This impact is not significant for insulated pipes. In the example below, I run 90degC water for 10km, either with no insulation (technically, there is an insulation layer with 100W/mK conductivity) or with 2cm of mineral wool (k=0.035W/mK).
![image](https://user-images.githubusercontent.com/48033702/121043438-7ac29c80-c769-11eb-8187-ef293c2b0197.png)

With regard to virtual insulation, the observation is that it can offset the need for discretization to a certain extent. The soil higher conductivity (k=1.58W/mK) does not allow us to fully substitute actual insulation with a layer of soil. In the example below, I run 20degC water for 10km, with either 20cm or 0.2cm of virtual insulation. What we see is that when the pipe is segmented in 10 pieces, the virtual insulation thickness has a moderate impact on the outlet temperature, and when the pipe is not discretized, we see that thicker virtual insulation slightly reduces the gap between 1seg-10seg.
![image](https://user-images.githubusercontent.com/48033702/121045061-86629300-c76a-11eb-8431-304e028ccc12.png)

I have tried coming up with an analytical solution for the heat balance between the plug flow pipe model and the ground coupling model which could recommend the right number of segment or virtual insulation thickness, but was not successful. I am open to suggestion though.

**Comment by mwetter** [comment]
This is addressed on the master.
