### ISSUE TITLE
Handling of flow reversal in x-port interfaces

### ISSUE THREAD

**Issue by hcasperfu** [ibpsa/modelica-ibpsa#1578]
This issue is to improve the handling of flow reversal for `IBPSA.Fluid.Interfaces.PartialTwoPortInterface`, `.PartialFourPortInterface`, and `.PartialEightPortInterface`. When determining `sta_a` and `sta_b`, It replaces or removes the `actualStream()` operator if `allowFlowReversal == false`. 
The reasons for this revision include:

- This operator is pointless if flow reversal is not allowed.
- This operator will flip values in `sta_a` and `sta_b` when the flow has a small negative value due to numerical noise even if flow reversal is not allowed. This may produce results that are contrary to the user's intention. (See lbl-srg/modelica-buildings#2866)

**Comment by thorade** [comment]
Should the same change be applied to _Vector interface? And wrap into if allowFlowReversal?

https://github.com/ibpsa/modelica-ibpsa/blob/c52a650877e5246cc8b19b1e7e7ba609df73aa68/IBPSA/Fluid/Interfaces/PartialTwoPortVector.mo#L41-L51
