### ISSUE TITLE
Protected parameter in signal exchange blocks

### ISSUE THREAD

**Issue by dhblum** [ibpsa/modelica-ibpsa#1585]
Using the BOPTEST parser (https://github.com/ibpsa/project1-boptest/blob/master/parsing/parser.py) to compile the wrapped test case FMU with Spawn/Optimica is not able to find the signal exchange blocks.  This is because the parameters ``boptestOverwrite`` and ``boptestRead`` present in the blocks are protected and Spawn/Optimica does not make them visible in the resulting FMU.  This issue is to remove the ``protected`` statement from the blocks, which then allows Spawn/Optimica to be used for compiling the wrapped test case FMUs with the BOPTEST parser.

@kbenne this is the issue you are running into.

**Comment by mwetter** [comment]
Closed as this is on the master branch.
