### ISSUE TITLE
(min=0) attribute to parameter h in MediumColumn

### ISSUE THREAD

**Issue by kldjonge** [ibpsa/modelica-ibpsa#1599]
Would it be possible to not use of the `(min=0) `attribute in this case? 

To use this model as sub-component in other models, the height of the density column often depends on other parameters and as such, it is possible that the height turns out to be negative (effectively flipping the column upside down OR mathematically: changing the sign of dP ).

```
model MediumColumn
...
  parameter Modelica.Units.SI.Length h(min=0) = 3 "Height of shaft";
```

**Comment by kldjonge** [comment]
Flipping the model is what I tried first but turned out to require a load of messy conditional connect statements. I will check if overriding the `min` attribute works, I never needed to do that before apparently (and didn't know it was a possibility), thanks for the suggestion!

**Comment by mwetter** [comment]
I will close this, please reopen if the issue persists.
