### ISSUE TITLE
refactor towards relative pressure in ports instead of absolute pressure

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1600]
Currently, the variable `p` of a `FluidPort` contains the absolute pressure. Absolute pressures are typically in the order of 100 000 Pa and can have pressure differences in the order of a few Pascal. When solving algebraic loops that compute these pressure differences to high accuracy, the relative large absolute pressure causes 5 digits of precision to be lost and can cause solver problems.

This issue is to discuss the possibility of refactoring the library such that `FluidPort.p` contains the relative pressure instead of an absolute pressure. This should avoid the issue described above. E.g. `Medium.reference_p` could be subtracted from the absolute pressure. At least the following models would require changes:
- boundary_pT etc (subtract reference_p when assigning the port pressure)

- MixingVolume ( add reference_p when assigning the BaseProperties/medium pressure)

- any model that uses `Medium.setState_p**(port.p, ...)`

Is this of interest for the library?

**Comment by mwetter** [comment]
This is already investigated at
https://github.com/ibpsa/modelica-ibpsa/pull/1413/files#diff-5865f9ce0ce1ce8aa94dd5e97179439d6633a7874322c896ddb9848f5792e055R108
for the code change for pressure as a state and
https://github.com/ibpsa/modelica-ibpsa/pull/1413
for the PR (work in progress for the IBPSA and Buildings libraries ) that applies similar transformation to other states. We should aim on finishing up this work and either apply or reject it.

This work will need to include tool developers, which we started with Modelon, to be sure the transformed variables indeed show up in the respective equations of the solver.

**Comment by Mathadon** [comment]
okay! I wouldn't worry about the last point btw. The wrong variables can't end up in the algebraic loop solver if they do not exist!
