### ISSUE TITLE
Add weekly schedule functionality

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1601]
This continues development from https://github.com/open-ideas/IDEAS/issues/1248. 

This issue is to create an external model for loading weekly schedules from file. The schedules have a format that is easy for humans to interpret and modify. The schedule (a txt file) may look like for 3 output signals:

```
# some comment
double  tab1(3,5) #test:
#
mon:0:0:10              -       3       1       -   # monday at 10 seconds past midnight
tue,thu:20:30           123     -       45      -  # Tuesdays and Thursdays at 20:30
wed                     12      1       4       - # Wednesday at midnight
```

Dashes '-' are used as wildcards and indicate that the values defined by the previous row (rows are expanded and sorted chronologically internally) should be reused. The lookup wraps back to the end of the table in case no value is defined by the start of the table. If no value is defined at all then 0 is returned by default.

**Comment by mwetter** [comment]
- [ ] Should this be called `Utilites.Schedules.Weekly` and pre-populated with some standard schedules for offices and homes? See also https://web.ashrae.org/90_1files/pdfs/Addendum_an_Sched_and_Load.pdf?

**Comment by mwetter** [comment]
This model has been merged.
