### ISSUE TITLE
Negative Fan Power

### ISSUE THREAD

**Issue by hcasperfu** [ibpsa/modelica-ibpsa#1621]
This issue is to add a non-negative constraint to the flow work computation
_W&#775;<sub>flo</sub> = V&#775; &Delta; p >= 0_
in `IBPSA.Fluid.Movers.BaseClasses.FlowMachineInterface` in order to prevent the model from producing negative power when either the pressure rise or the flow rate is negative. 
An example of this situation is in the model `Buildings.Examples.DualFanDualDuct.ClosedLoop` (as of https://github.com/lbl-srg/modelica-buildings/commit/b65753005f56311322c675892f0fc75fc5b1d9bd). When the cold deck is dominant, the hot deck fan `fanSupHot` is forced to have a pressure drop instead of rise across the fan because it is overpowered by the return fan `fanRet`. This results in negative fan power in the model which is incorrect.

![ClosedLoop](https://user-images.githubusercontent.com/91219266/172228481-20b6d9fa-90d2-4285-8a94-4e596ec126ec.png)

**Comment by Mathadon** [comment]
I do not entirely agree with this analysis. Fans can indeed be operated as turbines that generate power instead of consuming it. Not every fan may support this since it depends on the used technology but many do. 

I think we have to look further at the root cause of the problem here.

**Comment by mwetter** [comment]
@Mathadon : If we want to have a fan also act as a turbine, more work would be needed. I don't think users expect it to work that way. For example, if a fan has an efficiency of 80%, and the shaft work is 1000 W, then `PEle = PSha/eMot = 1000/0.8`, e.g, it would produce more electricity than the flow work that it transmits at the shaft. Also, we would need to know what a variable frequency drive would be doing in this case. In light of this, I suggest we set negative flow work to zero.

**Comment by Mathadon** [comment]
@mwetter that's a good point. Okay, let's  cap the flow work.

Can we add a note to the documentation that explains this 'approximation' and perhaps add a link to this issue?

**Comment by hcasperfu** [comment]
@Mathadon 
Thank you for the feedback!
I have updated the documentation of `FlowMachineInterface` as well as the `usersguide` with a brief explanation and a link to this post.
