### ISSUE TITLE
Wrong convertClass usage in conversion script

### ISSUE THREAD

**Issue by FWuellhorst** [ibpsa/modelica-ibpsa#1626]
The file https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Resources/Scripts/Conversion/ConvertIBPSA_from_3.0_to_4.0.mos uses the `convertClass` with too many arguments. I guess it sould be `convertModifiers` instead.

I get the error in AixLib (blindly copied from IBPSA:
![image](https://user-images.githubusercontent.com/22442514/178961308-277e908b-9632-4cbf-9ba0-b7528fefcbfe.png)

@mwetter : If I got the mistake right, I can change the script. Or does the script work for you?

**Comment by mwetter** [comment]
@FWuellhorst : This is indeed an error. It would be great if you can make a pull request.

**Comment by FWuellhorst** [comment]
@mwetter : I created the PR #1629 .
One question: Which reviewers are typically available for IBPSA? I can always request your review, but such minor changes could also be reviewed by someone else I guess.

**Comment by mwetter** [comment]
@FWuellhorst : Thanks for the pull request. You should be able to put any name from https://github.com/ibpsa/modelica-ibpsa/graphs/contributors into the review assignment, also best is to use those with recent contributions as some moved on to other work.

**Comment by FWuellhorst** [comment]
This was closed in https://github.com/ibpsa/modelica-ibpsa/pull/1629.
