### ISSUE TITLE
Heat Exchanger Model Numerics

### ISSUE THREAD

**Issue by hcasperfu** [ibpsa/modelica-ibpsa#1682]
In `IBPSA.Fluid.HeatExchangers.{WetCoilEffectivenessNTU,BaseClasses.PartialEffectivenessNTU}`, there is this equation block:

```
equation
  if (configuration == con.ParallelFlow) then
    flowRegime = if (C1_flow*C2_flow >= 0)
      then 
        flo.ParallelFlow
      else 
        flo.CounterFlow;
  elseif (configuration == con.CounterFlow) then
    flowRegime = if (C1_flow*C2_flow >= 0)
      then 
        flo.CounterFlow
      else 
        flo.ParallelFlow;
  elseif (configuration == con.CrossFlowUnmixed) then
    flowRegime = flo.CrossFlowUnmixed;
  elseif (configuration == con.CrossFlowStream1MixedStream2Unmixed) then
    flowRegime = if (C1_flow < C2_flow)
      then 
        flo.CrossFlowCMinMixedCMaxUnmixed
      else 
        flo.CrossFlowCMinUnmixedCMaxMixed;
  else
    flowRegime = if (C1_flow < C2_flow)
      then 
        flo.CrossFlowCMinUnmixedCMaxMixed
      else 
        flo.CrossFlowCMinMixedCMaxUnmixed;
  end if;
```

This block is numerically problematic. For example, with
```
    flowRegime = if (C1_flow*C2_flow >= 0)
      then 
        flo.CounterFlow
      else 
        flo.ParallelFlow;
```
the numerical noise can cause the model to generate events and switch equations frequently.

After brief discussions with @mwetter, we suggest:
- removing this equation block,
- removing the variable `flowRegime`,
- and replacing the use of `flowRegime` elsewhere in these models with `flowRegime_nominal`.

These changes have the implication that once the flow regime is determined by nominal values, the model now sticks with this set of equations regardless of the actual flow conditions during the simulation. But we believe that reversing the flow inside a heat exchanger during operation is unusual. Having a robust implementation is worth having this limitation.

**Comment by carlesRT** [comment]
Issue to be discussed (comments done on pull request #1683) and potentially reopened.
