### ISSUE TITLE
Dependency warning in heat pump calibration

### ISSUE THREAD

**Issue by FWuellhorst** [ibpsa/modelica-ibpsa#1696]
We enabled the dependabot feature in the AixLib, and it warned us about an issue with the `certifi` requirement in the doc part of the heat pump calibration: https://github.com/RWTH-EBC/AixLib/pull/1420

@mwetter @MassimoCimmino: Are these requirements used actively in any script like CI or similar? If so, we should update the version to `2022.12.7` and check if the docs are still generated correctly.

**Comment by mwetter** [comment]
@FWuellhorst That is already corrected in IBPSA, see https://github.com/ibpsa/modelica-ibpsa/pull/1670
