### ISSUE TITLE
Updates on ISO13790 package

### ISSUE THREAD

**Issue by amaccarini** [ibpsa/modelica-ibpsa#1707]
This issue will focus on making two updates on the ISO13790 package:

- The `ISO13790.Validation.BESTEST` package will be updated by using the recent results from ANSI/ASHRAE Standard 140-2020. Current results are based on an old version (ANSI/ASHRAE Standard 140-2007). In addition, the documentation text will be improved by showing some plots to directly visualize differences among tools. 
- Two models will be added to `ISO13790.Examples` package. In particular, template models of residential and office will be developed using pre-defined occupancy schedules and typical HVAC systems.

**Comment by amaccarini** [comment]
@mwetter: I noticed that the model `Buildings.Controls.OBC.CDL.Continuous.MovingAverage` is not available in the IBPSA library, but it would actually be useful for the BESTEST validation. Is it possible to integrate into the IBPSA library?

**Comment by mwetter** [comment]
@amaccarini : As `CDL` is not in the `IBPSA` library, and still undergoes some changes, I suggest you copy this block and put it for example in `IBPSA.Utilities.Math` or into a `BaseClasses` package of your validation.

**Comment by mwetter** [comment]
This is now merged to the master.
