### ISSUE TITLE
An Update to the Contributor's List (Steam Medium)

### ISSUE THREAD

**Issue by khinkelman** [ibpsa/modelica-ibpsa#1786]
Hi @mwetter, I was wondering if it is possible to add me to the contributor's list for this library (with the contributions of `Media.Steam` and related models)? 

Thanks for your consideration. 

```
<li>Kathryn Hinkelman, University of Colorado Boulder, USA
</li>
```

**Comment by mwetter** [comment]
Sure, I will address this through https://github.com/ibpsa/modelica-ibpsa/pull/1787
