### ISSUE TITLE
Update SimpleHouse tutorial using feedback of Modelica Conference

### ISSUE THREAD

**Issue by jelgerjansen** [ibpsa/modelica-ibpsa#1803]
This issue is to update the SimpleHouse tutorial using feedback from the Modelica Conference. Some feedback I already got during the workshop:

- [x] The documentation of `SimpleHouse3` mentions a nominal mass flow rate of 1 kg/m3 instead of 1 kg/s.
- [ ] The plots in the documentation uses seconds (mega seconds) on the time axis. Days would be a more suitable unit. 

@mwetter @LauraMaier @drehelmns @nytschgeusen please let me know if you have any other feedback, then I'll create a development branch and apply these changes.

**Comment by mwetter** [comment]
@jelgerjansen : Regarding the plot unit, could you please file an issue on the OpenModelica repository. It would be very convenient to switch between seconds and minutes/hours/days, and also use such a switch in units in the experiment setup window.

**Comment by jelgerjansen** [comment]
I filed the issue of changing the time unit in OM: https://github.com/OpenModelica/OpenModelica/issues/11382
Once this is integrated, I'll update the reference results and create a pull request.

**Comment by jelgerjansen** [comment]
Typo is fixed in #1899, time unit will be fixed in the future once this is integrated in OM

**Comment by jelgerjansen** [comment]
Closed by #1899
