### ISSUE TITLE
Issue about Dymola simulation

### ISSUE THREAD

**Issue by XiongbaXu** [ibpsa/modelica-ibpsa#1812]
I revised one model (Guideline 36) from Buildings library. I added some sensors from Buildings library and revised the control signal of exhausted damper, but I meet a problem when I conducted simulation. In one day simulation process, the simulation would be hold in a specific time(shown in the picture).

![damper_1](https://github.com/ibpsa/modelica-ibpsa/assets/140901145/49371eda-67a4-4429-9bc5-51066da49cc1)
![problem_1 1](https://github.com/ibpsa/modelica-ibpsa/assets/140901145/89e19d5b-c3b6-4e23-8087-ec4cb597de94)

**Comment by mwetter** [comment]
This is the wrong repository to report issues with models from the Buildings library.
Before you report it on the Buildings repository, please check the Dymola manual for how to debug models, and if this won't help, we would need a clear description for how to reproduce the problem. Most likely however it is a solver related issue which you would need to report to the Dassault support.
