### ISSUE TITLE
Missing header includes in jsonWriterInit.c and fileWriterStructure.c

### ISSUE THREAD

**Issue by henrikt-ma** [ibpsa/modelica-ibpsa#1818]
Similar to #1816, the two files _jsonWriterInit.c_ and _fileWriterStructure.c_ also need to include _stdlib.h_ and _string.h_.

This is needed for the `JSONWriterObject.constructor`: https://github.com/ibpsa/modelica-ibpsa/blob/5250513d8a2b94412baefdadfe2743e1c60801c2/IBPSA/Utilities/IO/Files/BaseClasses/JSONWriterObject.mo#L15

**Comment by mwetter** [comment]
@henrikt-ma : Thanks for the notice. I made pull requests for IBPSA and Buildings.

**Comment by henrikt-ma** [comment]
Thanks, your response time is fantastic!
