### ISSUE TITLE
Connection between causal and acausal connectors

### ISSUE THREAD

**Issue by maltelenz** [ibpsa/modelica-ibpsa#1829]
Here:
https://github.com/ibpsa/modelica-ibpsa/blob/86bfd55f17c123448c7caaa494217891cb9a3597/IBPSA/Fluid/FMI/Conversion/AirToOutlet.mo#L159

`outlet.backward` is declared as input:

https://github.com/ibpsa/modelica-ibpsa/blob/86bfd55f17c123448c7caaa494217891cb9a3597/IBPSA/Fluid/FMI/Interfaces/Outlet.mo#L27-L29

while `bacPro_internal` is not declared as `output`:

https://github.com/ibpsa/modelica-ibpsa/blob/86bfd55f17c123448c7caaa494217891cb9a3597/IBPSA/Fluid/FMI/Conversion/AirToOutlet.mo#L96-L98

This makes this an illegal connection.

There are other cases, like this one:

https://github.com/ibpsa/modelica-ibpsa/blob/86bfd55f17c123448c7caaa494217891cb9a3597/IBPSA/Fluid/FMI/Conversion/AirToOutlet.mo#L147

and in InletToAir:
https://github.com/ibpsa/modelica-ibpsa/blob/86bfd55f17c123448c7caaa494217891cb9a3597/IBPSA/Fluid/FMI/Conversion/InletToAir.mo#L116
https://github.com/ibpsa/modelica-ibpsa/blob/86bfd55f17c123448c7caaa494217891cb9a3597/IBPSA/Fluid/FMI/Conversion/InletToAir.mo#L104

**Comment by mwetter** [comment]
@maltelenz : Could you please test whether https://github.com/ibpsa/modelica-ibpsa/pull/1835 corrects the issue.

**Comment by maltelenz** [comment]
I can confirm that with #1835 System Modeler no longer complains about this issue.

(I now get another error, but that is very likely to be an issue with System Modeler itself, and seems unrelated to this fix.)
