### ISSUE TITLE
Structurally singular initial equation system in PPM model

### ISSUE THREAD

**Issue by maltelenz** [ibpsa/modelica-ibpsa#1830]
For `IBPSA.Fluid.Sensors.Examples.PPM` Wolfram System Modeler gives the following error:

> Error: Overdetermined initial equation system.
Error: The initialization problem is structurally singular, the following equations cannot be solved for any variable:
    volSte.dynBal.ports_H_flow[1] = semiLinear(0.0, 0.0, volSte.dynBal.hOut)
    sin.p = volDyn.p_start
  Given the following equations:
    $START.volSte.dynBal.m = volSte.V * volSte.rho_start
    volSte.dynBal.m = 1.18430792005922e-05 * volSte.V * volSte.p_start
    volSte.dynBal.ports_mXi_flow[1,1] = semiLinear(0.0, 0.0, volSte.dynBal.medium.Xi[1])
    $START.volSte.dynBal.mXi[1] = 0.01 * volSte.dynBal.fluidVolume * volSte.dynBal.rho_start
    $START.volSte.dynBal.hOut = volSte.dynBal.hStart
    $START.volSte.heatPort.T = volSte.T_start
    volSte.heatPort.T = volSte.T
    0.0 = volSte.dynBal.ports_mXi_flow[3,1] + volSte.dynBal.ports_mXi_flow[1,1] + volSte.dynBal.ports_mXi_flow[2,1]
    volSte.dynBal.ports_mXi_flow[2,1] = semiLinear(mSouSta.m_flow, 0.01, volSte.dynBal.medium.Xi[1])
    volSte.dynBal.medium.state.X[1] = volSte.dynBal.medium.Xi[1]
    volSte.dynBal.medium.R_s = 461.523329085088 * volSte.dynBal.medium.Xi[1] + 287.051224952979 * volSte.dynBal.medium.X[2]
    volSte.dynBal.medium.MM = 1 / (55.508435061792 * volSte.dynBal.medium.Xi[1] + 34.5242878865884 * volSte.dynBal.medium.X[2])
    volSte.dynBal.mXi[1] = volSte.dynBal.m * volSte.dynBal.medium.Xi[1]
    volSte.dynBal.hOut = 1006.0 * volSte.dynBal.medium.X[2] * volSte.dynBal.medium.dT + (1860.0 * volSte.dynBal.medium.dT + 2501014.5) * volSte.dynBal.medium.Xi[1]
    volSte.T = IBPSA.Fluid.Sensors.Examples.PPM.volDyn.Medium.temperature_phX(0.0, volSte.dynBal.hOut, {volSte.dynBal.medium.Xi[1], 1.0 - volSte.dynBal.medium.Xi[1]})
    -volSte.dynBal.ports_mXi_flow[3,1] = semiLinear(mSouSta.m_flow, volSte.dynBal.medium.Xi[1], 0.01)
    volSte.dynBal.medium.X[2] = 1.0 - volSte.dynBal.medium.Xi[1]
    volSte.dynBal.medium.X[1] = volSte.dynBal.medium.Xi[1]
    senPPMSta.port_a.h_outflow = 995.94 * (sin.T + (-273.15)) + 0.01 * (1860.0 * sin.T + 1992955.5)
    mSouSta.h_internal = 995.94 * (mSouSta.T + (-273.15)) + 0.01 * (1860.0 * mSouSta.T + 1992955.5)
    volSte.dynBal.ports_H_flow[2] = semiLinear(mSouSta.m_flow, mSouSta.h_internal, volSte.dynBal.hOut)
    -volSte.dynBal.ports_H_flow[3] = semiLinear(mSouSta.m_flow, volSte.dynBal.hOut, senPPMSta.port_a.h_outflow)
    0.0 = volSte.dynBal.ports_H_flow[3] + volSte.dynBal.ports_H_flow[1] + volSte.dynBal.ports_H_flow[2]

We (System Modeler) don't typically allow for overdetermined and inconsistent initial equations.

We can see that OpenModelica agrees that the initialization problem is overspecified in their test run log [here](https://libraries.openmodelica.org/branches/master/IBPSA_latest/files/IBPSA_latest_IBPSA.Fluid.Sensors.Examples.PPM.err), but that they decide to drop an equation and go on anyway:

> Warning: The initial conditions are over specified. The following 1 initial equations are redundant, so they are removed from the initialization system:
         volDyn.dynBal.medium.p = volDyn.dynBal.p_start.

Perhaps the model could be improved to have a consistently specified initialization?

**Comment by mwetter** [comment]
@maltelenz : Can you please check if https://github.com/ibpsa/modelica-ibpsa/pull/1834 corrects the issue for System Modeler. (Note that as far as I see, the initial conditions were over-specified but consistent. The change in the model should remove this problem.)

**Comment by maltelenz** [comment]
I can confirm it simulates cleanly in System Modeler with #1834 .
