### ISSUE TITLE
Add HeatMeter as sensor

### ISSUE THREAD

**Issue by JAG-1337** [ibpsa/modelica-ibpsa#1831]
When validating systems of components or heating networks, I would like to have a simple heat meter for measurement of thermal energy.

The implementation inherits from `PartialDynamicFlowSensor` and adds a temperature input `T_other` to finally calculate

    Q_flow = port_a.m_flow * Medium.cp_const * (T - T_other);

with `T` being the temperature of the fluid passing through that sensor.

**Comment by mwetter** [comment]
That would be a good addition. Can you please make an implementation and pull request to the branch `issue1831_heatMeter`.
