### ISSUE TITLE
Allow reference years later than 2020 in CalendarTime

### ISSUE THREAD

**Issue by jelgerjansen** [ibpsa/modelica-ibpsa#1847]
The CalendarTime model has epoch time stamps till 2031, but the model itself does not allow custom years later than 2020.
Can't we update this by adding extra elseif statements for the calculation of `zerTim`, e.g.
```
elseif zerTim == IBPSA.Utilities.Time.Types.ZeroTime.NY2021 or 
    zerTim == IBPSA.Utilities.Time.Types.ZeroTime.Custom and yearRef == 2021 then
      timOff :=timeStampsNewYear[12];
```
and extending `IBPSA.Utilities.Types.ZeroTime` accordingly? Or am I missing something?

While updating this, we could also add more epoch times (e.g. till 2040)?

**Comment by mwetter** [comment]
I think that would be a good improvement.

**Comment by jelgerjansen** [comment]
@mwetter I pushed a fix to my repo. Do I create a PR from [my branch](https://github.com/jelgerjansen/modelica-ibpsa/tree/issue1847_calendarTime) directly to the master? Or do you want to create a separate branch on the ibpsa repo first?

**Comment by mwetter** [comment]
@jelgerjansen : I created a new branch `issue1847_calendarTime` so we can the review and CI testing. I think you should also have permissions to create branches; let me know otherwise.
