### ISSUE TITLE
More connections between causal and acausal connectors

### ISSUE THREAD

**Issue by maltelenz** [ibpsa/modelica-ibpsa#1853]
I have discovered more cases where a causal connector is connected to a non-causal one, similar to #1829.

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Source_T.mo#L70

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Source_T.mo#L66

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Adaptors/Inlet.mo#L68

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Adaptors/Inlet.mo#L73

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/FlowSplitter_u.mo#L78

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Sink_T.mo#L59-L60

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Adaptors/Outlet.mo#L64

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Adaptors/Outlet.mo#L68

https://github.com/ibpsa/modelica-ibpsa/blob/b8d6489e9d27b68556f754afb200a1d610e3f937/IBPSA/Fluid/FMI/Adaptors/Outlet.mo#L75

**Comment by mwetter** [comment]
@maltelenz : Thanks for reporting. This will be closed through https://github.com/ibpsa/modelica-ibpsa/pull/1854
