### ISSUE TITLE
Root error in getPeak calculation even though Euler is not selected

### ISSUE THREAD

**Issue by FWuellhorst** [ibpsa/modelica-ibpsa#1912]
In the mover models, we encountered a bug confirmed by @hcasperfu for the case of a `power` specification even though not used according to the grey-out graphic view, as we did not select Euler method:
```
Error: The following error was detected at time: 0
Computing the roots of a polynomial with function "Modelica.Math.Polynomials.roots"
failed because the first element of the coefficient vector is zero, but should not be.
Failed condition: abs(p[1]) > 0
The stack of functions is:
Modelica.Math.Polynomials.roots
AixLib.Fluid.Movers.BaseClasses.Euler.getPeak
AixLib.Fluid.Movers.BaseClasses.Euler.getPeak(
indoorSwimming.cirPump.per.pressure, 
indoorSwimming.cirPump.per.power)
```

I added two models to a temp branch to show you the error:
https://github.com/RWTH-EBC/AixLib/tree/showEulerError/AixLib/Fluid/Pools/Examples
The only difference to the no-error model is this specification.

Specification with error: (https://github.com/RWTH-EBC/AixLib/blob/showEulerError/AixLib/Fluid/Pools/IndoorSwimmingPoolWithError.mo)
```
    redeclare Movers.Data.Generic per(
      pressure(V_flow={0,m_flow_nominal/1000,m_flow_nominal/1000/0.7}, dp={
            pumpHead/0.7,pumpHead,0}),
      etaHydMet=AixLib.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.Efficiency_VolumeFlowRate,

      etaMotMet=AixLib.Fluid.Movers.BaseClasses.Types.MotorEfficiencyMethod.Efficiency_VolumeFlowRate,

      efficiency(V_flow={0,m_flow_nominal/1000,m_flow_nominal/1000/0.7}, eta={
            0.7,0.8,0.7}),
      motorEfficiency(V_flow={0,m_flow_nominal/1000,m_flow_nominal/1000/0.7},
          eta={0.9,0.9,0.9}),
      power(V_flow={0,(m_flow_nominal/1000*0.2),(m_flow_nominal/1000*0.5),
            m_flow_nominal/1000*0.7,m_flow_nominal/1000,m_flow_nominal/1000/0.7,
            m_flow_nominal/1000/0.6,m_flow_nominal/1000/0.5,m_flow_nominal/1000
            /0.4}, P={(m_flow_nominal/0.4)/1000*pumpHead/0.7/0.9,(
            m_flow_nominal/0.5)/1000*pumpHead/0.7/0.9,(m_flow_nominal/0.6)/1000
            *pumpHead/0.7/0.9,(m_flow_nominal/0.7)/1000*pumpHead/0.7/0.9,
            m_flow_nominal/1000*pumpHead/0.8/0.9,(m_flow_nominal/1000*0.7)*
            pumpHead/0.7/0.9,(m_flow_nominal/1000*0.5)*pumpHead/0.7/0.9,(
            m_flow_nominal/1000*0.2)*pumpHead/0.7/0.9,0}))
```
Removing `power` solves the issue:

```
    redeclare Movers.Data.Generic per(
      pressure(V_flow={0,m_flow_nominal/1000,m_flow_nominal/1000/0.7}, dp={
            pumpHead/0.7,pumpHead,0}),
      etaHydMet=AixLib.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.Efficiency_VolumeFlowRate,
      etaMotMet=AixLib.Fluid.Movers.BaseClasses.Types.MotorEfficiencyMethod.Efficiency_VolumeFlowRate,
      efficiency(V_flow={0,m_flow_nominal/1000,m_flow_nominal/1000/0.7}, eta={0.7,
            0.8,0.7}),
      motorEfficiency(V_flow={0,m_flow_nominal/1000,m_flow_nominal/1000/0.7},
          eta={0.9,0.9,0.9})),
```

**Comment by hcasperfu** [comment]
I think the power curve provided in the declaration is causing trouble, and I see two problems with it.
If I plug in `m_flow_nominal = 1; pumpHead = 1000;`, I get a $P(\dot V)$ power curve that trends down, while at constant speed it should should have a concave shape. See graphs below. This resulted in a monotonic efficiency curve trending up. `getPeak()` assumes that the efficiency curve has a maximum value, hence it fails.
The second problem is that the power should not reach zero. This is the whole point of using the Euler number method. The hydraulic power (or total electric power) is not zero when the flow work ($\dot V \Delta p$) is zero, and the Euler number method provides a way to approximate that. 

<img width="394" alt="image" src="https://github.com/user-attachments/assets/74871a1e-78a9-42a8-9aba-abc7e1fb2e0b">

**Comment by FWuellhorst** [comment]
I agree. The question is if the error should be more specific and whether to check for these conditions or not. For me it is fine to keep it like this, the power curve was not used anyway. 
Another minor issue: I wanted to check how the regression was done, and the UsersGuide states:
```
This curve is based on a least squares polynomial fit of all pressure curves from
<a href=\"Modelica://IBPSA.Fluid.Movers.Data.Pumps\">
IBPSA.Fluid.Movers.Data.Pumps</a>
for pumps and
<a href=\"Modelica://IBPSA.Fluid.Movers.Data.Fans\">
IBPSA.Fluid.Movers.Data.Fans</a>
for fans.
(See also
<a href=\"https://github.com/lbl-srg/modelica-buildings/issues/1884\">#1884</a>.)
```

The linked issue does not seem to be correct.

**Comment by hcasperfu** [comment]
@FWuellhorst -
I've created a PR to hide the `getPeak()` function unless it is needed.
I also updated the link you mentioned. Previously the graph we were trying to refer to was still in the development branch and we decided against citing it in the official release. Thanks for catching that!
