### ISSUE TITLE
Make proposition to add heat pump model

### ISSUE THREAD

**Issue by damienpicard** [ibpsa/modelica-ibpsa#223]
This issue can be use to discuss a general heat pump implementation.

**Comment by damienpicard** [comment]
Special care should be spent to make to model compatible with the input data of Energy +

**Comment by mwetter** [comment]
Each library should create a branch `Annex60_HP_review`

**Comment by damienpicard** [comment]
The KULeuven model can be found in:
https://github.com/open-ideas/IDEAS/tree/Annex60_HP_review

The models are in `IDEAS.Fluid.Production`.

**Comment by mwetter** [comment]
The LBNL models are at
https://github.com/lbl-srg/modelica-buildings/tree/Annex60_HP_review
in the package `Fluid/HeatExchangers/HeatPumps`
A few unit tests of the base classes do not yet work, and also the air to air heat pump fails the model check due to a syntax error.

**Comment by KristianHuchtemann** [comment]
The RWTH Aachen model can be found here:
https://github.com/RWTH-EBC/AixLib/tree/Annex60_HP_review
in `AixLib/Fluid/HeatExchangers/HeatPump`

**Comment by damienpicard** [comment]
Dear all,

I made a small qualitative comparison between the IDEAS and Buildings heat pump model.
The comparison can be found on this link:
https://docs.google.com/spreadsheets/d/1MCp-S20RlsxlY-m2P3vKMVa3hW3r-jMMvyjB8qlotqk/edit?usp=sharing

My general conclusions are:
1. The buildings library models are physically more accurate, as they take the start up and shut down behaviour fo the HP into account as well as the moisture condensation. The IDEAS does not have such options.
2. The buidlings library models can be set to heating or cooling while two different models need to be used in IDEAS. This feature can, however, probably be easily added.
3. The buidlings library models require the pre-computation of the heat pump coefficients by the user, while the IDEAS model only require the performance map. IDEAS models seem also to be more flexibel regarding to the type of data provided, as it can use 1D, 2D and 3D performance maps and the inputs types are not pre-defined.
4. The inheritance of the buildings library models between water-water and air-air / air-water heat pump is low while the IDEAS models use a single heat source model which is useable for all the heat pump types and also for a boiler model. However, the lack of inheritance in the buildings library is due to the calculation of the moisture condensation which is not taken into account in IDEAS.
5. The control inputs of the IDEAS models are more intuitive and complete, as the user can either specify the required output temperature or heat, or modulation rate, ... while the Buildings model is limited to a speed input.

Based on these observations, it is clear that the models of both libraries have a different focus. IDEAS models are meant to be flexible, easy to use and to parametrize and easy to control, while the Buildings models are more physical.

**Comment by damienpicard** [comment]
New link with edit right:
https://docs.google.com/spreadsheets/d/1MCp-S20RlsxlY-m2P3vKMVa3hW3r-jMMvyjB8qlotqk/edit?usp=sharing

**Comment by Mathadon** [comment]
@damienpicard @mwetter can this be closed?

**Comment by mwetter** [comment]
Let's close it for now as this is also on the Berlin agenda.
