### ISSUE TITLE
consider adding storage tank to library

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#314]
Consider adding or a merge the storage tank model from `IDEAS`, `BuilingSystems`, `Buildings` and maybe `AixLib`  to the `Annex60` library.

Next step is to discuss the four models during the phone call.
Filip to check with his co-worker about the stratification model.

**Comment by Mathadon** [comment]
I spoke to Brecht. He's currently working on a publication of reduced order models that we can later integrate into Annex 60. His main remark is that buoyancy should be considered as something that has a source and not something that 'homogeneously' appears in the tank, as we model it now.
For instance this source ca be a hot yet that anders the tank, or a heating coil that is heated. Both effects should be treated differently. From my understanding the momentum of the incoming jets is quite important and should therefore be considered into more detail.

To be continued!

**Comment by mwetter** [comment]
Each library developer should add a branch `annex60_tank` for review on the future call.

**Comment by Mathadon** [comment]
I checked with Brecht. He has a Modelica implementation of a tank that seems to work very well. It explicitly takes into account the mixing introduced by jets instead of using a temperature inversion model.

I need to rework the code to be compatible with the Annex 60 base classes, which I probably won't have time for before february so I propose to postpone this meeting topic.

**Comment by mwetter** [comment]
OK, we can cover this topic in February. I assume the model also takes into account mixing if you add warmer water at the bottom of the tank, which is not related to having a jet.

**Comment by Mathadon** [comment]
The code I'm working on is in:
https://github.com/Mathadon/modelica-annex60/tree/issue314_storageTank 
there however seems to be a bug in the model, which I've thus far been unable to track..

**Comment by carlesRT** [comment]
Hi, I added in the branch https://github.com/carlesRT/modelica-annex60/tree/Annex60_tank_review
the storage tank model we currently have in the BuildingSystems library, <code>StratifiedStorage</code>. It is a relatively simple model, discretized volume in vertical direction with heat conductivity between layers + buoyancy model ("Rule-based demand side management..." Leuven). 

It is quite difficult to properly model the storage tank behaviour, they might have different Height/diameter ratio, n° and position of the in-/outflows, mass flow rates, etc. I tried to find some simple and general model. I could find a model based on detailed numerical experiments but focus on the cooling phase (nor charge neither discharge). I think it could be at least used for cros-validation purposes. I added in the branch, <code>GlobalModel</code>. There are still some uncertainities in the results.. I contact the author of the thesis. Hope, she can help.

Besides that I think it could be good to add some model to evaluate the storage tanks efficiency, for instance the <code>MIX-number</code>.

**Comment by Mathadon** [comment]
Brecht fixed our model such that the results now align with his paper.
The code is on https://github.com/BrechtBa/modelica-annex60/tree/issue314_storageTank

**Comment by Mathadon** [comment]
Can we have a look at merging the Buildings storage tank model into IBPSA? I'd prefer this implementation over the existing IDEAS model.

**Comment by Mathadon** [comment]
I'll make a pull request that simply copies all examples and unit tests from Buildings?

**Comment by mwetter** [comment]
That would be great. In one of the example you will need to replace some
control blocks as they are from the OBC package in Buildings, but there are
equivalent blocks in the MSL.

**Comment by Mathadon** [comment]
consider it (somewhere) on my to do list!

**Comment by Mathadon** [comment]
@RouvenZ the currently implemented model `IBPSA.Fluid.Storage.Stratified` has no link to the model in the paper. They are different models and will produce different results. This issue was not finished and as such the model is only available on the referenced branch.

**Comment by RouvenZ** [comment]
@Mathadon Thank you for your quick clarification! Is there any process or plan you know of to merge this issue (or comparably, to introduce buoyant jets) into the `IBPSA.Fluid.Storage.Stratified` model? Or was there never the necessity to do so as the present `IBPSA.Fluid.Storage.Stratified` model performed reasonably well verified against experimental data?

**Comment by Mathadon** [comment]
There are no plans to work on this. Mostly since nobody is taking up the work, I do think that the buoyant jets can cause different results than what the current models are predicting. In some cases at least.
