### ISSUE TITLE
Add analyses of air benchmark

### ISSUE THREAD

**Issue by marcusfuchs** [ibpsa/modelica-ibpsa#416]
So far, the airflow benchmark has not been put to use. I have added a Python script that simulates the scalable benchmark to see how the CPU time depends on the problem size. As a first result, I obtained this:
![airbenchmarkscaling](https://cloud.githubusercontent.com/assets/5516900/13141336/19e4ff1c-d637-11e5-8bf0-dd2439be56eb.png)

I hope we can use this issue to discuss how to proceed with the benchmark and how it can be useful for meaningful analyses.

**Comment by Mathadon** [comment]
It would be useful to have a similar plot that plots the maximum/largest non-linear system size after reduction.. I expect there will be a large correlation between the two plots.

**Comment by marcusfuchs** [comment]
I agree. These may be the things for which such a scalable benchmark could be useful. I can add such a plot and another one for CPU time over system size.

**Comment by Mathadon** [comment]
@mwetter I guess that we can close this?
