### ISSUE TITLE
Flow reversal issue when dp=0

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#439]
Consider the case where you have a fluid network with the following structure:

![screen shot 2016-03-19 at 16 23 15](https://cloud.githubusercontent.com/assets/5970879/13899460/ecb662c2-edee-11e5-9e58-d7cd65ebeb6c.png)

when `res*(from_dp=true)` the pressure in the middle of the two pressure drop components `p_mid` will be an iteration variable. Consider now the case where `bou.p_in=bou1.p_in=1e5`. The algebraic loop solver will then solve towards `p_mid` such that `res1.dp=1e5-p_mid` and `res.dp=p_mid-1e5`.
The algebraic loop solver will stop when a certain accuracy for `p_mid` is obtained, for which the solution may not exactly be 1e5. When this is not the case the solution will be that there is a small (+- 1e-6 kg/s) mass flow rate through `res` and `res1`, in opposed directions. 
This results in 2 problems:
1) mass is not conserved, which is not really that much of a problem in practice
2) flow reversal occurs, which can lead to errors when `allowFlowReversal=false` since this assumes that no flow reversal occurs. When this situation occurs for a long time this can lead to numerical problems where for instance the species concentration `Xi` in a mixing volume becomes negative, causing the simulation to crash.

This effect is causing some problems for me so it would be nice if we could somehow get the solver to find exactly that `p_mid=1e5`. I think this should be doable by changing the pressure drop curves such that they are linear around `m_flow=0`. This corresponds to a laminar flow regime which also occurs in practice. Moreover I have experienced problems (bad validation results) in cases where I was not able to correctly simulate a laminar flow regime, so this would be nice to have. It would also allow a more physical interpretation of how to set `m_flow_turbulent`.

Is this something we can have a look into?

**Comment by mwetter** [comment]
Such a laminarization would be nice to have provided that it is computationally efficient, which I think can be done.
It won't however guarantee that the solution will be found exactly. Even though the equations are linear in some neighborhood, the solver still solves them up to some accuracy. You may be lucky that it gets closer as the Jacobians may be exact (if they happened to be updated) but there is no guarantee. All you are guaranteed is that the solver stops when the approximate solution satisfies a certain tolerance.

An implementation may be `dp = k * m_flow^n(m_flow)`, where 
```
n(x) = 2 if x > m_flow_turbulent, 
n(x) = 1 if x < 3/4 m_flow_turbulent [the implementation may then simply use a linear function]
n(x) has a smooth transition between the two values 
```
and similarly for negative flow rates.

A basic flow function that allows `n` different from 2 also would make it simple to implement an air filter, for which `n` is typically between 1 and 2.

**Comment by Mathadon** [comment]
To be discussed at Porticcio!

**Comment by mwetter** [comment]
This should be compared with the MSL implementation. We could compute `dh=f(m_flow_turbulent, Re=2300...4000)` and then use this diameter for the laminar pressure drop.
