### ISSUE TITLE
singularity in ConservationEquation for m_flow=0

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#445]
It turns out that `dynamicBalance` did have a use! I updated my model and I get instant crashes =)

The problem is that the `ConservationEquation` equations are not properly regularised for zero flow, i.e. we have:

```
ports_H_flow[i]     = semiLinear(ports[i].m_flow, inStream(ports[i].h_outflow), ports[i].h_outflow) 
```

when `m_flow=0` and `energyDynamics=SteadyState` this equation may end up in a (linear) algebraic loop that cannot be solved:

```
Rhs component 1 of system 4 is -nan
Rhs component 2 of system 4 is -nan
Rhs component 3 of system 4 is -nan
Rhs component 4 of system 4 is -nan
In system 4 valve1.port_1.h_outflow = -nan
In system 4 valve2.port_1.h_outflow = -nan
In system 4 valve3.port_1.h_outflow = -nan
In system 4 valve4.port_1.h_outflow = -nan
LINEAR SYSTEM OF EQUATIONS IS SINGULAR AT TIME = 135
```

To solve this, I guess we can copy the implementation from 
Franke, R., Casella, F., Otter, M., Sielemann, M., Elmqvist, H., Mattson, S. E., & Olsson, H. (2009). Stream Connectors – An Extension of Modelica for Device-Oriented Modeling of Convective Transport Phenomena, 108–121. doi:10.3384/ecp09430078
?
Unless we think we can do better of course!

**Comment by Mathadon** [comment]
Some intermediate analysis:
it seems difficult to find a solution that 1) regularises the equations, that 2) also correctly simplifies code when `allowFlowReversal=false` and that 3) has few equations. This is because when computing the mixing enthalpy, the flow regularisation uses the enthalpy of each port, even when its mass flow rate equals zero. This means that having `m_flow(min=0)` does not lead to simplifications, which breaks the simplification for `allowFlowReversal=false`.

A solution may be to write the energy balance separately for each port such that `nPorts` mixing enthalpies are computed. The computation for port `i` should then exclude `inStream(port[i].h_outflow)`. This leads to more lines of (flattened) code but should lead to the desired simplifications. This is also how `h_outflow` seems to be computed in the paper.

**Comment by Mathadon** [comment]
The `semiLinear` is not really the problem. The problem is that 
```
semiLinear(ports[i].m_flow, inStream(ports[i].h_outflow), ports[i].h_outflow)
```
is converted into 
```
if ports[i].m_flow > 0 then ports[i].m_flow * inStream(ports[i].h_outflow) else ports[i].m_flow*ports[i].h_outflow
```
which does not contain a regularisation for zero flow, but instead a simple multiplication between `m` and `h`. Using `actualStream` would not change that.

**Comment by Mathadon** [comment]
I think it would be best to implement the approach from 
Franke, R., Casella, F., Otter, M., Sielemann, M., Elmqvist, H., Mattson, S. E., & Olsson, H. (2009). Stream Connectors – An Extension of Modelica for Device-Oriented Modeling of Convective Transport Phenomena, 108–121. doi:10.3384/ecp09430078

where there are `nPorts` calculations of the mixing enthalpy.

Excerpt:
![screen shot 2016-05-03 at 08 22 45](https://cloud.githubusercontent.com/assets/5970879/14976045/50a9c8f0-1108-11e6-8910-d2ca8a48b764.png)

the regularised version of these equations should of course be implemented.

This however changes the equations for the case when the energy dynamics are not steady state too. I think we should look into this in more detail in Miami.

**Comment by Mathadon** [comment]
I added an implementation in https://github.com/iea-annex60/modelica-annex60/tree/issue445_steadystatemultiport

I created another conservationequation model: ```Annex60.Fluid.Interfaces.StaticMultiPortConservationEquation``` that implements the equations above.
It is used when the `energyDynamics` and `massDynamics` are both `SteadyState` and when `nPorts>2`.

I also added an example model that demonstrates the old bug:
```
Annex60.Fluid.MixingVolumes.Validation.MixingVolumeZeroFlowMultiPort
```

The model now runs fine but it does not when you set

```
final parameter Boolean useSteadyStateMultiPort=false;
```

in  `Annex60.Fluid.MixingVolumes.BaseClasses.PartialMixingVolume`.

Additionally I had to set `prescribedHeatFlowRate=true` by default in `Annex60.Fluid.MixingVolumes.BaseClasses.PartialMixingVolume`. This is because by default the heat port of a `MixingVolume` is not connected, resulting in `heatPort.Q_flow=0`. Setting `prescribedHeatFlowRate=false` therefore results in a bug in `Annex60.Fluid.MixingVolumes.Validation.MixingVolumeZeroFlowMultiPort`.
I had to set `prescribedHeatFlowRate=true` in two models that used to rely on the default value of `prescribedHeatFlowRate` to operate correctly.

Todo: 
 [-] implement the smooth approximation (I currently use a max() function)
 [-] verify implementation for correctness since this is not currently checked in the unit tests
 [-] add unit test for example
 [-] review documentation

**Comment by mwetter** [comment]
@Mathadon : Also JModelica requires `useSteadyStateMultiPort=true` for `Annex60.Fluid.MixingVolumes.Validation.MixingVolumeZeroFlowMultiPort` to simulate past t=0.5

Having 3 models looks OK to me. It looks clearer than putting your new code into `ConservationEquation`.

Let's also discuss in Miami the rational for allowing different values for `energyDynamics` and `massDynamics`. I am not sure if having these flexibility, combined with 3 different mass/energy balances, is sufficiently transparent and justified by its benefits.

**Comment by Mathadon** [comment]
I agree that the result is non-physical. Note that this issue already existed in `Annex60.Fluid.MixingVolumes.Validation.MixingVolumeZeroFlow` too, so at least it's consistent with the other implementations. The example is mostly to show that the simulation does not crash.

We could add a conditional assert that catches this?

**Comment by mwetter** [comment]
Yes, an assertion would be good as users will use it in a non-physical way,
which we want to avoid.

**Comment by Mathadon** [comment]
Okay, so todo: 
- [ ] implement the smooth approximation (I currently use a max() function)
- [ ] verify implementation for correctness since this is not currently checked in the unit tests
- [ ] add unit test for example
- [ ] review documentation
- [ ] add asserts for conservation of energy

**Comment by Mathadon** [comment]
The new implementation so far does not have clear advantages. 
The current implementation status is that we have 
1) smaller linear systems
2) larger non-linear systems
3) more stable equations but only when initialising at zero flow, since dymola accepts singular consistent systems

due to these reasons we decide to postpone this development until we have a clear example that shows that a new implementation is really necessary.

**Comment by Mathadon** [comment]
I haven't come across this problem during the last few years so I'm ok with closing this, @mwetter ?
