### ISSUE TITLE
missing comments in model instances in Airflow.Multizone package

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#515]
Many models in `Annex60.Airflow.Multizone.Examples` and in `Annex60.Airflow.Multizone.Validation` have instances that have no comment. These missing comments should be added.

**Comment by kldjonge** [comment]
Going through the older issues to look for airflow related issues.
Seems this issue should be solved before merging the https://github.com/ibpsa/modelica-ibpsa/tree/issue1436_AirflowNewClasses

**Comment by mwetter** [comment]
@kldjonge : This fell off the radar. I will add them in `issue515_airflow_missing_comments`
