### ISSUE TITLE
Functions no longer inlined

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#543]
It seems that `Annex60.Fluid.BaseClasses.FlowModels.basicFlowFunction_m_flow` etc are no longer inlined. Setting `Inline=True` instead of `LateInline=True` in all flow functions and their derivates reduced computation time from 39 to 31s for `Annex60.Fluid.Examples.FlowSystem.Basic` on the Corsica branch.

Shall I make this change?

**Comment by Mathadon** [comment]
Actually inlining `Annex60.Fluid.BaseClasses.FlowModels.basicFlowFunction_dp_der` does not work even with `Inline=True` and after expanding the factors.

**Comment by mwetter** [comment]
@Mathadon : This would be a good change.

**Comment by Mathadon** [comment]
This change has the adverse effect that the functions are inlined before symbolic processing. Therefore when a non-linear algebraic loop of size 1 is formed, the function inverse is no longer used to analytically solve the algebraic loop. Instead it is solved iteratively. This occurs in many examples and will also have a computation cost penalty for many examples.

I therefore propose to not implement the change and instead make a bug report.

**Comment by mwetter** [comment]
Yes, in this case I suggest to leave the code.

**Comment by Mathadon** [comment]
The developers are aware of the issue.

**Comment by mwetter** [comment]
@Mathadon Branch `issue543_inlining` has an unmerged commit. Can this branch be deleted?

**Comment by Mathadon** [comment]
Based on the discussion above this need not be merged. We should probably check though whether this issue is resolved in Dymola 2017FD01.

**Comment by Mathadon** [comment]
I deleted the branch.
