### ISSUE TITLE
Dymola 2017 computes different results

### ISSUE THREAD

**Issue by tsnouidui** [ibpsa/modelica-ibpsa#635]
This issue is to analyze if Dymola 2017 computes different/incorrect results for the model 
Annex60.Fluid.BaseClasses.FlowModels.Validation.InvertingBasicFlowFunction_m_flow.
This model produces different results compared to JModelica

**Comment by Mathadon** [comment]
This may be related to the fact that we set InvertingBasicFlowFunction_m_flow as the inverse of InvertingBasicFlowFunction_dp using the inverse annotation. However this is not correct since in the regularisation region a different regularisation function is used (i.e. They are not the inverse of each other).

**Comment by thorade** [comment]
The FluidDissipation library also always supplies two functions that are the inveres of each other and that have regularisation around zero. Is anything contained in there helpful?
https://github.com/ClaRaLibrary/FluidDissipation/

Another idea might be to base the regularization on `tanh`:
http://mathworld.wolfram.com/HyperbolicTangent.html
or sigmoid function:
http://mathworld.wolfram.com/SigmoidFunction.html
Not sure whether that would help, or how expensive that would be,
maybe I didn't even understand the problem...

**Comment by Mathadon** [comment]
I don't think the FluidDissipation library uses the correct inverse either since `https://github.com/ClaRaLibrary/FluidDissipation/blob/master/PressureLoss/StraightPipe/dp_overall_DP.mo` and `https://github.com/ClaRaLibrary/FluidDissipation/blob/master/PressureLoss/StraightPipe/dp_overall_MFLOW.mo` use the same regularisation function.

**Comment by thorade** [comment]
I also posted this as a question on StackExchange:
http://math.stackexchange.com/q/2096077/92706

**Comment by tsnouidui** [comment]
JModelica does not support the inverse annotation which yields to the difference in results.

**Comment by thorade** [comment]
@tsnouidui Do you know what JModelica does then instead? Do they try to invert symbolically or do they just nvert numerically?

**Comment by thorade** [comment]
One idea for a alternative regularisation function could be of the form
`y:= a*sinh(b*x)` 
with the exact inverse
`x := asinh(y/a)/b`
and then find `a` and `b` such that the value and derivative of the original function and the regularisation function match at `m_flow_turbulent`.

With some help, I found values for a and b:
http://math.stackexchange.com/questions/2100016/solve-system-of-two-trigonometric-equations
```
b=1.915008048/m_flow_turbulent
a=m_flow^2/k^2/sinh(b*m_flow)
```
where the value `1.915...` is the numerical solution for this equation:
http://www.wolframalpha.com/input/?i=solve+2+*tanh(x)-x=0

Reinserting the expressions for `a` and `b` yields
```
dp := m_flow_turbulent^2/k^2 * sinh(1.915008048*m_flow/m_flow_turbulent)/3.319826386;
m_flow := m_flow_turbulent/1.915008048 * asinh(m_flow*k^2/m_flow_turbulent^2*3.319826386);
```
where `sinh(1.915008048) = 3.319826386`

A first and second derivative should also exist, but I would only try to find them if that alternative regularisation function solves this issue of Dymola vs JModelica giving different results.
I will send a Pull Request implementing these two functions. Thierry, could you test whether that leads to identical results in Dymola and JModelica? If yes, I can send the derivatives in a second PR.

**Comment by thorade** [comment]
I can only open Pull Requests against existing branches, which is not what I want to do.
Instead of a PR, you can find the code here (or open a PR yourself):
https://github.com/thorade/modelica-annex60/tree/issue635_sinh

**Comment by tsnouidui** [comment]
Thanks. JModelica is planning on supporting the inverse annotation soon. They will give us some details in few days. This should resolve the issue and make the code produce the same results in the different tools.

**Comment by mwetter** [comment]
@thorade 
That looks like a nice implementation to test. I think however that the function is C1 and not C2. If the computations are fast and robust, I think a C1 implementation that is invertible is preferable over the current C2 implementation whose inverse is not exact.

However, you currently write that the function is C2 using smoothOrder=2:
https://github.com/thorade/modelica-annex60/blob/issue635_sinh/Annex60/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp.mo#L22
Is the 2nd derivative really continuous? I haven't looked at the trajectories, but I doubt it is C2 because you don't seem to impose conditions for the 2nd derivative.

A drawback of using C1 vs. C2 is that for optimization, many algorithms require the cost function to be C2. Hence, maybe by default we could use the C1 implementation but allow to select the C2 implementation with a boolean constant?

**Comment by thorade** [comment]
Yes, you are right, the second derivative of the original function (a constant) and the second derivative of the alternative regularisation function do not match.
The annotation was just there because I forgot to change it.

I'll think some more, maybe I can just add the third condition somehow.

**Comment by Mathadon** [comment]
If you use

`y:= c + a*sinh(b*x)` you get another degree of freedom `c`
and the inverse is
`x:=asinh((y-c)/1)/b` 
I did not check the shape of the function but maybe it helps!

**Comment by thorade** [comment]
Just adding a constant was also my first idea, but then it is no longer symmetric with respect to the ordinate axis.

**Comment by Mathadon** [comment]
in that case:

`y:= a*sinh(b*x)^c` 
and
`x:=asinh((y^(1/c))/1)/b` 
?

**Comment by thorade** [comment]
Works only for integer values of c.
But `sinh=1/2(e^z - e^-z)` and that maybe allows to introduce more variables

**Comment by Mathadon** [comment]
but then I suppose the inverse becomes non-trivial to determine?

**Comment by thorade** [comment]
Correct, and the function is also not symmetric. Hm.
Maybe `y := a*sinh(b*x) + c*cosh(d*x)` or something similar.

**Comment by Mathadon** [comment]
can we invert that?

**Comment by thorade** [comment]
No. My next guess `y := a*sinh(b*x) +c*x` also seems to be non-invertible.

**Comment by mwetter** [comment]
Closed for now as no work is progressing.

**Comment by mwetter** [comment]
Maybe a 3rd order polynomial in m_flow^2 could be invertible.

**Comment by Mathadon** [comment]
Now that I think of it, the curve is symmetric around zero, so a curve of form 
```
a x + b x^ 3 + c x^5
``` 
could make more sense.

**Comment by thorade** [comment]
Yes, it is an odd function.
Using 3rd or 5th order polynomials means that the analytical inverse function has a 3rd or 5th root, to my understanding!? That is why I was looking at trigonometric functions like sin(x) which is also odd, because it has a nicer inverse.

**Comment by Mathadon** [comment]
that's true :)

**Comment by thorade** [comment]
Do Bézier curves have an analytical inverse?
https://en.wikipedia.org/wiki/B%C3%A9zier_curve

**Comment by Mathadon** [comment]
I seem to recall that the regStep or spliceFunction result in an 'infinitely continuous' transition. Maybe we can just use this..?

**Comment by thorade** [comment]
Would that also give a non-zero slope at x=0 ?
The function as it is is smooth, it is replaced with a different one to have the non-zero slope at zero.

**Comment by Mathadon** [comment]
the unit test of `IBPSA.Utilities.Math.Functions.Examples.SpliceFunction` seems to give a nonzero slope?

**Comment by thorade** [comment]
But looking at the function, I am not sure whether it has an exact inverse?
https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Utilities/Math/Functions/spliceFunction.mo

**Comment by Mathadon** [comment]
Oh yes, forgot about that.. Will need to look into that later.

**Comment by thorade** [comment]
m_turbulent could be chosen such that the suggested function becomes C2, instead of letting the user specify it.
