### ISSUE TITLE
Nominal values for mixing volume

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#664]
This is for integrating https://github.com/lbl-srg/modelica-buildings/issues/629

Please see this ticket for a discussion.

@Mathadon I suggest to integrate it in `Annex60`. Do you want to run other benchmarks?

**Comment by Mathadon** [comment]
I'd like to run a benchmark on IDEAS. I have a defence for my PhD this monday so probably I won't have time until afterwards.

**Comment by mwetter** [comment]
I will close this as state selection and scaling will be addressed through https://github.com/ibpsa/modelica-ibpsa/issues/1412

**Comment by mwetter** [comment]
Branch was `issue664_states_scaling`
