### ISSUE TITLE
Add approach temperature to Carnot.mo

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#698]
This issue is to integrate https://github.com/lbl-srg/modelica-buildings/issues/653 as otherwise, the COP of the heat pump is unreasonably high if there is a small temperature lift. Adding an approach temperature is also justified as the Carnot efficiency is for the refrigerant temperatures rather than the water temperatures.

**Comment by FelixBue** [comment]
I implemented the approach temperature in the buildings library in the branch "issue653_carnot_dt". I don't have a Dymola license at the moment, so I can't check for any errors if I make changes to the code.

I could implement it and someone else would have to check if it works. Or you just copy the lines 53-59 and 139-142 from Carnot.mo in the above named issue yourself.

**Comment by mwetter** [comment]
@FelixBue Thanks, I will integrate the changes in the IBPSA library.

**Comment by mwetter** [comment]
Todo:
- [ ] add validation that shows that the nominal efficiency is achieved during simulation if the temperatures are at the nominal temperatures (this verifies that the approach temperatures are correctly used for the initialization and the simulation).
