### ISSUE TITLE
Unfortunate naming of repository 

### ISSUE THREAD

**Issue by dietmarw** [ibpsa/modelica-ibpsa#719]
The current naming of the repository `modelica` is rather unfortunate for automatic listing on modelica.org/libraries. This basically prohibits to add it to the list of available libraries. You should think of renaming the repo to something like IBPSAlib or similar.

**Comment by thorade** [comment]
Also see the discussion in #674

**Comment by mwetter** [comment]
I suggest we rename the repository to `https://github.com/ibpsa/modelica-ibpsa`.

`ibpsa-lib` would in my view be too generic as there may be other IBPSA libraries in the future.

**Comment by tsnouidui** [comment]
I suggest we rename it to` https://github.com/ibpsa/MIL` or `mil` which stands for the name of the library.

**Comment by Mathadon** [comment]
+1

**Comment by tbeu** [comment]
MIL is short for Model in the loop, right?

**Comment by tsnouidui** [comment]
True as MSL is short for Mars Science Laboratory ;-). I think MIL is unique with respect to IBPSA?

**Comment by mwetter** [comment]
I'd prefer a repository name from which one can recognize Modelica and IBPSA.

**Comment by tbeu** [comment]
If `modelica-ibpsa`, then better `Modelica_IBPSA`.
