### ISSUE TITLE
Non-smooth min() function in PartialEffectiveness

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#737]
In `IBPSA.Fluid.HeatExchangers.BaseClasses.PartialEffectiveness` we currently have 
```
CMin_flow = min(C1_flow, C2_flow);
```
which is C0 and could lead to problems when this equation ends up in an algebraic loop.

I'll add an implementation using `smoothMin`

**Comment by Mathadon** [comment]
As suggested in #736 we could add something like:

```
  if smoothness == IBPSA.Types.Smoothness.C0 then
    CMin_flow = min(C1_flow, C2_flow);
  elseif smoothness == IBPSA.Types.Smoothness.C1 then
    CMin_flow = Modelica.Fluid.Utilities.cubicHermite(...);
  else
    CMin_flow = Modelica.Fluid.Utilities.quinticHermite(...);
  end if;
```

I'm just not sure how to treat `C1_flow=C2_flow=0`.. Since this leads to a division by zero.

**Comment by Mathadon** [comment]
Actually, this seems to work rather well for me:

```
CMin_flow = C1_flow + C2_flow - ((C1_flow)^10 + (C2_flow)^10)^(1/10);
```

this returns 0 when `C1_flow` or `C2_flow` or both are zero. Since both arguments should always be positive, I think we can use it in this case. I think the largest relative error this produces is 2^(1/10). Which in this case is 7%. The power 10 can be increased/reduced based on the required accuracy.

@mwetter would this be a good approach?

**Comment by Mathadon** [comment]
Moreover I propose to replace

```
  C1_flow = abs(m1_flow)*
    ( if allowFlowReversal1 then 
           fra_a1 * Medium1.specificHeatCapacityCp(state_a1_inflow) +
           fra_b1 * Medium1.specificHeatCapacityCp(state_b1_inflow) else 
        Medium1.specificHeatCapacityCp(state_a1_inflow));
  C2_flow = abs(m2_flow)*
    ( if allowFlowReversal2 then 
           fra_a2 * Medium2.specificHeatCapacityCp(state_a2_inflow) +
           fra_b2 * Medium2.specificHeatCapacityCp(state_b2_inflow) else 
        Medium2.specificHeatCapacityCp(state_a2_inflow));
```
by
```
  C1_flow = 
      if allowFlowReversal1 then 
           abs(m1_flow)*(fra_a1 * Medium1.specificHeatCapacityCp(state_a1_inflow) +
           fra_b1 * Medium1.specificHeatCapacityCp(state_b1_inflow)) else 
        m1_flow*Medium1.specificHeatCapacityCp(state_a1_inflow);
  C2_flow = 
      if allowFlowReversal2 then 
           abs(m2_flow)*(fra_a2 * Medium2.specificHeatCapacityCp(state_a2_inflow) +
           fra_b2 * Medium2.specificHeatCapacityCp(state_b2_inflow)) else 
        m2_flow*Medium2.specificHeatCapacityCp(state_a2_inflow);
```

since this removes a source of non-differentiability when `allowFlowReversal=false`

**Comment by mwetter** [comment]
@Mathadon : The changes should be fine but will need testing with Buildings as this code is used in `DryEffectivenessNTU` that is a bit more involved than `ConstantEffectiveness`.

However, we should have an accuracy of about 1%, e.g., use a larger exponent, as 7% is quite high an error. Does the error depend on quantities so that we can ensure an error of about 1%?

**Comment by Mathadon** [comment]
I think we should be able to ensure that, but if we increase the exponent further, we should probably check whether a `double` does not overflow for reasonable values of `CMin_flow` and whether the computation cost of the power and square root operations does not scale with the exponent value.

**Comment by Mathadon** [comment]
Also, I think the combined operations of power and square root is non-differentiable around zero (flow), similarly to `sqrt(x^2)=abs(x)`. So removing the abs(m_flow) probably won't have the desired effect. I'm currently using the formulation though, since the solve should not pass through `m_flow=0`. I'll to further testing before continuing with this.
