### ISSUE TITLE
too sensitive assert in StaticTwoPortConservationEquation

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#741]
I'm getting following warning (after having extended the assert output):

```
noEvent((if abs(adsolairs.bureaux2.heatingOut.m_flow) < 1E-60 then 
abs(adsolairs.bureaux2.heater.Q1_flow) < 1E-10 else 
abs(adsolairs.bureaux2.heater.Q1_flow/adsolairs.bureaux2.heater.bal2.vol.cp_default/adsolairs.bureaux2.heatingOut.m_flow) < 200))
The following was detected at time: 1404170000
Energy may not be conserved for small mass flow rates. 
This model may require prescribedHeatFlowRate = false. Found 
Q_flow=-7.41038e-18 
abs(Q_flow)=  7.41038e-18 
abs(m_flow) = 9.75149e-43
```

`m_flow` is solved from an algebraic loop and should be zero, but instead it is just very small. This value is used to compute `Q_flow` through `CMin_flow = C1_flow + C2_flow - ((C1_flow)^10 + (C2_flow)^10)^(1/10);`. This last computation subtracts `C2_flow - (C2_flow^6 + 0)^(1/6)` with `C2_flow` nonzero, which is relatively large due to numerical noise, although still very small (7e-18). The assert is correctly triggered since this heat flow rate corresponds to a huge temperature difference (~1e20K).

I propose to change

```
    assert(noEvent(if abs(m_flow) < Modelica.Constants.small
      then 
        abs(Q_flow) < 1E-10
      else 
        abs(Q_flow/cp_default/m_flow) < 200);
```
into
```
    assert(noEvent(if abs(m_flow) < 1e-10
      then 
        abs(Q_flow) < 1E-10
      else 
        abs(Q_flow/cp_default/m_flow) < 200);
```
to solve this.

**Comment by mwetter** [comment]
This needs to be reverted, it brakes various models in `Buildings`, see https://travis-ci.org/lbl-srg/modelica-buildings/builds/225370841

**Comment by Mathadon** [comment]
Probably `abs(Q_flow) < 1E-10` is now too strict.

If we solve `abs(Q_flow/cp_default/m_flow) < 200);` for `Q_flow` with `m_flow=1e-10` then we could use `abs(Q_flow) < 2e-8 * cp_default`?

**Comment by mwetter** [comment]
Or we could simply use 
```
constant debug = false "Set to true for debugging";
...
if debug then ....
```
This is probably more robust. I reverted your change on `issue741_staticTwoPort`

**Comment by Mathadon** [comment]
I'm not sure why this helps? My change was not for debugging purposes. It was solving an actual problem during simulation.

**Comment by mwetter** [comment]
It would get around the problem of running these tests in normal simulations. Then, one could enable them if a model is being developed or debugged.

**Comment by Mathadon** [comment]
Sounds like a good idea, but that assumes that all model errors will be caught by the unit tests set up during development and that the developer knows how and when to enable this constant?

**Comment by mwetter** [comment]
No, we don't want to change the constant for the unit tests, as it can change the numerics and cause test to pass or fail which otherwise would fail or pass. (And running all tests twice with the different settings would take too much resources.) I was thinking that a model developer should enable it temporarily if she/he wants to verify the model.
