### ISSUE TITLE
Remove minimum attribute of deltaM in PressureDrop

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#745]
In `PressureDrop` we currently have 

```
 parameter Real deltaM(min=0.01) = 0.3
    "Fraction of nominal mass flow rate where transition to turbulent occurs";
```

Is there a reason why we have a minimum attribute for `deltaM`? I'd prefer to remove it as setting small values for `deltaM` allows the (non C2-continuous) regularisation region to be shifted away from active region of the flow function when the mass flow rate is strictly postive, which is useful for optimisation purposes.

**Comment by mwetter** [comment]
I don't understand, because `deltaM = 0` yields `m_flow_turbulent=0` for which the equations are not defined because of division by zero. Also, you will get `m_flow = k * sqrt(dp)` which has infinite derivative.

**Comment by Mathadon** [comment]
I would set `deltaM=1e-6` such that the regularisation still exists, but since `m_flow` is constrained to be slightly positive, e.g. `m_flow>1e-4` the regularisation region would never be entered and therefore the non-differentiability of the first derivative is no problem.

**Comment by mwetter** [comment]
I don't think that is a good idea as the optimization (or a Newton-solver during simulation) will still get a very large 1st derivative. It is bounded if `m_flow > 0`, but very large and hence may cause numerical ill-conditioning (depending on the algorithm).

I don't quite see your use case, would it suffice if you overwrite in your optimization library the `min` attribute, as it is non-final.

**Comment by Mathadon** [comment]
good point, forgot about that!
