### ISSUE TITLE
fix model with 50,000 output intervals

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#765]
@Mathadon 
Is there any reason why you need 50,000 output intervals?
https://github.com/ibpsa/modelica-ibpsa/blame/1114c2061d366394e7765237645cf8e3bfcca738/Annex60/Resources/Scripts/Dymola/Fluid/Movers/Validation/PumpCurveDerivatives.mos

(Note that `PrescribedOutletState.mos` also has that many intervals, but I can fix this because I revise that model.)

**Comment by Mathadon** [comment]
I can't think of any. Sounds like overkill!
