### ISSUE TITLE
runUnitTests.py

### ISSUE THREAD

**Issue by tsnouidui** [ibpsa/modelica-ibpsa#774]
@mwetter and others: Is there any reason why the `runUnitTests.py` we have on the IBPSA repo differs from the one on the Buildings library repo? Should we update the one on the IBPSA repo to be the same as the one on Buildings? Otherwise the one on IBPSA won't be checking for instance the validity of mo/mos files?

**Comment by Mathadon** [comment]
I don't know :)

**Comment by mwetter** [comment]
@tsnouidui Please incorporate the changes from the Buildings repo to the IBPSA repository. We don't merge the bin directory, this is why your changes on the Buildings repo did not get overwritten.
