### ISSUE TITLE
Block for analytic solution of parallel valves when mass flow rate is prescribed

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#775]
I made a block that computes the flow rates without an algebraic loop for a system of two parallel valves when the total flow rate of these valves is prescribed. This can lead to smaller algebraic loops in specific cases.

Todo:
 - [ ] Add this to `Valves.Subcircuits`
 - [ ] Add clear demonstration of where this makes a difference
 - [ ] Illustrate two valves on icon
 - [ ] Find appropriate way to expose flow ports based on flow direction.
 - [ ] Add flow chart in documentation that explains where such a block could occur.

**Comment by Mathadon** [comment]
Note to self: such a block leads to funny results when two closed valves are put in parallel and then a mass flow rate is forced through it using a mass flow source. The inconsistency between the two regularisation regions causes the pressure difference to become very large such that the absolute pressure becomes negative. This crashes the model.

**Comment by Mathadon** [comment]
I expect to have time for this after new year.

**Comment by mwetter** [comment]
I will close this due to inactivity.
