### ISSUE TITLE
revise flow functions for easier analytic manipulation

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#782]
Variable `k` could be eliminated from the flow functions, which may lead to smaller algebraic loops. This issue aims to figure out how large the impact of such a revision would be.

**Comment by Mathadon** [comment]
Some analysis from what I remember from a few months ago:
I did some tests and, although this works, the problem seems to be that the flow functions must have exactly the same arguments: dp_turbulent or m_flow_turbulent (depending on the value of `from_dp`). The problem is that we use m_flow_turbulent as an argument and we compute dp_turbulent internally. So unless we want to duplicate the computation of dp_turbulent everywhere, this won't be practical. Finally, the alias variable elimination of the tool should work very well for this.

**Comment by mwetter** [comment]
Closed for now unless someone starts working on it again.
