### ISSUE TITLE
Semantic Versioning in Modelica and consequences for libraries

### ISSUE THREAD

**Issue by marcusfuchs** [ibpsa/modelica-ibpsa#786]
I wanted to ask your opinions on the general issue of using semantic versioning for a Modelica library like this one:

While the [Wiki in this repository does not mention semantic versioning ](https://github.com/ibpsa/modelica-ibpsa/wiki/Release-Version#making-a-release), e.g. the [Wiki of the Buildings library](https://github.com/lbl-srg/modelica-buildings/wiki/Release-Version#making-a-release) contains the following:

> We use semantic versioning as described at http://semver.org/. Hence, major version X (X.y.z | X > 0) must be incremented if any backwards incompatible changes are introduced to the public API

To me, it is not yet clear, how we will proceed for the Modelica IBPSA Library and what the implications are. That includes the question what exactly "the public API" is. 

E.g. we currently have 3 open issues that would introduce non-backwards compatible changes. After adressing these issues and merging, will this automatically bump e.g. the Buildings library from v4.0.0 to v7.0.0? And how will we handle that for the Modelica IBPSA Library?

**Comment by Mathadon** [comment]
I think the idea is to group non-reverse-compatible changes into a single release and only then uncrease the major version. Which raises the question: when do we create a new release for IBPSA? For IDEAS I'm also thinking about not strictly following that versioning method since it could increase the IDEAS major version every time that we merge IBPSA, which could be quite often.

**Comment by marcusfuchs** [comment]
I agree that collecting these changes into a single release would be an option. Yet, as e.g. pull request #763 aims to merge into the `master` branch, I am wondering whether that would lead us to v2.0.0 under semantic versioning? In general, I think the semantic versioning concept is very appealing, but I must admit that I am not yet sure how a good workflow for a Modelica library should look like. Therefore, I thought that it would be interesting to discuss this here.

**Comment by tbeu** [comment]
Having the examples within a Modelica package, then moving example models (as reported e.g., by RWTH-EBC/AixLib#352) also calls for an increase of the major version number.

**Comment by mlauster** [comment]
Seems we are again not the first ones breaking their head about SemVer:
https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e
https://news.ycombinator.com/item?id=13378637

My favorite: "Some pieces of software are like icebergs: a small surface area that's visible, and a mountain of private code hidden beneath. For those types of packages, something like SemVer can be helpful. But much of the code on the web, and in repositories like npm, isn't code like that at all — there's a lot of surface area, and minor changes happen frequently."

Unfortunately, they do not provide a better solution...

This repo
https://github.com/Software-Development-Guidelines/Explicit-Versioning
recommends four digits and a slightly different view on versioning

**Comment by thorade** [comment]
To my understanding, adding things (with appropriate defaults) does not require the X in X.Y.Z to be changed, as it would not break any users models. Renaming models, moving models, renaming parameters or any public variable would require the X to be changed.

But you can of course make a release every couple of months only, and each release then contains 100 such changes. Then one can have maintenance Y versions than branch off from a X release and just contain fixes, but no interface changes.
Once tools like Teaser or similar are really stable and widely used, they would to my understanding indeed require the X (the interface) to be stable.

Semver has also been discussed in the context of [impact](https://github.com/impact/impact):
Sec 3.2 of https://doi.org/10.3384/ECP14096543
Sec 3 of https://doi.org/10.3384/ecp15118725

**Comment by tbeu** [comment]
So is IPBSA foolowing semver then or not?

**Comment by mwetter** [comment]
We should follow semver, with the caveat that it is not entirely clear what semver is for Modelica. The MA had a lengthy discussion about this.
