### ISSUE TITLE
data for wilo IP-E 50/150-4/2

### ISSUE THREAD

**Issue by icupeiro** [ibpsa/modelica-ibpsa#789]
I have introduced data for a Wilo IP-E 50/150-4/2

Power and pressure data is included for points {0, 10, 20, 30, 40, 50, 60} m3/h

However you can see in the attached file that for the pressure, the first three points (Q of 0, 10 and 20 [m3/h]) the H is constant, and the model recommends a minimum drop between points. Should this issue be approached or it is a minor one?

[wilo p01 and p02 curves.pdf](https://github.com/ibpsa/modelica-ibpsa/files/1040689/wilo.p01.and.p02.curves.pdf)

**Comment by mwetter** [comment]
@icupeiro Please add a small decrease so that the warning disappears. Otherwise we cannot guarantee that a unique solution exists, which could lead to non-convergence.

**Comment by icupeiro** [comment]
@mwetter minimum required decrease added

**Comment by Mathadon** [comment]
@icupeiro fyi, this is also what I did for my pump models, most of which are in the IBPSA library.

**Comment by mwetter** [comment]
Closed as this is now on the master
