### ISSUE TITLE
ThreeWay valves' documentation and code need to be corrected

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#800]
This issue is to address https://github.com/lbl-srg/modelica-buildings/issues/795

**Comment by mwetter** [comment]
@YangyangFu : Thanks for the report. I addressed the documentation error at the upstream IBPSA library.

Why do you think `CvData` is not propagated? I think they are all set correctly. See also the test
`IBPSA/Fluid/Actuators/Valves/Validation/ThreeWayValveParameterization.mo` on the branch `issue800_threeWayValves` that I added.

**Comment by YangyangFu** [comment]
@mwetter: Thanks for your explanation. I had some misunderstanding before. Now it's clear.
