### ISSUE TITLE
Pump derivative

### ISSUE THREAD

**Issue by tsnouidui** [ibpsa/modelica-ibpsa#812]
`IBPSA.Fluid.Movers.Validation.PumpCurveDerivatives` fails verification on JModelica (Jenkins) after changing exact derivative with approximation.

**Comment by tsnouidui** [comment]
@mwetter I looked at the mos file for this example and saw that it is using Euler for the time integration. Is there any reason to use Euler as opposed to Dassl/CVODE which is used by JModelica? 

The problem I believe to see is that Euler is using the fix (default) integration step of 0.002 which seems to be too loose for the derivative approximation case. I hence suggest to either use Dassl (which is closer to what JModelica is using) or tighten the integration step.

**Comment by mwetter** [comment]
I don't see a reason why not to use Dassl.
