### ISSUE TITLE
Tighten tolerance for FlowJunction model

### ISSUE THREAD

**Issue by tsnouidui** [ibpsa/modelica-ibpsa#814]
The following model fails verification on Jenkins 

``IBPSA.Fluid.FixedResistances.Examples.FlowJunction``

https://jenkins.jmodelica.org/job/JM-trunk_IBPSA-trunk_verify/lastSuccessfulBuild/artifact/diag/29500167_result_report.html
@mwetter I propose to tighten the tolerance of the model as a potential solution to the issue.
Any other measure you could think of?

**Comment by mwetter** [comment]
@tsnouidui Yes, please try a tighter tolerance.
