### ISSUE TITLE
Documentation of travis

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#816]
In https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Resources/Scripts/travis/usr/local/bin/dymola
we have
	  
```
Xvfb :77  -extension RANDR & \
export DISPLAY=:77.0 && \
```

I think this is required for running Dymola without a display? What do these commands do exactly? I'll then add some documentation in the file. I was able to use this to run dymola from ssh.

**Comment by thorade** [comment]
Here are two pieces of info:
https://stackoverflow.com/questions/39904247/can-i-launch-dymola-without-the-gui
https://kb.dsxclient.3ds.com/mashup-ui/page/resultqa?id=QA00000047306e
And Wikipedia on Xvfb:
https://en.wikipedia.org/wiki/Xvfb
