### ISSUE TITLE
More detailed equal percentage valve

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#821]
On page 5 of https://www.downloads.siemens.com/download-center/Download.aspx?pos=download&fct=getasset&id1=A6V10416372 . The flow characteristic for a specific Siemens valve is outlined. This equal-percentage three-way valve consists of a linear valve and an equal-percentage valve where the equal-percentage valve also has a linear part for small valve openings. I'm seeing some model mismatch in my validations that is probably caused by this. It would be good if we could extend existing models to support this.
Do we add a second equal percentage valve, or do we provide an option in the existing one? At the same time we could consider moving some of the valve parameters (rangeability, valve leakage) to the advanced section.

**Comment by mwetter** [comment]
@Mathadon 
I suggest you add a new valve that has this characteristic.
Moving the rangeability and leakage to an Advanced tab makes sense.

**Comment by Mathadon** [comment]
@mwetter I'll have a look at it when I find some time! Do you have any objections against using a polynomial fit to the actual flow curve. I think this will be more efficient than setting up another regularisation between the linear and equal-percentage regimes.

@mlauster you happend to know what the "VDI/VDE2173" standard (see url above) specifies exactly about equal percentage characteristics?

**Comment by mwetter** [comment]
@Mathadon I wonder why a polynomial fit would be more efficient than a regularization? For polynomial fit, you could use the cubic hermite spline interpolation as this can take care of monotonicity and also the extrapolation outside the valid region. For an arbitrary polynomial, you would need to figure out how to make sure it is well behaved for the data that are used to identify its coefficients, which would not be trivial.

**Comment by Mathadon** [comment]
Well, that's assuming that the flow curve is not parameterised. I.e. such that it is always as drawn in the figure in the url above. The coefficients could then be defined off line. The question is of course whether there exist a lot of variants of this valve, which would require parameterisation.. An alternative would be to simply make a 'ValvePolynomial' such that everybody can implement their specific valve using a polynomial curve. This is similar to `IBPSA.Fluid.Actuators.Valves.TwoWayTable`, with the difference that polynomials can be differentiated (i.e. optimised) and tables can't. So maybe that's a better idea?

**Comment by mlauster** [comment]
Sorry, I'm not familiar with this guideline, but it should be in English too. :)
