### ISSUE TITLE
Array dimension mismatch

### ISSUE THREAD

**Issue by thorade** [ibpsa/modelica-ibpsa#831]
OpenModelica complains about non-matching dimensions of arrays:
https://libraries.openmodelica.org/branches/master/IBPSA_latest/IBPSA_latest.html
- https://libraries.openmodelica.org/branches/master/IBPSA_latest/files/IBPSA_latest_IBPSA.Fluid.MixingVolumes.Validation.MixingVolumeTraceSubstanceReverseFlow.err
- https://libraries.openmodelica.org/branches/master/IBPSA_latest/files/IBPSA_latest_IBPSA.Fluid.MixingVolumes.Validation.MixingVolumeTraceSubstanceReverseFlowPrescribedHeatFlowRate.err

**Comment by mwetter** [comment]
@thorade This looks to me like OpenModelica does not propagate the change in the Medium constant `extraPropertiesNames` to the instance `bou`.

**Comment by thorade** [comment]
Ok
