### ISSUE TITLE
filename too long

### ISSUE THREAD

**Issue by thorade** [ibpsa/modelica-ibpsa#855]
Windows seems to limit filenames (including path) to 260 characters by default.
@vishen89 today was not able to clone to `C:\Users\Vishen\Desktop\Modelica\BuildingSystems` but instead had to clone to `C:\Modelica\BuildingSystems`
There is no immediate action required, just posting it here in case anyone else runs into the same problem.

![filename_too_long](https://user-images.githubusercontent.com/314571/32550197-7e019970-c48c-11e7-9bd7-bcae4f3ef5f0.PNG)

**Comment by ainderfurth** [comment]
Agreed, I am running into the same issue. Especially when the library is a submodule in another project.

Is there a possibility to make filenames in IBPSA/Resources/ReferenceResults/Dymola/ shorter?
