### ISSUE TITLE
Update reference results to Dymola 2018FD01

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#867]
This branch is to update the reference results as discussed in https://github.com/ibpsa/project1/wiki/2017-10-05-library-development#update-of-reference-results-to-dymola-2018

**Comment by mwetter** [comment]
Note that `loadResources` had to be removed from the weather data reader to avoid an error in Dymola's pedantic check. Instead, `loadResources` need to be declared together with the declaration of the weather data file. See https://github.com/ibpsa/modelica-ibpsa/commit/24f126d40654b21e9ac6b7dad06fecc92bd496c9

**Comment by mwetter** [comment]
Assignments such as
```modelica
filNam="modelica://IBPSA/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos")
```
need now be written as
```modelica
filNam=Modelica.Utilities.Files.loadResource("modelica://IBPSA/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos"))
```
otherwise the url will not get resolved. Note that the Dymola GUI automatically inserts a call to `loadResources` when a data file is selected.

This has been added in https://github.com/ibpsa/modelica-ibpsa/commit/cf4504f952f219704ba2e394dc8691423f4a9ecf

**Comment by sgtlove** [comment]
Good day to you.

My name is Sgt.Leigh A. Hester,i will like to be your friend ,if you care please reply me back in my private email ( Hester.Ann.leigh87@gmail.com ) So that i will tell you more about my self .
