### ISSUE TITLE
Plugflow pipe fails to translate in JModelica

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#869]
The plugflow pipe fails to translate in JModelica.

**Comment by Mathadon** [comment]
What error message do you get?

**Comment by mwetter** [comment]
The error is
```
In components:
    pip.heaLos_a
    pip.heaLos_b
  Calling function Medium.specificEnthalpy_pTX(): types of positional argument 3 and input X are not compatible
    type of 'inStream(port_a.Xi_outflow)' is Real[0]
    expected type is Real[1]
```
I am not convinced that JModelica properly resolves the medium dependencies, but the bug fix provided in the pull request works around it.

**Comment by Mathadon** [comment]
Looks like a bug, indeed! Nice fix :)
