### ISSUE TITLE
Inverse sensor implementation

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#881]
I could use a component that essentially does the invers of a fluid sensor: it _sets_ either `h_outflow`, `Xi_outflow` or `C_outflow` of a flow that passes through the component to an input value/vector of the component. Sensors do the opposite: they read the value. I'd make a single component that allows setting all three variables using conditionally enabled inputs, similar to `MassFlowSource`.  I suppose that I can add this? Any suggestions on where to put it?

**Comment by mwetter** [comment]
For h and Xi, you could use the ideal heater or ideal humidifier, assuming this serves your purpose. For C, it may be best to put a similar class in `Fluid.Sources`.

**Comment by Mathadon** [comment]
I was thinking about a model that allows to set all properties at once, since you can set all properties with `Boundary_pT` too. I'll at this to `Fluid.Sources` then!

**Comment by mwetter** [comment]
That sounds good.

**Comment by Mathadon** [comment]
closed through #917
