### ISSUE TITLE
Use Xi as input for source models & removing BaseProperties

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#882]
Currently, the models in `IBPSA.Fluid.Sources` allow the use of an input for `X`, while in many cases `X` is not directly available. E.g. a `FluidPort` only contains the independent fractions `Xi`. I would like to add the option to use `Xi` as an input instead of `X` to avoid having to do obsolete computations to compute `X` from `Xi`. This process is error-prone and annoying since you're often working with multidimensional vectors. I can't see any downside if we add this option in an advanced tab to avoid confusion with users about the difference between using `X` and `Xi` as an input. 

A related issue: these models instantiate `Medium.BaseProperties`. I'm not sure why this is the case, possibly to the check consistency of `X`, temperatures that are out of the bounds, etc? In any case, I'd like to add the option to remove this instantiation since it introduces additional equations and/or translation time to the problem.

Any remarks before I implement this?

**Comment by mwetter** [comment]
Both are worthwhile, but maybe we can move `X` to the advanced tab rather than `Xi`. `Xi` is more useful in my view.

Can you check whether removing `Medium.BaseProperties` indeed gives faster translation and simulation. I would think the overhead is small, and it allows to catch unreasonable user input.

**Comment by Mathadon** [comment]
Using this example
```
model Boundary
  parameter Integer n = 200;
  Boundary_pT[n] bou(
    redeclare package Medium = Medium,
    each use_p_in=true,
    each use_T_in=true);
  Modelica.Blocks.Sources.Cosine cosine(freqHz=1, offset=1e5);
  Modelica.Blocks.Sources.Cosine cosine1(offset=290);
  replaceable package Medium = IBPSA.Media.Air;
equation 
  for i in 1:n loop
    connect(bou[i].p_in, cosine.y);
    connect(cosine1.y, bou[i].T_in);          
  end for;
end Boundary;
```

I get following translation/simulation times (seconds) for 1e5 steps.

With `BaseProperties` 
```
n=200 - 15/0.555
n=400 - 21/1.19
n=600 - 32/1.61
```

Without
```
n=200 - 5/0.0344
n=400 - 5.5/0.0328
n=600 - 7/0.0371
```

I'll make `BaseProperties` conditional with default enabled?

**Comment by Mathadon** [comment]
I verified the analysis with

```
model Boundary
  parameter Integer n = 200;
  IDEAS.Fluid.Sources.Boundary_pT[n] bou(
    redeclare package Medium = Medium,
    each use_p_in=true,
    each use_T_in=true);
  Modelica.Blocks.Sources.Cosine[n] cosine(freqHz=1:n, offset=1e5);
  Modelica.Blocks.Sources.Cosine[n] cosine1(freqHz=1:n, offset=290);
  replaceable package Medium = IBPSA.Media.Air;
equation 

    connect(bou.p_in, cosine.y);
    connect(cosine1.y, bou.T_in);

end Boundary;
```
which results in comparable results. The clue could be that the `asserts` are function calls that cause a lot of overhead.

**Comment by Mathadon** [comment]
Old implementation
Translation/simulation times for the example above (n=200):

Old implementation with input verification: 20s / 3.7 s
New implementation with input verification: 18s / 3.6 s
New implementation without input verification: 8.5s / 0.0556 s
