### ISSUE TITLE
Records for valves

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#883]
We currently have records for pumps and fans. It would make sense that we provide this option for valves too. The user then only needs to know the valve manufacturer type and relevant parameters are then filled in automatically. More advanced parameters like the valve rangeability then do not need to be known by the user. Also, custom, computationally efficient implementations such as `ValvePolynomial` can be used more easily.

One thing to be careful about: real valves usually have a separate motor. This is currently not supported by the library: e.g. a valve may be linear, but the valve motor can sometimes have an equal percentage characteristic, meaning it should be modelled by an equal percentage valve. Furthermore, the motor could have a mechanical switch to switch between a linear or equal percentage characteristic. Therefore it could make sense to add separate motor models too?

**Comment by mwetter** [comment]
@Mathadon : Do you have documentation regarding these valve motors? I thought this is always done by using a different physical construction of the valve rather than by changing the motor position. How would the data then be used? Would you have a valve data, and a motor data, and these need to be combined if a user selects the option to model the motor non-linearity?

**Comment by Mathadon** [comment]
@mwetter see top of page 4 of https://www.downloads.siemens.com/download-center/Download.aspx?pos=download&fct=getasset&id1=10445 for an example. 

I'm not sure how the motors should be integrated, which determines how the parameters should be set. It adds a level of complexity that many users may not understand. 

I was thinking of a replaceable motor model as part of the valves, in an advanced tab, that simply has one input and output and no dynamics. The motor could then also be linear/equal percentage/polynomial/record.

**Comment by mwetter** [comment]
@Mathadon : Thanks for the link. If you need such a switch, it would be best to put it on a "Motor" or an "Advanced" tab with the default being linear. Maybe an enumeration that picks linear (default) or equal percentage could be used. I would be surprised if anyone needs a polynomial or a record; this could be added later in a backward compatible way if we use an enumeration to pick the motor type.
