### ISSUE TITLE
revising parameters

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#889]
All,

As suggested earlier, I propose to have a sweep through the (Fluid) library to move some parameters to advanced tabs. E.g. `IBPSA.Fluid.Actuators.Valves.TwoWayEqualPercentage` has following parameters:
- Medium
- l
- kFixed
- R
- delta0
- m_flow_nominal
- dpValve_nominal
- dpFixed_nominal
- CvData
- Kv
- Cv
- Av
- deltaM

This is a bunch of parameters while the 'core' parameters are `dpValve_nominal` and `m_flow_nominal` and the others don't matter that much.

We should be able to indicate better to the user what are the important parameters. Therefore I propose to move parameters (e.g. `l`, `deltaM`, `delta0`, `kFixed`) to advanced (or other) tabs. On the main parameter view we could also use `Dialog(group=... (optional))` to better reflect when a parameter is optional, in this case e.g. `R`, `CvData`, `Kv`, `Cv`, `Av`, `dpFixed_nominal`.

The question is however: how do we objectify what parameters are important? If we can agree on some general guidelines for this, we can add it to the wiki and I can have a sweep through the library to implement them.

I was thinking of defining three parameter categories:
1) Important parameters: those parameters that describe the core behavior of the model and that have a significant impact on model results. They usually do not have a default value.
2) Optional parameters: parameters that can have a significant impact on model results, but that have a good default value.
3) Advanced parameters: parameters that are not really related to model physics, but more to its numerical implementation.

Categories 1 and 2 should be on the main tab, but with 2) clearly indicated as optional. Category 3) should be on the advanced tab.

Note that this implies that `m_flow_nominal` is sometimes in 1) and sometimes in 3). Given the partials that we use, it may be difficult to adhere to these guidelines in some cases.

**Comment by mwetter** [comment]
This would be good to demonstrate. A couple of comments:
- `m_flow_nominal` should stay on the main tab for two reasons: In Dymola, if you have two models A and B, with A having `m_flow_nominal` on the advanced tab, and B having `m_flow_nominal` on the main tab, then if you click both models to set their parameters, then `m_flow_nominal` is on the advanced tab if you first click on A, and on the main tab if you first click on B.
- although in some models, `m_flow_nominal` is "only" used for numerical reasons, you can get really bad results or ill conditioning if you are off by orders of magnitude.

**Comment by Mathadon** [comment]
Closing since I have no time to work on this.
