### ISSUE TITLE
propagating filter order in valves

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#891]
I sometimes reduce the filter order of valves from 2 to 1 to be able to use larger time step sizes with Euler. I currently override this parameter manually, however the filter is protected such that this leads to a warning. Therefore, I'd like to propagate the filter order to the advanced tab of the valve partial. Is that ok?

**Comment by mwetter** [comment]
@Mathadon 
In general. propagating the order of the filter is fine. Maybe it would be clearer to put it on the "Dynamics" tab as all other filter parameters are there (and any tab other than the "General" are considered advanced?).

I do however wonder if you still need a filter if you use (fixed?) time step Euler. If your time step is a minute or two, the valve would already be halfway or fully opened between steps (if `riseTime=120`).

**Comment by Mathadon** [comment]
I agree regarding the tab choice, I use 'Advanced tab' to refer to any non-'general' tab. 

I mostly use the state to decouple algebraic loops so the actual behavior of the filter does not matter that much.
