### ISSUE TITLE
should check zero m_flow_nominal in movers

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#908]
I mistakenly tried to set a constant flow rate of 0 kg/s by setting `m_flow_nominal` in `FlowControlled_m_flow` instead of by setting `constantMassFlowRate`. This produces the following error 

```
Model error - division by zero: (0.1*(pump1.eff.dpMax*pump1.eff.delta^2)) / (pump1.eff.V_flow_max) = (5) / (0)
```

It would be good to add an assert that verifies that `m_flow_nominal` is strictly positive?

**Comment by mwetter** [comment]
A check on `m_flow_nominal > eps` in the fan would be good.
