### ISSUE TITLE
final modifier for timeZone, lon, lat

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#918]
`ReaderTMY3` has

```
  final parameter Modelica.SIunits.Angle lon(displayUnit="deg")=
    IDEAS.BoundaryConditions.WeatherData.BaseClasses.getLongitudeTMY3(
    filNam) "Longitude";
  final parameter Modelica.SIunits.Angle lat(displayUnit="deg")=
    IDEAS.BoundaryConditions.WeatherData.BaseClasses.getLatitudeTMY3(
    filNam) "Latitude";
  final parameter Modelica.SIunits.Time timZon(displayUnit="h")=
    IDEAS.BoundaryConditions.WeatherData.BaseClasses.getTimeZoneTMY3(filNam)
    "Time zone";
```

In IDEAS we allow the user to define these values and we should therefore be able to change these (fixed) values. Due to the fixed attribute this generates warnings unless I manually modify the code every time that I do an IBPSA merge. Therefore I'd like to remove these final modifiers. Is that okay? Probably I should move the parameters to a separate tab such that the user does not wonder what to do about them?

**Comment by mwetter** [comment]
@Mathadon : What is the use case for overwriting the `lon` and `lat` from the weather file? The solar data in the weather file are only valid for these `lon` and `lat` values, hence you can get unreasonable results if your sun path is not consistent with the solar data. Wouldn't you want `lon` and `lat` from the data reader and then use these data in other models?

**Comment by Mathadon** [comment]
Good point.. It's a bit tricky. We allow the user to define custom values for `lon` and `lat` in case he wants to use a different weather data reader. E.g. I have a separate weather data reader for Solarwind. For consistency reasons these `lon` and `lat` values are propagated to `ReaderTMY3`. But in that case the reader is removed so the value does not need to be propagated.. Also, our weather files do not contain the `lat` and `lon` values but I guess that is bad design on our side.
Let me check if I can work around this.

**Comment by mwetter** [comment]
@Mathadon Could you work around this and can this issue be closed?

**Comment by Mathadon** [comment]
I'll figure it out when we do another IBPSA merge. I'll reopen if I have any issues then. Thanks!
