### ISSUE TITLE
Remove dependency on obsolete models

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#934]
The `IBPSA.Media` package has various models that extend
`Modelica.Media.Examples.Tests.Components.PartialTestModel`. However, this, model is flagged as obsolete in MSL 3.2.3 beta1, which will fail the regression tests if MSL 3.2.3 is used. I suggest to change these models to no longer extend from `Modelica.Media.Examples.Tests.Components.PartialTestModel` so that they simulate in the pedantic mode with MSL 3.2.3 beta1

**Comment by mwetter** [comment]
We decided to remove these test models.

**Comment by thorade** [comment]
Tests were removed in this PR: https://github.com/modelica/ModelicaStandardLibrary/pull/2542

**Comment by beutlich** [comment]
Modelica.Media.Examples.Tests.Components.PartialTestModel is moved to Modelica.Media.Examples.Utilities.PartialTestModel

**Comment by thorade** [comment]
Will IBPSA switch to MSL 3.2.3 immediately once it is released? 
MSL 3.2.3 is not shipped with Dymola (not sure about the freshly released 2019), so it might be inconvenient for some users.

**Comment by mwetter** [comment]
I don't plan to switch immediately. It is better to wait until tools ship
MSL 3.2.3
Michael

**Comment by beutlich** [comment]
IIRC IBPSA was one of the main drivers of the MSL license switch.

**Comment by mwetter** [comment]
@beutlich : That's correct and having cleared the license situation helps a lot for our projects, but for users that use the IBPSA or Buildings library with their own installation of a Modelica tool, it is better to wait a few months until the tools ship the new MSL.
This would be another nice use case for a Modelica package manager that downloads the right version if it is not already distributed with a tool.

**Comment by mwetter** [comment]
I close this issue as this will be addressed in https://github.com/ibpsa/modelica-ibpsa/issues/1135
