### ISSUE TITLE
Add thermal network substation

### ISSUE THREAD

**Issue by bramvdh91** [ibpsa/modelica-ibpsa#940]
@annvdm and I are starting to look into a substation model for thermal networks. 

We see several options for the implementation and would like to discuss first what is needed. 

- Validated model of a real substation (but validation data not yet available)
- Generic model
- Which interface would be needed?
   - four-port, fluid in/out at primary and secondary side
   - fluid in/out at primary side, heat out at secondary side (heat emission system is modelled as part of substation)
- How is the mass flow controlled?
   - Valve control at primary side (central pump)
   - Mass flow driven primary side (decentral pumps)
   - Should mass flow control be included at secondary side (pump/valve)? Or is this just the connection to the heat exchanger?
- Should all of this be included in a single block or should it be modular (control blockx, heat exchanger)
- Indirect or direct district heating? (Heat exchanger not necessary in latter case)

@mwetter, did you already have an idea of which functionalities you would like to see included in such a model?

**Comment by mwetter** [comment]
@bramvdh91  What about implementing the substations that are shown in Chapter 8 in http://www.verenum.ch/Dokumente/PLH-FW_V1.1.pdf as these seem to be common configurations.

**Comment by Mathadon** [comment]
@bramvdh91 and @annvdm are no longer working at KUL so I think this issue can be closed.
