### ISSUE TITLE
merge Buildings heat pump model into IBPSA

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#944]
I'd like to merge the Buildings heat pump model into IBPSA. @mlauster @thorade would there be an interest for this?

See also https://github.com/open-ideas/IDEAS/issues/731 for some more discussion.

**Comment by mlauster** [comment]
Fine for us. We still have our own models and will keep using them, but having another model at that stage of library development is okay from my point of view. We wil anyway add another modular heat pump model, see https://github.com/RWTH-EBC/AixLib/issues/407.
