### ISSUE TITLE
LossLessPipe does not simplify when allowFlowReversal=false

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#949]
`IDEAS.Fluid.FixedResistances.LosslessPipe` does not simplify its equations when allowFlowReversal=false. This should be fixed.

**Comment by bramvdh91** [comment]
I guess the same holds for the PlugFlow models, as they have a similar basis. Interested to look further into this with you.

**Comment by Mathadon** [comment]
@bramvdh91 sure, let's have a look at it next week!
