### ISSUE TITLE
update reference results for Dymola 2019

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#957]
This branch is to update the reference results for Dymola 2019

**Comment by mwetter** [comment]
Note that with Dymola 2019 and the dassl solver, only one result point seems to be stored if there is an event:
![image](https://user-images.githubusercontent.com/1329080/41802675-5a621370-7637-11e8-8713-0bf5706a0dd7.png)
With Dymola 2018FD01, `del.y` has a step change, not a ramp, in the results.
If the solver is changed in Dymola 2019 to Cvode, then there is a step change. I therefore change the dassl solver to Cvode in these tests. Note that JModelica also uses Cvode by default.

**Comment by Mathadon** [comment]
@mwetter perhaps this is a bug or there exists a new option? Did you report it?

**Comment by mwetter** [comment]
@Mathadon : In Dymola 2019, `Advanced.EfficientMinorEvents` is now by default true. It used to be false. This causes dassl, but not Cvode, to only produce one result point at the event for BooleanDelay.

I suggest to 
1. add in BuildingsPy the line `Advanced.EfficientMinorEvents=false;`
2. keep the solvers that are already changed to `Cvode` in some of this branch, as there is no drawback in using `Cvode`.

If we don't do 1, then all `dassl` solvers should be changed to `Cvode`. Otherwise we introduce a challenge for the verification simply because dymola does some more efficient computations now that cause lower resolution of step changes in the output.

**Comment by Mathadon** [comment]
agreed!

**Comment by mwetter** [comment]
This is now on the master.
