### ISSUE TITLE
add butterfly valve model 

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#975]
We currently do not have a model for a butterfly valve. Typically these valves are used for open/closed operation only, however in some cases they are used for control too. In these cases it would be good to have a somewhat accurate valve characteristic.

Some sources for such characteristics:
 - http://cgproducts.johnsoncontrols.com/MET_PDF/347VB2.PDF?x=86 p13 figure 6
 - https://www.engineeringtoolbox.com/butterfly-valves-flow-coefficients-d_224.html
 - CFD study, but which does not seem to provide data for constructing a valve characteristic http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1005.2457&rep=rep1&type=pdf 
 - https://www.sciencedirect.com/science/article/pii/0019057895000240 fig 8
 - https://pdfs.semanticscholar.org/8fa6/277c7729cd5aba9631961cdd214007bdc882.pdf fig 7 (large diameter)
 - http://www.dcsc.tudelft.nl/~bdeschutter/private_20100705_acc_2010/data/papers/1640.pdf figure 3: analytical model
 - https://link.springer.com/chapter/10.1007/978-3-540-75995-9_149 fig 7: experiment + CFD
 - http://blog.opticontrols.com/archives/727 fig 3: flow characteristic can be computed from gain
 - http://www.samson-regeltechniek.nl/2_Markten/Technische_onderwerpen/Selectie_&_trim/Klepkarakteristiek_7_5_4_1.pdf last page
 - https://repository.tudelft.nl/assets/uuid:727d9a2a-a852-4fd7-99b5-b7f045c7d512/318.pdf figure 5
 - http://iopscience.iop.org/article/10.1088/1755-1315/12/1/012098/pdf large diameter
 - http://www.valmatic.com/pdfs/Cavitation_in_Valves_7-22-08.pdf figure 3
 - http://www.polna.com.pl/en/flow-characteristic.html figure 2
 - http://www.valmatic.com/pdfs/SurgeControlinPumpingSystems3-17-09.pdf figure 10

Some questions before I implement this:
 - I propose to implement the characteristic by extending `TwoWayPolynomial`.
 - We could add the valve diameter as parameter that computes a default value for `dp_nominal`, using another polynomial e.g. based on the data in https://www.engineeringtoolbox.com/butterfly-valves-flow-coefficients-d_224.html , or http://cgproducts.johnsoncontrols.com/MET_PDF/347VB2.PDF?x=86 page 22. 
 - The cleanest way to do this would be to add the option `Diameter` to `CvData`, but this would be an invalid option for the other valve models so I don't think is realistic. Unless an `enumeration` can be extended and redeclared. So perhaps it's better to not add the `diameter` option for now, or to implement it as a separate function.
 - Proposed name: `TwoWayButterfly`

@icupeiro @damienpicard this is for Infrax

**Comment by mwetter** [comment]
@Mathadon Using `TwoWayPolynomial` as the base class makes sense.
How would one usually parameterize the valve? Is it common to simply use the diameter, or does one really specify the `Cv` value for butterfly valves? If it is the first, maybe it needs a different base class that does not use `ValveParameters`.

**Comment by Mathadon** [comment]
I think butterfly valves are typically selected such that they match the pipe diameter, since that makes them easy to install.

It looks quite tedious to do the new implementation without using `ValveParameters` and without duplicating code. Perhaps it's better to use `ValveParameters` and to assign `final` default values for `Kv`, `Cv`, etc?

**Comment by Mathadon** [comment]
In 27e0682 I implemented figure 10 from http://www.valmatic.com/pdfs/SurgeControlinPumpingSystems3-17-09.pdf. I should still verify the shape against other sources.

**Comment by Mathadon** [comment]
Butterfly valve in brown:

<img width="681" alt="schermafbeelding 2018-07-07 om 19 49 45" src="https://user-images.githubusercontent.com/5970879/42415513-3d120dd6-8251-11e8-85e3-975be6d4748b.png">

**Comment by Mathadon** [comment]
Could compute Kv from DN value, but sources disagree quite a bit on the pressure drop at fully opened position. That makes sense since some butterfly valves may be thinner than others. However, the Kv curve should be consistent with the Kv value since at closed position all valves probably behave more similarly.

http://www.valvias.com/flow-coefficient-butterfly-valve.php 
http://www.mydatabook.org/fluid-mechanics/flow-coefficient-opening-and-closure-curves-of-butterfly-valves/

**Comment by Mathadon** [comment]
Commit ceadd7b422f9ab921271d0cfe7726ae1aaf98d86 revises the implementation to use a different curve and matching DN->Kv curve based on the data in http://www.mydatabook.org/fluid-mechanics/flow-coefficient-opening-and-closure-curves-of-butterfly-valves/. The curve difference is quite large (see image below) but it's hard to find a good source and clearly these valves have different shapes in practice too, which cause different flow profiles.

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/5970879/102714668-9546ad80-42d0-11eb-88fa-3912345900d6.png">
