### ISSUE TITLE
add nominal values for h_outflow in partials

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#977]
Our `Fluid` partials currently do not define the nominal values of `h_outflow`. Properly chosing these values could affects convergence of algebraic loop solvers. Although I do not have a clear example for this, I'd like to add more appropriate values to be sure.

**Comment by Mathadon** [comment]
This change somehow changed the statistics of one model:
```

*** Warning: Simplified5.mat: Translation statistics for simulation changed for linear, but results are unchanged.
 Old = 27
 New = 26
```

**Comment by mwetter** [comment]
If you set a start attribute, the solver is more likely to use this variable as an iteration variable. This can then affect the symbolic processing.
