### ISSUE TITLE
simplify threeWayValve when no mixing occurs

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#979]
When `PartialThreeWayResistance` has `FlowDirection=Entering` for only one port (e.g. `port_b`) then we can hardcode `port_a.h_outflow=inStream(port_b.h_outflow)` similar to the twoport partials. This omits the `stream` mixing equations and could possibly avoid algebraic loops. Is this a simplification that we want to implement or would it make the code too complex? We would then have 3 different implementations in the model: 1) dynamics, 2) static, 3) static without flowreversal.

**Comment by mwetter** [comment]
Before we add this complexity, is there a realistic use case for which you can show that it makes a difference?

**Comment by Mathadon** [comment]
I have no time to look into this and ideally the tool vendors already make this simplification internally.
