### ISSUE TITLE
Examples.CSVReader requires a pre-simulation that can break unit tests

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#983]
`Examples.CSVReader` requires first the simulation of `Examples.CSVWriter` for the csv file to exists. This will only work with Dymola but not with other tools that won't run the `.mos` script.
The csv file should be stored in a `Data` folder so that the library is portable across tools.

**Comment by Mathadon** [comment]
I see the point, just too bad that we now do not automatically verify that the CSVWriter produces a file that can indeed be read by the CombiTimeTable.
