### ISSUE TITLE
Fix typo in Buildings.Utilities.IO.Files.CSVWriter

### ISSUE THREAD

**Issue by milicag** [ibpsa/modelica-ibpsa#985]
In the info section there is a typo: ```The parameter samplePeriod defines every how may seconds the inputs are saved to the file. ```

**Comment by Mathadon** [comment]
had to read it three times before I saw that 'may' should be 'many' =) feel free to make a pull request?

**Comment by milicag** [comment]
I understood what it said before I noticed the typo. I'll fork and create a PR after I do some more testing, since I'm already at it.
